### ISSUE TITLE
libmabs-mobile.so is too huge

### ISSUE THREAD

**Issue by softkot** [Unact/yandex_mapkit#100]
Just including  yandex_mapkit into the flutter project makes the binaries larger 3-4 times. The libmaps-mobile.so native is 4-5 times larger than flutter app itself in libapp.so

```
arm64-v8a libmaps-mobile.so    │ 48706K
armeabi-v7a libmaps-mobile.so  │ 36676K
x86_64 libmaps-mobile.so       │ 52858K
x86 libmaps-mobile.so          │ 51386K
```

Is it possible to reduce the size ?

**Comment by DCrow** [comment]
Hello!

Unfortunately this is a problem with underlying iOS/Android libraries. 
The only way to reduce the size is to ask YandexMapKit iOS/Android developers to reduce their library sizes.
