### ISSUE TITLE
Переход на null-safety.

### ISSUE THREAD

**Issue by kidok313** [Unact/yandex_mapkit#101]
Будет ли миграция yandex_mapkit на null-safety?

**Comment by kirill-plotnikov** [comment]
pubslec.yaml

yandex_mapkit:
   git:
      url: https://github.com/Unact/yandex_mapkit.git

**Comment by kidok313** [comment]
На pub.dev не обновилось, и warning о том что это легаси если просто указать yandex_mapkit: ^0.5.1.

**Comment by DCrow** [comment]
Добрый вечер!

На данный момент на pub.dev null-safety версия еще не выкладывалась. 
В ближайшее время будет выложена.

**Comment by DCrow** [comment]
Версия теперь доступна на pub.dev
