### ISSUE TITLE
Поддержка прямого и обратного геокодирования

### ISSUE THREAD

**Issue by cream-cheeze** [Unact/yandex_mapkit#102]
Добрый день!

В Yandex MapKit есть поддержка прямого (поиск по тексту) и обратного (поиск по точке) геокодирования. Подробнее это описано в [статье на Хабре](https://habr.com/ru/company/yandex/blog/428564/).

В вашем плагине для flutter реализован метод поисковых подсказок getSuggestions, но он возвращает только текстовые подсказки, без координат – если нужно по найденному адресу получить координату, то необходимо обращаться к отдельно стоящему сервису геокодирования. То же и с обратной задачей – по точке, которую пользователь указал на карте, определить полный адрес. 

Обе эти задачи решаются, если использовать [HTTP API геокодирования](https://yandex.ru/dev/maps/geocoder/doc/desc/concepts/input_params.html#input_params__geocode-format), но это требует дополнительной лицензии для коммерческих приложений.

Было бы здорово, если бы появилась возможность работать с прямым и обратным поиском напрямую из плагина yandex_mapkit для flutter.

**Comment by DCrow** [comment]
Доброе утро! 

Да, было бы хорошо иметь такой функционал. 
В целом получается это не много отдельный функционал от `getSuggestions`, в рамках `YandexSearch`.

**Comment by cream-cheeze** [comment]
Скажите, пожалуйста, пока не планируете это реализовывать?
P.S. Спасибо за "Add the ability to get users current point"!

**Comment by DCrow** [comment]
У меня, в целом, не так много времени есть на этот проект, поэтому пока не могу обещать чего-либо.
Всегда готов посмотреть на PR и добавить доработку в проект.

**Comment by cream-cheeze** [comment]
@DCrow, [сделал PR](https://github.com/Unact/yandex_mapkit/pull/119). Посмотрите по возможности, пожалуйста. И ещё  PR с доработками по зуму.

**Comment by cream-cheeze** [comment]
Всё в мастере.
