### ISSUE TITLE
Паддинг для логотипа Yandex.

### ISSUE THREAD

**Issue by kidok313** [Unact/yandex_mapkit#103]
В нашем приложении верх и низ карты находятся за полупрозрачными элементами, и логотип закрывается ими. 
Можно ли каким либо образом изменить расположение логотипа кроме указания logoAlignment?
Подобная проблема на андроид: https://github.com/yandex/mapkit-android-demo/issues/193

**Comment by kidok313** [comment]
<details>
  <summary>Скриншот</summary>

![simulator_screenshot_9CD25671-A1ED-4586-B1B9-0CCFD1E7F999](https://user-images.githubusercontent.com/42135981/118114558-6e5c5580-b3f0-11eb-89f6-6e5cda32e213.png)

</details>
А в центре у айфонов "бровь" которая закрывает логотип.

**Comment by DCrow** [comment]
Доброе утро!

Насколько я знаю YandexMapkit для Android/iOS не дает такой возможности, кроме как этим методом.
