### ISSUE TITLE
How to use the method "YandexMapController().moveToUser()"correctly?

### ISSUE THREAD

**Issue by McFamous** [Unact/yandex_mapkit#104]
I use this method so that when drawing the map, the camera moves to the user's location
![image](https://user-images.githubusercontent.com/55532701/118121933-d3b54400-b3fa-11eb-84bc-b5f5f00e16e3.png)
controller.showUserLayer() - displays the placemark, but the camera does not move

**Comment by DCrow** [comment]
Hello!

This method has been deprecated in newer versions(not yet published on pub.dev). 
Instead it is advised to use combination of `YandexMapController.getUserTargetPoint` and `YandexMapController.move` for moving the camera to user position.
