### ISSUE TITLE
Можно ли объединить маркеры ?

### ISSUE THREAD

**Issue by Kizat** [Unact/yandex_mapkit#106]
Можно ли маркеры объединить и показать количество объединенных объектов в одном маркере при масштабировании карты?

**Comment by DCrow** [comment]
Добрый день!

На данный момент такого функционала нет.
Насколько я знаю, такой функционал есть в нативных либах iOS/Android.

**Comment by cream-cheeze** [comment]
Добавлено в [PR #122](https://github.com/Unact/yandex_mapkit/pull/122)

**Comment by Vitaly26** [comment]
Я использую fluster. Его можно использовать с любыми картами.
https://pub.dev/packages/fluster
https://github.com/alfonsocejudo/fluster_demo
