### ISSUE TITLE
Утечка памяти в iOS 

### ISSUE THREAD

**Issue by Vasiliy-Kravchenko** [Unact/yandex_mapkit#107]
Добрый день! Приложение стало иногда крашиться, выяснилось что в ИОС каждое открытие карт забирает приблизительно 180 МБ памяти и эта память потом не освобождается, и после нескольких раз память заканчивается и приложение падает. Вроде подобную проблему правили в версии 0.3.11 но сейчас стабильно повторяется.

**Comment by Vasiliy-Kravchenko** [comment]
Разобрался где происходит утечка. Я закрывал карту при включенном трекинге камеры enableCameraTracking  тогда у MapCameraListener и YandexMapController создаются ссылки друг на друга и происходит утечка. Решил это обязательным disableCameraTracking при закрытии карты. Может стоит рассмотреть  вариант добавить метод deinit в класс YandexMapController (ios/Classes/YandexMapController.swift) в котором быдет вызываться disableCameraTracking() чтобы даже если забыл сделать disableCameraTracking все равно все корректно очищалось из памяти?

**Comment by DCrow** [comment]
Добрый день!

Действительно, как вы и говорите, утечка в этом месте.

Тут лучше вместо `deinit` использовать weak reference, также как сделано [тут](https://github.com/Unact/yandex_mapkit/blob/master/ios/Classes/YandexMapController.swift#L35-L36). 
В таком случае, GC сможет убрать из памяти ссылку на экземпляр `YandexMapController`, вместе с этим эту ссылку обнулит.

Поправил в мастере. На следующей неделе на pub.dev выложу.
