### ISSUE TITLE
Подписи к placemark'ам

### ISSUE THREAD

**Issue by cream-cheeze** [Unact/yandex_mapkit#109]
Подскажите, пожалуйста, есть ли в плагине возможность добавлять к плейсмаркам подписи, подобные тем тем, что на изображении? 
Я вижу, что есть возможность использовать rawImageData в качестве иконки для плейсмарка, но, скорее всего в приведённом примере, это какой-то отдельный атрибут плейсмарка, а не сама иконка.

![IMG_4BE9CB935140-1](https://user-images.githubusercontent.com/1291107/122398590-b25bf080-cf82-11eb-9a63-b9685c08fb49.jpeg)

**Comment by cream-cheeze** [comment]
Я вот смотрю на объект https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKPlacemarkMapObject.html в документации к мэпкиту и не могу понять, какой атрибут вообще за это может отвечать... 
Знать бы, если не в плагине, то хотя бы в самом mapkit есть такая возможность? Или в приведённом примере люди это вообще сами поверх карты накладывают эти элементы с подписями?

P.S. Документация у Яндекса полный улёт, конечно...

**Comment by DCrow** [comment]
Добрый день!

Этот плагин такой функционал не поддерживает. В либе яндекса, насколько я понимаю, используется [этот](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKPlacemarkMapObject.html#-setViewWithView) метод. 
Судя по всему, используется нативный вью на iOS, который отображается сумму и синюю точку под ней.

**Comment by cream-cheeze** [comment]
Понял, спасибо за ответ.

**Comment by cream-cheeze** [comment]
Пришёл к решению, что проще всего реализовать через картинки. Нашёл функционал составных иконок и реализовал его в [PR](https://github.com/Unact/yandex_mapkit/pull/122). Картинки можно получать, отрендерив flutter виджет (например, с помощью плагина [screenshot](https://pub.dev/packages/screenshot)). Это наиболее универсальный вариант, который я вижу. 

С setViewWithView вообще непонятно как - нужно как-то преобразовывать виджет в нативные вьюхи - по-моему iOS не даёт такое сделать, а вот в андроиде есть [что-то похожее](https://flutter.dev/docs/development/add-to-app/android/add-flutter-view)... Ну либо заранее создавать вьюги в нативном коде и передавать их имена, что криво и сложно. Если видите, как решить эту задачу лучше, подскажите, плз.
