### ISSUE TITLE
removeAll()

### ISSUE THREAD

**Issue by vlkigdm** [Unact/yandex_mapkit#110]
Привет, добавьте метод для 
Removes all map objects from the collection.
(Android - https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObjectCollection.html?lang=ru
iOs - https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKMapObjectCollection.html?lang=ru)
Спасибо.

Что-нибудь такое:
yandex_map_controller.dart
```
  Future<void> removeAll() async {
    await _channel.invokeMethod<void>('removeAll');
    placemarks.clear();
  }
```

YandexMapController.java
```

private void removeAll() {
    MapObjectCollection mapObjects = mapView.getMap().getMapObjects();
    mapObjects.clear();
}

case "removeAll":
      removeAll();
      result.success(null);
      break;
```

YandexMapController.swift

```
public func removeAll() {
  let mapObjects = mapView.mapWindow.map.mapObjects
  mapObjects.clear()
}

case "removeAll":
      removeAll()
      result(nil)
```

**Comment by DCrow** [comment]
Здравствуйте! 

Скорее всего лучше сразу метод, который полностью все геобъекты убирает. Не только Placemark

**Comment by cream-cheeze** [comment]
В [PR #122](https://github.com/Unact/yandex_mapkit/pull/122) добавлен метод clear()

**Comment by DCrow** [comment]
В мастере можно убрать все объекты на карте через `await controller.updateMapObjects([])`
