### ISSUE TITLE
Изменить цвет маркера при 

### ISSUE THREAD

**Issue by statsss** [Unact/yandex_mapkit#113]
Как изменить иконку маркера при вызове onTap:, пробую  через removePlacemark и addPlacemark маркеры не всегда удаляются и соответственно в точке имею кучу дубликатов/багов

**Comment by DCrow** [comment]
Здравствуйте!

Просьба приложить пример. В `onTap` должен всегда передавать тот placemark, которому этот callback принадлежит.

**Comment by cream-cheeze** [comment]
Да, я тоже замечаю, что иногда маркеры накладываются друг на друга, несмотря на то, что я всё делаю последовательно вроде бы - сначала удаляю старые маркеры, а затем добавляю новые.

**Comment by DCrow** [comment]
Закрываю, так как не активности
