### ISSUE TITLE
'Attempt to set invalid focusRect: rect.bottomRight is out of screen; rect.topLeft >= rect.bottomRight;

### ISSUE THREAD

**Issue by akbarpulatov** [Unact/yandex_mapkit#114]
```
controller.setFocusRect(
    bottomRight: ScreenPoint(x: 50, y:  -50),
    topLeft: ScreenPoint(x: 0, y: 0));
```

[https://github.com/yandex/mapkit-android-demo/issues/117#issuecomment-523367417](https://github.com/yandex/mapkit-android-demo/issues/117#issuecomment-523367417)
Здесь написано что точка начало левый верхний угол, но даёт ошибку. Нет ни одного примера? 

![IMG_0152](https://user-images.githubusercontent.com/27597344/123081154-18d78780-d437-11eb-8f55-646280e2afff.PNG)

**Comment by cream-cheeze** [comment]
Здесь есть пример: https://github.com/Unact/yandex_mapkit/blob/master/example/lib/examples/map_controls_page.dart

**Comment by DCrow** [comment]
Здравствуйте!

Как @cream-cheeze говорит, на этой странице можно посмотреть пример.
В целом большинство координатных систем для координат экрана используют систему где левый вверхний угол это (0, 0), а нижний правый имеет (maxX, maxY). Все координаты положительные.
Подробнее описано [тут](https://fcs-cs.github.io/cs1-2018/modules/01-introduction/computer-coordinates/)
