### ISSUE TITLE
No available cache for request

### ISSUE THREAD

**Issue by ivanesi** [Unact/yandex_mapkit#117]
Calling `YandexSearch.getSuggestions()` on Android I'm getting:
 
`W/yandex.maps(32418): std::__ndk1::enable_if: No available cache for request`

<details>
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.5 19F101 darwin-x64, locale en)

    • Flutter version 2.2.0 at /Users/ivan/flutter
    • Framework revision b22742018b (7 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)

    • Android SDK at /Users/ivan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS

    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web

    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)

    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.1)

    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)

    • Pixel (mobile) • FA6BW0303564 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
</details>

**Comment by DCrow** [comment]
Hello!

This seems to be related to https://github.com/yandex/mapkit-ios-demo/issues/85

I think this is a bug with underlying iOS/Android libraries. 
It should clear cache without asking to use only `SearchManagerType.ONLINE`
