### ISSUE TITLE
Convert Android code to Kotlin

### ISSUE THREAD

**Issue by ILAgent** [Unact/yandex_mapkit#123]

**Comment by DCrow** [comment]
Для чего это требуется? Чем плох код на Java? 

Тут больше момент, что либа Android написана на Java, и все примеры, также написаны на Java.
Из-за перехода становится сложнее добавлять новые фичи в проект.

**Comment by ILAgent** [comment]
>Для чего это требуется? Чем плох код на Java?

В 2021 году писать на джаве под андроид - моветон. Да на котлине просто удобнее и писать, и читать.

>Тут больше момент, что либа Android написана на Java, и все примеры, также написаны на Java.

Это не проблема. Android SDK тоже на джаве.

**Comment by cream-cheeze** [comment]
ИМХО Я хоть вообще не в теме андроида и java - впервые столкнулся в этом проекте, но, честно говоря, java по сравнению с другими используемыми языками, кажется ущербной, по крайней мере при текущей версии sdk (так это вроде называется), которая не даёт использовать некоторые языковые конструкции. Ну и про Kotlin слышал, что классный современный язык. 

Кстати, iOS проект сам просится в Swift5 конвертнуться.

**Comment by DCrow** [comment]
В Swift5 перейти особо не проблема, а переход в Kotlin долгая работа. 

В целом хотел понять, в чем может быть проблема с текущим кодом.

Сам не готов переносить все на Kotlin, но не против PR с переносом(чистым, без доработок чего-либо)

**Comment by DCrow** [comment]
Поизучав вопрос по глубже. Общая тенденция среди плагинов(не приложений), оставлять код в Java.
Из-за того что версии Kotlin в проектах, которые используют плагин, могут быть версии либо ниже, либо выше, не всегда удается использоваться плагин, что плохо.(См https://github.com/flutter/flutter/issues/22945) С Java такой проблемы нет.

Пока команда флаттер не придумает нормальный способ разруливать такие ситуации(https://github.com/flutter/flutter/issues/78875), проект тоже будет на Java жить.

**Comment by DCrow** [comment]
Спустя почти два года, тенденция так и осталась оставлять код в Java. 
Пока закрою, если вдруг команда flutter создаст какое-нить глобальное решение, которое позволит избегать проблем с разными версиями котлин, то тогда можно будет перейти.
