### ISSUE TITLE
Зависание карты

### ISSUE THREAD

**Issue by vlkigdm** [Unact/yandex_mapkit#126]
Происходит зависание карты при возврате с фона, при запущенных других приложениях и/или долгого нахождения в фоне. 
Помогает только реинициализация через YandexMapSizeChanged (fix mapkit initialization тоже без толку).

Как повторить: запускаете приложение, уходите в фон, запускаете yandex maps, yandex navigator, google maps и тп ресурсозатратные приложения. При возвращении произойдет зависание.

**Comment by DCrow** [comment]
Добрый день!

Воспроизводится ли это тестовым приложением? 
На Android или iOS или обоих это воспроизводится?
Так же просьба приложить `flutter doctor --verbose`

Не совсем понял каким образом вы реинициализируете через `onMapSizeChanged`

**Comment by vlkigdm** [comment]
1. Да, воспроизводится тестовым приложением на эмуляторе Android 11 (API level 30) и устройстве Android 11 (API level 30), для iOS не смотрел, но воспроизводится на iOS не тестовым приложением.
2. Изменение размера контейнера с YandexMap => YandexMapSizeChangedListener (Java)/MapSizeChangedListener (Swift) onMapWindowSizeChanged => onMapCreated.

**Comment by DCrow** [comment]
Не удается воспроизвести ни на iOS, ни на Android. Под обоими делал как вы описали
1. Запустил приложение
2. Свернул его в фон
3. Запустил набор разных приложений
4. 
После возврата из фона, приложение без особых проблем продолжало работать.

Просьба приложить видео и более детальный способ как это можно воспроизвести

**Comment by vlkigdm** [comment]
1. Видео https://www.youtube.com/watch?v=9KPyAT2Vq7c
2. Релиз версия с yandex_mapkit: 1.1.1. В дебаг версии плагин YandexMapsMobile сообщает о onMemoryWarning.

**Comment by DCrow** [comment]
Поправил проблему с onMemoryWarning, также поменял работу при входе во фон и из него для Android.

Посмотрите сейчас проблему удается воспроизвести?(Используя master ветку проекта)

**Comment by vlkigdm** [comment]
Проблема воспроизводится, да.

**Comment by topor00** [comment]
я тоже столкнулся со схожей проблемой. Но при тестировании на разных устройствах, я наблюдаю данную проблему каждый раз на Xiaomi 9T на Android 10 . Справедливости ради, отмечу, что проверял и на других устройствах xiaomi на android 10 (redmi 9 pro) но такой проблемы не было.

**Comment by vlkigdm** [comment]
Кажется с 8e0fc41 такой баг не встречается.

**Comment by DCrow** [comment]
Хорошо, тогда пока закрываю.

Предположу, что и тут и в #173 одинаковая причина была.
