### ISSUE TITLE
Зависает карта при тройном нажатии на экран

### ISSUE THREAD

**Issue by FuryOfFools** [Unact/yandex_mapkit#130]
Зависает карта при тройном одновременном тапе по карте (например скриншот свайпом). Карту нельзя не скролить не передвигать.
Проблема только на андроиде и почти на всех девайсах проявляется на ios такой проблемы нет.

**Comment by DCrow** [comment]
Добрый день!

Просьба приложить `flutter doctor --verbose`.
Воспроизводится ли у вас это тестовым приложением? 
Если нет, то просьба еще приложить pubspec.yaml и пример кода, которым можно воспроизвести проблему.

Мне не удалось воспроизвести эту проблему тестовым приложением(на Android)

**Comment by DCrow** [comment]
Эта ошибка flutter

Вот тут решается https://github.com/flutter/flutter/issues/60921
