### ISSUE TITLE
перестаёт отображаться слой карты после перехода на новую страницу и обратно

### ISSUE THREAD

**Issue by akhokhlushin** [Unact/yandex_mapkit#131]
перестаёт отображаться слой карты при переходы при запуске камеры. 
самое поганое: кажется, это происходит не всегда, и логику проследить не удалось. Пример как это выглядит на видео.

https://disk.yandex.ru/i/TwULAj1RSUgk3Q

использую версию из гита
такое ощущение что как-то связано с ресурсами, ибо постоянно отображается
W/yandex.maps(23568): yandex::maps::mapkit::map::MapImpl::onMemoryWarning: Got memory warning

**Comment by cream-cheeze** [comment]
@akhokhlushin немного оффтоп, но интересно: а как адрес под pin'ом получаете? Нет же сейчас такого функционала в плагине.

**Comment by akhokhlushin** [comment]
> @akhokhlushin немного оффтоп, но интересно: а как адрес под pin'ом получаете? Нет же сейчас такого функционала в плагине. Через api геокодера?

Да. Пример же есть в такой в /example

**Comment by cream-cheeze** [comment]
> Да. Пример же есть в такой в /example

Серьёзно? Не видел... В любом случае, скоро такое можно будем прямо из плагина получать.

**Comment by akhokhlushin** [comment]
Отлично! :) Но вот хотелось бы с исчезновением слоя с картой разобраться неотображение карты. При этом, она двигается и это особое попадало - координаты пользователь сдвигает и сам об этом не знает.Отправлено с моего телефона Huawei-------- Исходное сообщение --------От: Roman ***@***.***>Дата: сб, 7 авг. 2021 г., 13:32Кому: Unact/yandex_mapkit ***@***.***>Копия: akhokhlushin ***@***.***>, Mention ***@***.***>Тема: Re: [Unact/yandex_mapkit] перестаёт отображаться слой карты после перехода на новую страницу и обратно (#131)



Да. Пример же есть в такой в /example



Серьёзно? Не видел... В любом случае, скоро такое можно будем прямо из плагина получать.

**Comment by akhokhlushin** [comment]
В итоге я вынес виджет на отдельный экран. Такой вот обход проблемы получился

**Comment by DCrow** [comment]
Добрый день

Это происходит только на Android или и на iOS?
А не подскажите это не похоже на проблему описанную в https://github.com/flutter/flutter/issues/61795 ?

Также было бы хорошо приложить `flutter doctor --verbose` и по возможности код, с помощью которого можно было бы воспроизвести.

PS Ошибка 
> W/yandex.maps(23568): yandex::maps::mapkit::map::MapImpl::onMemoryWarning: Got memory warning

появляется, когда на андроиде приложение уходит в фон, это не давно было исправлено.

**Comment by cream-cheeze** [comment]
У меня, кстати, тоже такое случалось на iOS - иногда, когда я возвращаюсь из другого интерфейса к карте, которая уже была загружена, вместо карты - пустое место. Но это происходило, когда я в release mode с устройства работал с приложением, поэтому никаких деталей не удалось получить. Попробую в симуляторе воспроизвести.

**Comment by DCrow** [comment]
Более вероятно что это ошибка flutter, которую тут не разрешить.

Закрываю так как нет конкретного примера.

**Comment by cream-cheeze** [comment]
Вот такое у меня в консоль вываливается, когда карта перестаёт отображаться:

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(unknown_view, trying to set gesture state for an unknown view, view id: '0', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
