### ISSUE TITLE
не линкуется под ios

### ISSUE THREAD

**Issue by akhokhlushin** [Unact/yandex_mapkit#132]
Не линкуется под иос. Читать умею, понимаю, что нет бинарников под armv7, да и кому они нужны. Но как собрать-то? подскажите, пожалуйста

``
ld: warning: ignoring file /Users/admin/development/mechta.online/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile, missing required architecture
    armv7 in file /Users/admin/development/mechta.online/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile (2 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_YMKSearch", referenced from:
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKCircleMapObject", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKPolylineMapObject", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKPolyline", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKCircle", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKLinearRing", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKPolygonMapObject", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKPlacemarkMapObject", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKBoundingBox", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKPolygon", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKSuggestItem", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKCameraPosition", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKSuggestOptions", referenced from:
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKLogoAlignment", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKScreenRect", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKSearchSuggestSession", referenced from:
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKScreenPoint", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKAnimation", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKPoint", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
          objc-class-ref in yandex_mapkit(YandexSearch.o)
      "_OBJC_CLASS_$_YMKIconStyle", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKMapView", referenced from:
          objc-class-ref in yandex_mapkit(YandexMapController.o)
      "_OBJC_CLASS_$_YMKMapKit", referenced from:
          objc-class-ref in AppDelegate.o
          objc-class-ref in yandex_mapkit(SwiftYandexMapkitPlugin.o)
          objc-class-ref in yandex_mapkit(YandexMapController.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
``

**Comment by DCrow** [comment]
Добрый день

Для этого надо указать в настройках BuildSettings проекта, в разделе Architectures указать armv7

Как на скриншоте
<img width="1155" alt="Screen Shot 2021-08-17 at 17 49 18" src="https://user-images.githubusercontent.com/8961745/129748445-aed1e9db-57f8-45d1-8513-509de07ad7e6.png">

**Comment by akhokhlushin** [comment]
спасибо, удалось собрать, но только наоборот, оставив только архитектуру arm64
