### ISSUE TITLE
Включить IconData в параметры для PlacemarkStyle

### ISSUE THREAD

**Issue by k0lourful** [Unact/yandex_mapkit#133]
Возможность брать картинку из ассетов это хорошо, но поддержка иконок из стандартного набора (или пакетов) это ж мастхэв, я считаю.

**Comment by DCrow** [comment]
Добрый день

IconData используется только для работы с виджетом Icon, он не предназначен для использования другими виджетами.

**Comment by k0lourful** [comment]
Ок, можно ли тогда включить поддержку Icon? Если сохранить суть вопроса об иконках
