### ISSUE TITLE
(Android) onMapRendered не работает?

### ISSUE THREAD

**Issue by k0lourful** [Unact/yandex_mapkit#134]
Она будто никогда не вызывается после открытия карты.

<details>
  <summary>Flutter doctor</summary>

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.2.3 at C:\Users\---\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\xt1zer\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • SM A705FN (mobile) • R58M543BNMJ • android-arm64  • Android 11 (API 30)
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 92.0.902.78

! Doctor found issues in 1 category.

</details>

**Comment by DCrow** [comment]
Добрый день!

Подскажите в приложении примере, на странице Map controls example, в консоле у вас есть сообщение "Map rendered"?
Также пожалуйста приложите пример, как вы используете виджет.

В данный момент не вижу проблем с работой метода.

**Comment by k0lourful** [comment]
> в приложении примере, на странице Map controls example, в консоле у вас есть сообщение "Map rendered"?

Есть. И что ещё заметил - метод работает, когда он async. Можно теперь закрыть вопрос, но вот это дело с async выглядит по мне неправильно.

**Comment by DCrow** [comment]
> Есть

Значит дело в том как вы объявили метод.

> И что ещё заметил - метод работает, когда он async.

Он и без него работает, скорее всего вы не верно декларируете метод в своем приложении.

**Comment by k0lourful** [comment]
Очень странная штука. Сейчас уже такой проблемы нет, за это время код не менялся. Пожалуй, проблема больше неактуальна, пока она снова не объявится.
