### ISSUE TITLE
Проблема с загрузкой ассета из iconName в showUserLayer

### ISSUE THREAD

**Issue by xt1zer** [Unact/yandex_mapkit#135]
```
await controller.showUserLayer(
    iconName: 'assets/icons/user-arrow.png',
    arrowName: 'user',
);
```
Отдельный вопрос: что делает arrowName? В документации об этом ничего.

<details>
    <summary>Логи</summary>

    E/yandex.maps(26943): Can't load image from asset: flutter_assets/user
    E/yandex.maps(26943): java.io.FileNotFoundException: flutter_assets/user
    E/yandex.maps(26943): 	at android.content.res.AssetManager.openAsset(Native Method)
    E/yandex.maps(26943): 	at android.content.res.AssetManager.open(AssetManager.java:313)
    E/yandex.maps(26943): 	at android.content.res.AssetManager.open(AssetManager.java:287)
    E/yandex.maps(26943): 	at com.yandex.runtime.image.ImageProvider$2.loadBitmap(ImageProvider.java:103)
    E/yandex.maps(26943): 	at com.yandex.runtime.image.ImageProvider$ImageProviderImpl.getImage(ImageProvider.java:60)
    E/yandex.maps(26943): yandex::maps::mapkit::map::: AndroidBitmap_getInfo() failed! Error code: -1
</details>

**Comment by DCrow** [comment]
Добрый день!

Пожалуйста приведите пример использования, когда не получается отобразить ассет. 
Вероятно вы передаете неверное название ассета. Также возможно, что вы его не указали в pubspec.yaml.

arrowName - это название файла ассета, который будет отображаться для пользователя при его движении - стрелка направления движения)

**Comment by k0lourful** [comment]
> arrowName - это название файла ассета, который будет отображаться для пользователя при его движении - стрелка направления движения)

Ну вот теперь понятно почему нет иконки, потому что в движении используется arrowName! Не будете против, если я опишу параметры в доках в новом PR?

**Comment by DCrow** [comment]
Всегда не против поревьюить.
В документации нативных либ, к сожалению, ничего не написано. 
Судя по примеру для [iOS](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/Assets.xcassets/UserArrow.imageset/user_arrow.png), надо чтобы стрелка смотрела ровно вверх.

**Comment by Horum-dev** [comment]
> Всегда не против поревьюить.
> В документации нативных либ, к сожалению, ничего не написано.
> Судя по примеру для [iOS](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/Assets.xcassets/UserArrow.imageset/user_arrow.png), надо чтобы стрелка смотрела ровно вверх.

Добрый день! с arrowName на IOS всплывает такой баг:
`yandex::maps::mapkit::layers::createGroundLayerUpdater <warn>: Layer: indoor, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/indoor/tiles
yandex_mapkit/YandexMapController.swift:662: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

Карта просто вылетает. Вот строчка из свифт кода библиотеки
`UIImage(named: pluginRegistrar.lookupKey(forAsset: self.iconName))!`

Вызов метода как выше.

**Comment by DCrow** [comment]
@Horum-dev 

А вы добавили ассет в pubspec.yaml? В случае если ассета нет, то приложение действительно вылетает.
