### ISSUE TITLE
запуск под IOS - вылет

### ISSUE THREAD

**Issue by akhokhlushin** [Unact/yandex_mapkit#136]
Cобираю IOS версию, на странице с картой приложение рушится. Под Андроидом работает нормально

 *** Assertion failure in -[YMKMap moveWithCameraPosition:], /place/sandbox-data/build_cache/yabuild/build_root/943y/000588/maps/mobile/libs/mapkit/map/idl/impl/YandexMapsMobile/YMKMap_Binding.mm:336
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Position should be finite, provided position is target = (nan,nan), zoom = nan, azimuth = 0, tilt = 0'
*** First throw call stack:
(0x18583725c 0x1995cc480 0x185744c98 0x186a7cef8 0x101cb71a0 0x102b0b1fc 0x102afff98 0x102af9550 0x102af8940 0x102af8a04 0x10b60970c 0x10b0f312c 0x10b0f8da4 0x10b4e1790 0x10b3ed6bc 0x10b3f415c 0x1857b70a8 0x1857b6ca8 0x1857b617c 0x1857b04b4 0x1857af7d0 0x19bef1570 0x1880dc2d0 0x1880e184c 0x10099cc78 0x18548e140)
libc++abi: terminating with uncaught exception of type NSException
`

вот целиком код модуля, который крашится:

                 case 'point':
                              var _lat = "${(_detail[detailKey]['latitude'])}";
                              var _long =
                                  "${(_detail[detailKey]['longitude'])}";
                              var _point = Point(
                                  latitude: double.parse(_lat),
                                  longitude: double.tryParse(_long));
                              YandexMapController yandexMapController;
                              return SizedBox(
                                  height: 400,
                                  child: YandexMap(
                                      onMapCreated: (controller) async {
                                        yandexMapController = controller;
                                        yandexMapController.addPlacemark(
                                            Placemark(
                                              point: _point,
                                            ));
                                        yandexMapController.setBounds(
                                            southWestPoint: Point(
                                                latitude: 56.088926,
                                                longitude: 37.353775),
                                            northEastPoint: Point(
                                                latitude: 56.067810,
                                                longitude: 37.386388));

                                        if (await locationPermissionGranted) {
                                          await controller.showUserLayer(
                                              iconName: 'assets/imgs/place.png',
                                              arrowName: 'assets/imgs/user.png',
                                              accuracyCircleFillColor:
                                              Colors.green.withOpacity(0.1));
                                        }
                                      }));
`

**Comment by DCrow** [comment]
Добрый день

Подскажите, а точно значения в double.tryParse(_long) не null? Судя по ошибке именно на это и жалуется.

Судя по коду советовал бы обновится до null-safety версии, помогает избегать такого рода ошибок(`Point` не принимает null значения, a double.tryParse может их вернуть)

**Comment by akhokhlushin** [comment]
Спасибо, протестирую, отпишусь

**Comment by akhokhlushin** [comment]
не, не помогло. Захардкодил координаты, ничего не меняет ;(

yandex::maps::mapkit::layers::createGroundLayerUpdater <warn>: Layer: map, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/map/tiles
yandex::maps::mapkit::layers::createGroundLayerUpdater <warn>: Layer: sat, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/sat/tiles
yandex::maps::mapkit::layers::createGroundLayerUpdater <warn>: Layer: vskl2, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/vskl2/tiles
yandex::maps::mapkit::layers::createGroundLayerUpdater <warn>: Layer: vmap2, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/vmap2/tiles
flutter: before permission
*** Assertion failure in -[YMKMap moveWithCameraPosition:], /place/sandbox-data/build_cache/yabuild/build_root/943y/000588/maps/mobile/libs/mapkit/map/idl/impl/YandexMapsMobile/YMKMap_Binding.mm:336
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Position should be finite, provided position is target = (nan,nan), zoom = nan, azimuth = 0, tilt = 0'
*** First throw call stack:

**Comment by DCrow** [comment]
А, точно! Вспомнил, это проблема из-за того как флаттер инициализирует размеры https://github.com/flutter/flutter/issues/30272. 

Тут надо использовать `onMapRendered`, в `onMapCreated` размер карты еще нулевой, из-за этого нативная либа выдает ошибку.

**Comment by akhokhlushin** [comment]
А может подскажите тогда, как правильно этот кусок кода переписать? Контроллера  onMapCreated не возвращает, а как тогда спозиционировать?

**Comment by DCrow** [comment]
Должно получиться что-то вроде такого

```dart
var _lat = "${(_detail[detailKey]['latitude'])}";
var _long = "${(_detail[detailKey]['longitude'])}";
var _point = Point(latitude: double.parse(_lat), longitude: double.parse(_long));
YandexMapController yandexMapController;

return SizedBox(
  height: 400,
  child: YandexMap(
    onMapCreated: (controller) {
      yandexMapController = controller;
    },
    onMapRendered: () async {
      yandexMapController.addPlacemark(Placemark(point: _point));
      yandexMapController.setBounds(
        southWestPoint: Point(latitude: 56.088926, longitude: 37.353775),
        northEastPoint: Point(latitude: 56.067810, longitude: 37.386388)
      );

      if (await locationPermissionGranted) {
        await controller.showUserLayer(
          iconName: 'assets/imgs/place.png',
          arrowName: 'assets/imgs/user.png',
          accuracyCircleFillColor: Colors.green.withOpacity(0.1)
        );
      }
    }
  )
);
```

В `onMapCreated` получаем контроллер, и потом, когда карта отобразилась и вызвала `onMapRendered`, используем контроллер для работы с картой.

**Comment by akhokhlushin** [comment]
Спасибо, тестирую!

**Comment by akhokhlushin** [comment]
Супер, заработало!!! спасибо!

**Comment by gurgenbalayan** [comment]
@akhokhlushin Добрый день. Подскажите, пожалуйста, а откуда вы взяли onMapRendered в мап ките его нет.
