### ISSUE TITLE
проблема с работай карты на android API ниже 23

### ISSUE THREAD

**Issue by Mite0** [Unact/yandex_mapkit#138]
Использую карту на API 24 и выше и карта нормально работает. Протестировал на 24, 26,27,28,29,30 все хорошо.
Но на API 21 и 22 карты нет, никаких ошибок тоже не замечено.
Пример API 21
![image](https://user-images.githubusercontent.com/43238130/132833837-679325e4-99f8-4c12-88aa-d82fb0317da9.png)
Пример API 30
![image](https://user-images.githubusercontent.com/43238130/132834847-ee13e25a-2a29-4541-b623-6650d6356ef1.png)

**Comment by DCrow** [comment]
Добрый вечер!

Это ошибка отрисовки во flutter, вот тут она описывается flutter/flutter/issues/62496
К сожалению, тут остается только ждать когда flutter поправит багу.
