### ISSUE TITLE
как проверить вхождение точки в область?

### ISSUE THREAD

**Issue by FetFrumos** [Unact/yandex_mapkit#140]
Использую ваш плагин в моем приложении flutter.
Есть регион(область доставки) - массив точек с координатами(широта/долгота), нужно проверить входит ли произвольная точка(широта/долгота) в эту область. Поиском по исходникам подобных методов не нашел. Возможно можно использовать методы из нативного кода(android, ios). или есть методы апи для этого? нашел только [это](https://yandex.ru/dev/maps/archive/doc/jsapi/2.0/ref/reference/IPolygonGeometryAccess.html#method_detail__contains). но это для java script.в общем любые советы - буду благодарен.

**Comment by cream-cheeze** [comment]
Не знаю, есть ли такая возможность в Yandex Mapkit в принципе, но даже если есть, то плагин это не поддерживает, насколько мне известно. Посмотрите [эту библиотеку](https://pub.dev/packages/poly) - возможно, это то, что вы ищите.

**Comment by DCrow** [comment]
Добрый вечер!

Такого функционал в нативной либе нет https://github.com/yandex/mapkit-android-demo/issues/124#issuecomment-526662835
Также есть [такая](https://pub.dev/packages/maps_toolkit) библиотека для работы с точками и полигонами.
Только с ними надо помнить, что там не учитываются полигоны с дырками. 
Там придется отдельно проверять, что точка не находится в дырке.

**Comment by FetFrumos** [comment]
спасибо
