### ISSUE TITLE
getUserTargetPoint() возвращает null

### ISSUE THREAD

**Issue by LakshmyLucky** [Unact/yandex_mapkit#144]
Здравствуйте!
Делаю все по учебному примеру, вызываю showUserLayer, после чего хочу получить Point через getUserTargetPoint(). Возвращается null.
```
if (await locationPermissionGranted) {
     await controller!.showUserLayer(
          iconName: 'lib/assets/user.png',
          arrowName: 'lib/assets/arrow.png',
          accuracyCircleFillColor:
               Colors.red.withOpacity(0.5));
Point? point = await controller!.getUserTargetPoint(); //point = null
```
Что я неправильно делаю?

**Comment by DCrow** [comment]
Добрый день!

Бывают [ситуации](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKUserLocationLayer.html#-cameraPosition), когда карта не может рассчитать местоположение юзера. 
Какие это ситуации сам не могу сказать, про это только разработчики нативной библиотеки знают.

**Comment by LakshmyLucky** [comment]
Здравствуйте!
У меня самая стандартная задача - показать маркер местоположения пользователя и на него отцентровать карту, ну и зум небольшой. [Вот здесь](https://github.com/Unact/yandex_mapkit/issues/104) написано как, но как я могу рассчитать центр экрана для функции move, если я не могу получить координаты маркера?

**Comment by DCrow** [comment]
В случае если `YandexMapController.getUserTargetPoint` не отдает точку, остается только сторонними библиотеками вроде [location](https://pub.dev/packages/location) получать координаты пользователя и создавать `Point` с полученными координатами, который уже передать в  `YandexMapController.move`

**Comment by LakshmyLucky** [comment]
Спасибо большое! Будем пробовать.

**Comment by LakshmyLucky** [comment]
Огромное спасибо! Все прекрасно заработало!
