### ISSUE TITLE
После выполнения метода "move" метод "getVisibleRegion" всегда возвращает одинаковые координаты

### ISSUE THREAD

**Issue by MushrooM1337** [Unact/yandex_mapkit#148]
Здравствуйте. 
Мне нужно получить видимый регион после перемещения камеры, но он всегда (после перемещения) возвращает координаты точки, координаты которой были переданы в метод "move", т.е. все 4 точки одинаковые. Для получения новых координат я использую метод "enableCameraTracking". Причем перед перемещением метод "getVisibleRegion" возвращает правильные координаты.

`
var region = await controller!.getVisibleRegion();

 _locationData = await location.getLocation();

controller!.enableCameraTracking(
    onCameraPositionChange: (e) async {
    var r = await controller!.getVisibleRegion();
});

await controller!.move(
  point: Point(
  latitude: _locationData.latitude!,
  longitude: _locationData
  .longitude!)); //controller!.zoomIn();
                    `

Подскажите пожалуйста как мне решить данную проблему.

**Comment by DCrow** [comment]
Добрый день!

Не вижу, чтобы в вашем примере результат `getVisibleRegion` как либо использовался. 
В самом методе на данный момент не вижу проблем в возвращении результата.

Вижу только что вы перед использованием `move`, не вызываете заново метод `getLocation()`(из плагина location) для получения новых координат пользователя.

**Comment by MushrooM1337** [comment]
Перед вызовом метода move я как бы подписываюсь на событие onCameraPositionChange. Метод getVisibleRegion вызывается как раз после вызова метода move.  Ну и это не так важно. Даже если я просто вызову метод getVisibleRegion после move, то вернется тот же результат (просто думал
, что так правильней). 
Мне нужно после move получить координаты региона видимости (4 разных точки), но вместо этого мне возвращается центр окна.

**Comment by DCrow** [comment]
Насколько я вас понял, у вас проблема в том, что если сразу после `move` вызвать `getVisibleRegion` координаты совпадают?

Если так, то это не совсем корректно, если сразу вызвать, то `move` только начинает двигать камеру, и поэтому, действительно, `getVisibleRegion` может вернуть те же значения, что и до move. 

Надо дожидаться когда закончится движение камеры, после чего можно получить новый регион.
```dart 
controller!.enableCameraTracking(
  onCameraPositionChange: (dynamic res) async {
    if (res['final']) {
      var region = await controller!.getVisibleRegion();
    }
  }
);
```

**Comment by MushrooM1337** [comment]
Извините, если я не так выразился или чего-то не понимаю, но вот посмотрите координаты перед перемещением камеры:

**TopLeft: Point(84.83704074687031, 20.491071428571473), BottomRight: Point(-49.897847063947154, 159.5089285714285)**

и координаты после перемещения:

**TopLeft: Point(37.43341960793751, -122.09248497663225), BottomRight: Point(37.410575234250736, -122.07551502336776)**

После перемещения координаты левого верхнего угла равны координатам правого нижнего угла. И это означает, что после перемещения метод getVisibleRegion возвращает одинаковые координаты одной точки, а не прямоугольную область.

**Comment by DCrow** [comment]
Координаты совсем не равны, 37.43341960793751 != 37.410575234250736 и -122.09248497663225 != -122.07551502336776

В реальном мире между этими двумя точками разница почти 3км.

**Comment by MushrooM1337** [comment]
Понял. 
Спасибо большое!!!
Прошу прощения за мою дикую невнимательность
