### ISSUE TITLE
failed to get last known location

### ISSUE THREAD

**Issue by Denmal1982** [Unact/yandex_mapkit#15]
Здравствуйте! При запуске экрана с картой, получаю в логах данную ошибку.

`E/com.yandex.runtime.sensors.internal.LastKnownLocation( 9122): failed to get last known location: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.`

В манифесте:
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

**Comment by DCrow** [comment]
Здравствуйте! Подскажите, вы запускали на эмуляторе или реальном устройстве? В разрешениях, дали ли права на получение координат?

**Comment by Denmal1982** [comment]
> Здравствуйте! Подскажите, вы запускали на эмуляторе или реальном устройстве? В разрешениях, дали ли права на получение координат?

Я запускаю на реальном устройстве, установка через кабель. Разрешение в манифесте, но при запуске разрешение приложение не спрашивает.
Но карта работает

**Comment by DCrow** [comment]
Да, в примере, приложение не запрашивает, так как это демонстрация возможностей библиотеки. В симуляторах права по умолчанию всегда даны, поэтому не было необходимости такой момент дорабатывать. Если вручную дать права(через найстройки в телефоне), ошибка должна пропасть.

**Comment by Ishokov-Dzhafar** [comment]
> > Здравствуйте! Подскажите, вы запускали на эмуляторе или реальном устройстве? В разрешениях, дали ли права на получение координат?
> 
> Я запускаю на реальном устройстве, установка через кабель. Разрешение в манифесте, но при запуске разрешение приложение не спрашивает.
> Но карта работает
Запросите предварительно права, и после разрешение прав, только тогда показывайте карту. У себя в приложении, я так и поступаю.

**Comment by Ishokov-Dzhafar** [comment]
> > Здравствуйте! Подскажите, вы запускали на эмуляторе или реальном устройстве? В разрешениях, дали ли права на получение координат?
> 
> Я запускаю на реальном устройстве, установка через кабель. Разрешение в манифесте, но при запуске разрешение приложение не спрашивает.
> Но карта работает

Запросите предварительно права, и после разрешение прав, только тогда показывайте карту. У себя в приложении, я так и поступаю.

**Comment by DCrow** [comment]
Проблема еще актуальна?

**Comment by vanyasem** [comment]
@DCrow в симуляторах права не даны по-умолчанию, их так же надо запрашивать. создал #22
