### ISSUE TITLE
Не отображается логотип Яндекса в релизной версии приложения.

### ISSUE THREAD

**Issue by alexanderkind** [Unact/yandex_mapkit#154]

**Comment by FeofanGreek** [comment]
Не поправили или не охота? :-)

**Comment by DCrow** [comment]
@FeofanGreek Последнее обновление нативной либы было 21.09.20, после этого яндекс не выпускал обновлений нативной либы, следовательно и бага не могла быть исправлена.

**Comment by iska9der** [comment]
Можно ведь самому наложить поверх карты это лого, и пускать в таком виде в релиз?

**Comment by DCrow** [comment]
Верно, так в нативной либе и советуют.
