### ISSUE TITLE
Invalid value: Not in inclusive range

### ISSUE THREAD

**Issue by borissius** [Unact/yandex_mapkit#158]
Здравствуйте! Есть проблема следующего плана:
С бэка приходит список координат, которые я кладу в List Placemark, длина списка свыше 250. Далее в цикле добавляю плэйсмарки методом addPlacemark. В итоге получаю ошибку RangeError (index): Invalid value: Not in inclusive range 0..100: 101. Подскажите пожалуйста с чем связана данная проблема, не понимаю куда думать? С начальным значением зума? На карте в итоге при начальном зуме в 10 всегда отображается 11 плэйсмарков из >250. Буду признателен за помощь!
Скрин кода: https://skr.sh/sAn2E5ubapH
Скрин логов: https://skr.sh/sAn1pdejJ2I
Скрин UI: https://skr.sh/sAn7AtnOYhV

**Comment by DCrow** [comment]
Здравствуйте!

Так у вас же цикл не правильно написан. 
Вы итерируете по 101 элементу, начинаете с 0 включительно и до 100 включительно.
Вам надо до 100 не включительно итерировать.

Вот так
```dart
final list = List.filled(100, (i) => i);

for (var i = 0; i < list.length; i++) {
}
```

**Comment by borissius** [comment]
Мда? Это я чайник получается. Блин. Извините. Спасибо большое!)))
