### ISSUE TITLE
При тапе на placemark колбэк срабатывает несколько раз

### ISSUE THREAD

**Issue by Klucherev** [Unact/yandex_mapkit#159]
Добрый день, спасибо за библиотеку!
При тапе на плейсмарк срабатывает коллбэк у всех плейсмарков, которые рядом и под ним, то есть если сделать минимальный зум и тапнуть на куче, то получим 100500 колбэков

**Comment by cream-cheeze** [comment]
В onMapObjectTap в листенере надо true возвращать - значит, что эвент обработан. Сейчас возвращается всегда false, поэтому срабатывает дальше. Я это кстати исправлял в прошлых ревью, но оно вернулось.

**Comment by Klucherev** [comment]
@cream-cheeze в placemark.onTap?

**Comment by cream-cheeze** [comment]
> @cream-cheeze в placemark.onTap?

Не-не, сейчас это в плагине зашито. Нужно либо внутри поменять безусловно - тогда всегда будет срабатывать только один тап на первом попавшемся объекте, либо дать возможность управлять этим в пользовательском placemark.onTap колбэке.

**Comment by Klucherev** [comment]
@cream-cheeze Спасибо за наводку, а то я замучался колбэки эти обрабатывать в асинхроне

**Comment by DCrow** [comment]
> Не-не, сейчас это в плагине зашито. Нужно либо внутри поменять безусловно - тогда всегда будет срабатывать только один тап на первом попавшемся объекте, либо дать возможность управлять этим в пользовательском placemark.onTap колбэке.

Таким образом в коллекции колбэк не срабатывает. 
В onTap нельзя это обработать, так как надо результат давать синхронно, а onTap вызывается асинхронно.
Это уже ограничение флаттера, в нем нет синхронных вызовов в dart и наобарот.

Отдельно доделаю, чтобы можно было настраивать что отдавать true/false для того или иного объекта. 
По аналогии с [consumeTapEvents](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart#L176) в google_maps_flutter

**Comment by DCrow** [comment]
В мастере добавил consumeTapEvents, теперь можно управлять какие объекты должны поглощать tap и не давать ему вызываться на других объектах.
