### ISSUE TITLE
YMK перестал работать((

### ISSUE THREAD

**Issue by ambogatyrev** [Unact/yandex_mapkit#161]
Лог:
![image](https://user-images.githubusercontent.com/79789858/140409488-0c1f2ee5-1e4c-459b-93fb-c650a50bf4e0.png)

Подскажите пожалуйста в чем причина?

**Comment by DCrow** [comment]
Здравствуйте!

Не могли бы поточнее объяснить проблему, и по возможности приложить пример.

**Comment by DCrow** [comment]
Закрываю, так как нет ответа на предыдущий вопрос.
