### ISSUE TITLE
Ошибка с установкой цвета круга точности на iOS

### ISSUE THREAD

**Issue by AdmiralPavel** [Unact/yandex_mapkit#162]
На некоторых устройствах вылетает ошибка при попытке установить цвет круга точности на iOS в методе onObjectAdded:
view.accuracyCircle.fillColor = accuracyCircleFillColor
Вылетает следующая ошибка:
Crashed: com.apple.main-thread
EXC_BREAKPOINT 0x0000000102b1a018
Насколько я понимаю (не силён в свифте), проблема с тем, что цвет оказывается ещё не инициализирован (в объявлении он помечен как private let accuracyCircleFillColor: UIColor!). В аналогичном коде на андроиде ему устанавливается значение по умолчанию равное 0.

**Comment by DCrow** [comment]
Здравствуйте!

Просьба приложить пример, с котором можно воспроизвести эту ошибку.

**Comment by AdmiralPavel** [comment]
Боюсь, что с этим будет сложно -- ошибку получилось поймать только через crashlytics у пользователей, сам я её не получал, так что не знаю, какие вводные нужны для её получения. А рабочий код из-за NDA выложить не могу. Вероятно, ошибка должна воспроизводиться и на приложении-примере: насколько я помню, там есть получение позиции пользователя.

**Comment by DCrow** [comment]
Тогда особо помочь не могу.

`accuracyCircleFillColor` инициализируется до того как вызывается `onObjectAdded`.
Нужен тогда конкретный пример, без него не понять в чем проблема.

**Comment by DCrow** [comment]
Доработал в мастере, теперь можно полноценно редактировать вид pin, arrow и accuracyCircle.
Думаю теперь проблемы не должно быть
