### ISSUE TITLE
 координаты у SuggestItem

### ISSUE THREAD

**Issue by DmitriyIgnashchenko** [Unact/yandex_mapkit#164]
День добрый, при поиске адреса возможно ли получить его координаты? спасибо

**Comment by cream-cheeze** [comment]
Чтобы получить координаты адреса используйте YandexSearch. В YandexSuggest можно получить только строковые подсказки. 

Логика такая:

1. С помощью YandexSuggest получили отформатированный адрес.
2. Передали строку в YandexSearch и получили координаты и другие атрибуты искомого адреса.

**Comment by DmitriyIgnashchenko** [comment]
Спасибо большое!
