### ISSUE TITLE
Как достать гео-координаты?

### ISSUE THREAD

**Issue by Jihadik** [Unact/yandex_mapkit#165]
Есть ли возможность в целом из мап кита при саджесте достать координаты адреса?

**Comment by DCrow** [comment]
Добрый вечер!

Сам YandexSuggest не возвращает координаты. 
Но можно сделать как тут рассказано https://github.com/Unact/yandex_mapkit/issues/164#issuecomment-963081284

**Comment by Jihadik** [comment]
@DCrow, невероятная благодарность!
