### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by asadbekdev** [Unact/yandex_mapkit#166]
I am using 1.1.1 version of yandex_mapkit, but examples on github doesn't work?

**Comment by asadbekdev** [comment]
If you make a difference on package, pls write docs

**Comment by DCrow** [comment]
Hello!

Currently master contains unreleased features. Version will be changed after those changes are published to pub.dev

**Comment by asadbekdev** [comment]
Which version of package and example can i use?

**Comment by asadbekdev** [comment]
Which example codes can i use ?

**Comment by DCrow** [comment]
Both master and pub.dev are valid version.
You can use whichever you like.

master has more implemented feature but they are subject to change. 
pub.dev is stable and won't be changed
