### ISSUE TITLE
Перестала работать карта

### ISSUE THREAD

**Issue by LakshmyLucky** [Unact/yandex_mapkit#169]
Здравствуйте! Вчера все работало, сегодня карта загружается, но не работает. Не только у меня, но и у коллеги. В чем может быть проблема?

Вот что пишется в логе:

![image](https://user-images.githubusercontent.com/91207057/142376235-03e8a022-6259-4a63-b1e7-ea0341fce02f.png)
![image](https://user-images.githubusercontent.com/91207057/142376327-010e0634-0f49-4dbd-bc1f-54ad0c04deca.png)

**Comment by DCrow** [comment]
Добрый день!

Судя по вашим логам, вы не передаете корректное название ассета картинки.
Можете приложить пример кода, который выполняете?

**Comment by LakshmyLucky** [comment]
Папка flutter_assets - это не наша папка, ошибка "Can't load image from asset: flutter_assets/" была всегда и на работу приложения не влияла. Вчера никакие картинки ни у меня, ни у коллеги не менялись. А так же, если я не ошибаюсь, сообщение "AndroidBitmap_getInfo() failed! Error code: -1" тоже всегда отображалось, но тоже не влияло на работу приложения.

**Comment by LakshmyLucky** [comment]
Ошибка нашлась. У коллеги проект стоял на точке останова, и я так же не могла получить доступ к карте. Прошу прощения за такую оплошность, сами виноваты :)
