### ISSUE TITLE
'<yandex_mapkit/yandex_mapkit-Swift.h>' file not found

### ISSUE THREAD

**Issue by Denmal1982** [Unact/yandex_mapkit#17]
Здравствуйте!
В XCode, при сборке  вызывается ошибка.

`yandex_mapkit-0.3.0/ios/Classes/YandexMapkitPlugin.m:2:9: fatal error: '<yandex_mapkit/yandex_mapkit-Swift.h>' file not found`

**Comment by DCrow** [comment]
Здравствуйте! Подскажите, как выглядит ваш Podfile, есть ли строки, помеченные комментарием "добавить"?

```ruby
target 'Runner' do
  use_frameworks! # <--- добавить
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0' # <--- добавить
    end
  end
end
```

**Comment by Denmal1982** [comment]
Добавил в код `config.build_settings['SWIFT_VERSION'] = '4.0'`, но ошибка не исчезла


# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end



# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end

**Comment by DCrow** [comment]
К сожалению, это общая проблема для плагинов флаттера написанных на swift...
Вы смотрели решения в https://github.com/flutter/flutter/issues/16049 ?

**Comment by Denmal1982** [comment]
спасибо, тогда пошаманим)

**Comment by DCrow** [comment]
Проблема еще актуальна?

**Comment by DCrow** [comment]
Закрываю, так как проблема не является проблемой плагина, а является общей проблемой для плагинов флаттера написанных на swift
