### ISSUE TITLE
question

### ISSUE THREAD

**Issue by asadbekdev** [Unact/yandex_mapkit#171]
When new version will be available, i need new versions future, i need marker like a yandex taxi app ?

**Comment by DCrow** [comment]
Hello!

If you mean when a current changes will be published to pub.dev, then for now it is undetermined. 
Maybe by the end of the year. 

All examples that are compatible with pub.dev version can be seen [here](https://github.com/Unact/yandex_mapkit/tree/581f4900496d284b7fc1df53420971254ee1e7d5/example)
