### ISSUE TITLE
как использовать YandexDriving.requestRoutes "без учета пробок"?

### ISSUE THREAD

**Issue by FetFrumos** [Unact/yandex_mapkit#172]
Добрый день, использую YandexDriving.requestRoutes в приложении Flutter. Результат возвращает несколько маршрутов, мне нужно получить один "оптимальный"  маршрут. Похожая опция есть для поиска в браузере - строит один маршрут. Поиск в сети дал вариант искать "без учета пробок". Поддерживает ли плагин такую возможность? или может посоветуете другой подход?

**Comment by DCrow** [comment]
Добрый день!

К сожалению в отличии от [JS Api](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/route.html#route__param-params.avoidTrafficJams), iOS/Android не имеет такой опции(Все доступные [опции](https://yandex.com/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKDrivingDrivingOptions.html?lang=ru))

Единственное, что нативные либы предоставляют это данные о [пробках](https://yandex.com/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKDrivingRoute.html#property_detail__property_jamSegments) в маршруте. 
Может быть с их помощью удастся определить маршрут, с наименьшим кол-вом пробок.

PS В плагине для флаттера эти данные на данный момент не возвращаются.

**Comment by FetFrumos** [comment]
Добрый вечер, спасибо за ваш ответ. Искал решение - пока не нашел. Немного изменю сам вопрос. На сайте есть поиск, посмотрел исходники js, в метод route передается две точки - в результате один маршрут, доп. параметров нет. Еще перед этим рисуются две области методом Polyline. В приложении - в результате получаю несколько( например три) маршрутов, мне нужно выбрать один и что бы он совпадал с тем что на сайте(построенный через API JS). Но как определить не понятно. может что то посоветуете?

**Comment by DCrow** [comment]
Тут не могу подсказать. Насколько я понимаю, постройка маршрутов сильно зависит от времени. 
Даже в примере проекта, бывает что получаю 3 варианта, а бывает что получаю 1 вариант маршрута.
