### ISSUE TITLE
Карта исчезает при появлении клавиатуры на Android

### ISSUE THREAD

**Issue by starikovvm** [Unact/yandex_mapkit#173]
При поднятии/опускании системной клавиатуры не всегда, но часто, карта пропадает с экрана, при этом в логе вылезает `dequeueBuffer: BufferQueue has no connected producer`

Повторяется с добавлением TextView на экран с картой, либо даже на другой экран, пока карта находится под ним.

Версия библиотеки из master, проверяется так:
```
return Scaffold(
  body: Stack(
    children: [
      YandexMap(),
      Center(child: TextField()),
    ],
  ),
);
```
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-arm, locale ru-RU)
    • Flutter version 2.8.0 at /Users/viktorstarikov/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (17 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/viktorstarikov/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • POT LX1 (mobile)            • WQD4C18C11007498                     • android-arm64 • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 12 (API 31) (emulator)
    • iPhone XR Viktor (mobile)   • 00008020-001C68AA14D2002E            • ios           • iOS 15.1 19B74
    • iPhone 13 Pro Max (mobile)  • A6B73A93-FF39-4EEB-A63F-50FE4A8072F3 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    ! Error: iPhone XR Viktor is busy: Making the device ready for development. Xcode will continue when iPhone XR Viktor is finished. (code -10)

! Doctor found issues in 1 category.
```

</details>

**Comment by DCrow** [comment]
Добрый день!

Подскажите что вы подразумеваете под "пропадает с экрана"? 
Совсем не отображается, или же мерцает(пропадает на секунду две и заново отображается).

Пробовал ваш пример, заметил только мерцание карты.

**Comment by starikovvm** [comment]
У меня с экрана исчезает совсем, становится прозрачной. Снова появляется только рандомно при очередном поднятии/опускании клавиатуры.

**Comment by DCrow** [comment]
К сожалению у меня не получается воспроизвести. 
Может быть дело в каких-то определенных устройствах? 
На каких андроид устройствах у вас получалось воспроизвести?

Также сделал ветку `android_surface`, возможно изменения в ней решат вашу проблему.
Если возможно проверьте, воспроизводится ли ваша ошибка в той ветке. 
Только предварительно надо в методе main в пример добавить
```dart
AndroidYandexMap.useAndroidViewSurface = true;
```
Эта опция меняет, каким образом отрисовывается виджет на андроиде.

**Comment by starikovvm** [comment]
С `useAndroidViewSurface = true` по моим тестам исправилось, спасибо. Стала меньше тормозить анимация показа клавиатуры и перестала карта исчезать. Заметил еще кстати, что появлялся еще странный баг с отзеркаливанием карты по вертикали со старой отрисовкой.

Повторялось причем на android 10 на девайсе и 12 на симуляторе, с версией флаттера 2.8. На Flutter 2.5.3 повторить не удалось, может быть с этим связано.

**Comment by DCrow** [comment]
Хорошо что помогло. В ближайшее время в мастер добавлю.

Мне больше кажется что это плавающая ошибка, я на 2.8 пробовал только мерцание видел. 
Либо флаттер для arm архитектуры, как-то особенно в отличии от x64 собирает.

В любом случае тут ошибка в движке флаттера(похожая https://github.com/flutter/flutter/issues/72706), хорошо что решается переходом на новую отрисовку.

**Comment by DCrow** [comment]
В мастере добавил.

По умолчанию `useAndroidViewSurface = true`, поэтому https://github.com/Unact/yandex_mapkit/issues/173#issuecomment-992451590 можно не выполнять.

**Comment by kirya355** [comment]
> Хорошо что помогло. В ближайшее время в мастер добавлю.
> 
> Мне больше кажется что это плавающая ошибка, я на 2.8 пробовал только мерцание видел. Либо флаттер для arm архитектуры, как-то особенно в отличии от x64 собирает.
> 
> В любом случае тут ошибка в движке флаттера(похожая [flutter/flutter#72706](https://github.com/flutter/flutter/issues/72706)), хорошо что решается переходом на новую отрисовку.

Проблема с мерцанием решается переходом на новую отрисовку?
