### ISSUE TITLE
Сделать возможность передвинуть камеру на несколько точек

### ISSUE THREAD

**Issue by punzar** [Unact/yandex_mapkit#176]
Большое спасибо за вашу библиотеку!
Не хватает легко способа передвинуть камеру на Polyline или Polygone, так чтоб все нужные объекты вписывались в CameraPosition

**Comment by DCrow** [comment]
Добрый день!

Вот тут описано как можно безболезненно это сделать https://github.com/Unact/yandex_mapkit/issues/163

Или вы хотите чтобы в либе были методы, которые бы позволяли строить BoundingBox из Polyline/Polygon?

**Comment by punzar** [comment]
Спасибо за столь быстрый и полезный ответ! Этого мне хватит
