### ISSUE TITLE
View карты просачивается поверх всех элементов

### ISSUE THREAD

**Issue by just-kip** [Unact/yandex_mapkit#178]
Привет! В первую очередь спасибо на плагин, благодаря ему было сэкономлено куча времени.

После включения Hybrid composition наблюдаю такой баг:
![bug](https://user-images.githubusercontent.com/4008338/147660529-78be5fad-0765-4836-8123-8a06a65fd74c.gif)

Легко воспроизвести если просто добавить табы на главный экран example, вот пример https://github.com/just-kip/yandex_mapkit/blob/nav_bar_bug/example/lib/main.dart На эмуляторе, девайсаx, с --release.

С AndroidYandexMap.useAndroidViewSurface = false Все ОК, но повторяются https://github.com/Unact/yandex_mapkit/issues/173 https://github.com/Unact/yandex_mapkit/issues/126

Ситуация очень похожа на древний баг android с аппаратной отрисовкой GLSurfaceView, когда последний фрейм буфера всегда остается на экране, но врятли это этот случай.

Буду признателен за любые наводки, в какую сторону копать.

**Comment by just-kip** [comment]
Кажется проблема заключалась в https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/android/mapkit/ref/com/yandex/mapkit/mapview/MapView.html

ссылка на тикет из MapKit https://github.com/yandex/mapkit-android-demo/issues/109

вот код, который фиксит https://github.com/just-kip/yandex_mapkit/pull/1/files

Не уверен что это нужно хардкодить, может быть сделать возможность изменения этого параметра в плагине?

**Comment by DCrow** [comment]
Доброе утро! 

По типу ошибки это больше похоже на багу https://github.com/flutter/flutter/issues/82105
(там кстати грешат на GLSurfaceView, который и используется тут по дефолту нативной либой)
То есть тут проблема самого флаттера, что он не верно работает с нативной вьюхой.

Хорошо что удалось другим способом обойти эту проблему.
Пока можно его использовать, но после того как поправят баг во флаттере надо будет откатить это изменение.
Тут бы я использовал movable всегда, когда используется AndroidYandexMap.useAndroidViewSurface = true, так как бага только на ней. Иначе другие пользователи также будут натыкаться на багу и думать что делать... 
Да и вообще странно иметь багу и фикс, который надо руками включать...

**Comment by kirya355** [comment]
Мерцание не удалось убрать при переключении между BottomNavigationItem?
