### ISSUE TITLE
YandexMapController.getVisibleRegion возвращает неверные значения на iOS

### ISSUE THREAD

**Issue by petrobik** [Unact/yandex_mapkit#183]
Здравствуйте!

Обнаружил, что при использовании YandexMapController.getVisibleRegion на iOS для точки "topRight" возвращаются координаты точки "bottomLeft".

Просмотрев исходники плагина для iOS я обнаружил ошибку в файле Utils.swift в функции visibleRegionToJson (стр. 193):

`"topRight": pointToJson(region.bottomLeft)`

**Comment by DCrow** [comment]
Здравствуйте!

Действительно ошибка, поправлю в ближайшее время

**Comment by DCrow** [comment]
Поправил в мастере и в 2.0.1
