### ISSUE TITLE
Вариант реализации и размер финальной сборки

### ISSUE THREAD

**Issue by iska9der** [Unact/yandex_mapkit#186]
Добрый день! Спасибо за библиотеку.

Вопрос вот в чем: 
возможно ли вместо full версии в зависимость поставить lite 
`implementation "com.yandex.android:maps.mobile:4.0.0-lite"`?

С полной версией размер приложения [apk not split] с ~25мб увеличивается до ~77мб, что слишком много.
Сейчас при запуске приложения с lite-зависимостью вылетает следующий трейс:

`
E/AndroidRuntime(13290): FATAL EXCEPTION: main
E/AndroidRuntime(13290): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yandex/mapkit/search/SearchFactory;
E/AndroidRuntime(13290): 	at com.unact.yandexmapkit.YandexSearch.<init>(YandexSearch.java:28)
E/AndroidRuntime(13290): 	at com.unact.yandexmapkit.YandexMapkitPlugin.setupChannels(YandexMapkitPlugin.java:46)
E/AndroidRuntime(13290): 	at com.unact.yandexmapkit.YandexMapkitPlugin.onAttachedToEngine(YandexMapkitPlugin.java:36)
E/AndroidRuntime(13290): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:145)
E/AndroidRuntime(13290): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:59)
E/AndroidRuntime(13290): 	at com.lightpay.optomarket.MainActivity.configureFlutterEngine(MainActivity.kt:11)
E/AndroidRuntime(13290): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:191)
E/AndroidRuntime(13290): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/AndroidRuntime(13290): 	at android.app.Activity.performCreate(Activity.java:7994)
E/AndroidRuntime(13290): 	at android.app.Activity.performCreate(Activity.java:7978)
E/AndroidRuntime(13290): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(13290): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(13290): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(13290): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(13290): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13290): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13290): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(13290): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13290): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(13290): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(13290): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13290): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(13290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(13290): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yandex.mapkit.search.SearchFactory" on path: DexPathList[[zip file "/data/app/~~Fi1SvmwER0-RNbmygfZzMA==/com.**.**.local-rQt2jlhzGgvt-dMuGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Fi1SvmwER0-RNbmygfZzMA==/com.**.**.local-rQt2jlhzGgvt-dMuGA==/lib/x86, /data/app/~~Fi1SvR0-RNgfZzMA==/com.**.**.local-rQt2jlhzGg4rZvt-dMu9GA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(13290): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(13290): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(13290): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(13290): 	... 23 more
`

**Comment by DCrow** [comment]
Добрый день!

Библиотека поддерживает только full версию. 
lite версия не совместима, так как в проекте используются разные методы, классы из full варианта.
