### ISSUE TITLE
getScreenPoint

### ISSUE THREAD

**Issue by Hellomik2002** [Unact/yandex_mapkit#188]
Новая фича работает не полноценно
На сколько я понял что нужно еще добавить информацию о размрее карты потому что размеры немного не сопвадают или что то такое

**Comment by Hellomik2002** [comment]
https://github.com/Hellomik2002/yandex_mapkit/blob/master/ios/Classes/YandexMapController.swift
Вот я делал такую вещь

**Comment by Hellomik2002** [comment]
Можете просто добавить MapSize

**Comment by Hellomik2002** [comment]
Если додите мне одобрение сам добавлю просто сам юзаю или скажите что можешь сам сделать и добавите если все ок
И еще потом сам реализую и оптимизирую

**Comment by DCrow** [comment]
Доброе утро!

Для получения размера виджета надо пользоваться функциями предоставляемые флаттером.
В вашем случае это выглядит примерно так
```dart
class ExamplePage extends StatefulWidget {
  @override
  _ExamplePageState createState() => _ExamplePageState();
}

class _ExamplePageState extends State<ExamplePage> {
  late YandexMapController controller;
  final GlobalKey _mapKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Expanded(child: YandexMap(key: _mapKey)),
        const SizedBox(height: 20),
        ElevatedButton(
          onPressed: () => print(_mapKey.currentContext?.size),
          child: Text('Get map size', textAlign: TextAlign.center),
        )
      ]
    );
  }
}
```

**Comment by Hellomik2002** [comment]
Не работает ибо рамер берется относительно четсно я фиг его как так вышло

**Comment by Hellomik2002** [comment]
<img width="888" alt="Screen Shot 2022-02-05 at 02 47 44" src="https://user-images.githubusercontent.com/30003495/152600919-85004265-c907-4f67-8718-43722f8a67a6.png">

**Comment by Hellomik2002** [comment]
Просто попробуй взять высоту у самой карты и самого виджета они разные, почему я хз

**Comment by Hellomik2002** [comment]
Крч братан размер dp и px разные просто добавь MediaQuery.of(context).devicePixelRatio к умножению size и код робит оказываетя
