### ISSUE TITLE
А есть параметр чтоб лого Яндекса принудительно убирать?

### ISSUE THREAD

**Issue by FeofanGreek** [Unact/yandex_mapkit#189]
Хотелось бы управлять не только размещением, но и отображением, или хотя бы вариантами оного

**Comment by DCrow** [comment]
Добрый день!

Логотип нельзя убирать. См [условия использования](https://yandex.ru/dev/maps/mapkit/doc/intro/concepts/conditions.html)

**Comment by FeofanGreek** [comment]
Вас понял!
