### ISSUE TITLE
Есть ли возможность выделять на карте регион?

### ISSUE THREAD

**Issue by FeofanGreek** [Unact/yandex_mapkit#190]
Как выделять регион и как задавать вариант отображения карты (со спутника и тд) ![Снимок экрана 2022-02-04 в 11 43 47](https://user-images.githubusercontent.com/57085995/152507279-801b0d13-20db-4aef-84dd-be27116698ff.png)

**Comment by DCrow** [comment]
Добрый день!

Гибрид, спутник и тп в мобильной версии не доступны См https://github.com/yandex/mapkit-android-demo/issues/26#issuecomment-421943642
Выделение региона на данный момент в этой библиотеке не реализовано.

**Comment by FeofanGreek** [comment]
Благодарю за ответ
