### ISSUE TITLE
Есть функция worldToScreen которая работает в яндекс карте, так вот как взять формулу и использовать ее только в рамках FLutter

### ISSUE THREAD

**Issue by Hellomik2002** [Unact/yandex_mapkit#191]
Возможно вопрос не к вам
Просто делать method channel и расчитывать через Java или Swift делая асинхронные запросы, работает долго и менять кординаты после ...
и в любом случае просиходит Delay который можно почуствовать если у тебя более 50 обьектов в этом и проблема
Если какая та возможность найти формулу и сделать так что бы она была зависимо только он onCameraPositionChanged
Ибо использовать функцию которую нам дайет яндекс в наших реалях слишком долго для Flutter

**Comment by DCrow** [comment]
Доброе утро!

Во флаттер вызов кода из dart на Swift/Java всегда асинхронный, синхронным его сделать нельзя.
