### ISSUE TITLE
Вылетает приложение на ios

### ISSUE THREAD

**Issue by andrey-tru** [Unact/yandex_mapkit#193]
Добрый день! Столкнулся с проблемой при добавлении точек на карту, приложение вылетает на симуляторе ios на macbook pro i9, на android все работает нормально

**Comment by DCrow** [comment]
Добрый день!

При каком действие вылетает приложение? Воспроизводится ли ошибка в приложении примере?
Просьба приложить пример.

**Comment by DCrow** [comment]
Странно...

Просьба тогда еще и `flutter doctor --verbose` приложить.

**Comment by andrey-tru** [comment]
<img width="1286" alt="Снимок экрана 2022-02-17 в 16 10 58" src="https://user-images.githubusercontent.com/30568997/154488592-98a9fb77-66f2-4d72-88dc-73b946252e3e.png">

**Comment by DCrow** [comment]
Все равно не удается воспроизвести ошибку. 

Какой текст ошибки в логе возникает?

**Comment by andrey-tru** [comment]
<img width="1381" alt="Снимок экрана 2022-02-18 в 15 14 19" src="https://user-images.githubusercontent.com/30568997/154681121-aa09730c-e58e-4077-b678-4a53624760ca.png">

**Comment by DCrow** [comment]
Судя по этой ошибке, там где вы используете пример и добавляете `Placemark`, вы не указали в `pubspec.yaml`
ассет используемый точкой. 
Вот [тут](https://docs.flutter.dev/development/ui/assets-and-images) по-точнее написано что надо сделать.

**Comment by andrey-tru** [comment]
Да и правда, забыл, только у меня вот другую ошибку выдало, в чем может быть причина?
<img width="1410" alt="Снимок экрана 2022-02-18 в 15 35 57" src="https://user-images.githubusercontent.com/30568997/154684030-407d01e2-036c-45bb-9481-2776d2641e35.png">

**Comment by DCrow** [comment]
Тут уже нужен явный пример, ошибка слишком общая. 
Точно сказать из-за чего происходит не могу.

**Comment by andrey-tru** [comment]
Вот мои файлы с картой, подскажите, пожалуйста, что может вызывать эту ошибку?
[delivery_points_state.txt](https://github.com/Unact/yandex_mapkit/files/8097352/delivery_points_state.txt)
[delivery_points_cubit.txt](https://github.com/Unact/yandex_mapkit/files/8097353/delivery_points_cubit.txt)
[delivery_points.txt](https://github.com/Unact/yandex_mapkit/files/8097354/delivery_points.txt)

**Comment by andrey-tru** [comment]
При этом на android все работает прекрасно

**Comment by DCrow** [comment]
Судя по коду, ошибка в `_buildClusterAppearance`. `TextPainter` требует чтобы `textDirection` был задан. 
Возможно там еще есть ошибки, эта первая, которая попалась на глаза.

**Comment by andrey-tru** [comment]
проблема была в этом, спасибо большое!
