### ISSUE TITLE
Apk size getting larger after adding this package.

### ISSUE THREAD

**Issue by AbbosSaidov** [Unact/yandex_mapkit#194]
I created a new flutter project. In release mode apk size was 15mb. Then I added yandex_mapkit package. I did not write any code yet. But in release mode my apk size was 74mb.This package adding approximately 60 mb. For installing this i should add this  `implementation 'com.yandex.android:maps.mobile:4.0.0-full` to `android/app/build.gradle`. And I tried change it to `implementation 'com.yandex.android:maps.mobile:4.0.0-lite` my apk size was reduced to 60mb.How can I reduce size of apk after adding yandex mapkit?

**Comment by DCrow** [comment]
Hello!

Unfortunately nothing can be done about the size of app. This project is merely a port from native iOS/Android implementations. All size requirements are governed by those libraries.
Also this project does not support lite version of yandex mapkit, so it won't work if you use `implementation 'com.yandex.android:maps.mobile:4.0.0-lite `
