### ISSUE TITLE
Вложенные (Nested) ClusterizedPlacemarkCollection

### ISSUE THREAD

**Issue by Ae-Mc** [Unact/yandex_mapkit#195]
Хотелось бы иметь возможность вкладывать один ClusterizedPlacemarkCollection в другой, чтобы на разном удалении отображались разные кластеры

Пример:

https://user-images.githubusercontent.com/43097289/154675475-45f684bd-cb18-444d-a287-dbf9ce88be74.mp4

Сейчас это теоретически можно реализовать через MapObjectCollection + Placemark, но это довольно костыльно

**Comment by DCrow** [comment]
Добрый день!

`ClusterizedPlacemarkCollection` поддерживается только добавление `Placemark`.
Если хочется иметь разные кластеры, то это можно достичь указыванием для карты(`YandexMap.mapObjects`) нескольких кластеров с разными `ClusterizedPlacemarkCollection.minZoom`.

**Comment by DCrow** [comment]
radius определяет расстояние между точками, после которого точки надо объединять в кластер.
minZoom определяет zoom камеры, на котором надо отображать точки вместо кластера, с учетом что между точками расстояние меньше radius. 
1 - это уровень карты мира, 21 - самый приближенный. Таким образом при 1 кластеры будут всегда видны, когда радиус между точками меньше указанного, а при 21 наоборот никогда не будут видны.

`collection.isVisible = false` - это скороет всю коллекцию, включая отдельные точки. 
Отдельно скрыть кластер можно только при создании кластера в `onClusterAdded`, только стоит учитывать, что отображение кластера задается только один раз, и больше изменить его нельзя будет.

**Comment by Ae-Mc** [comment]
Спасибо
