### ISSUE TITLE
Вылетает именно на iOS при вызове  YandexSuggest.getSuggestions

### ISSUE THREAD

**Issue by the-thirteenth-fox** [Unact/yandex_mapkit#197]
Использую метод:    
```
var list = await YandexSuggest.getSuggestions(
                text: value,
                boundingBox: const BoundingBox(
                  northEast: Point(latitude: 81.843056, longitude: 59.239444),
                  southWest: Point(latitude: 41.220556, longitude: 47.857778),
                ),
                suggestOptions: const SuggestOptions(
                  suggestType: SuggestType.geo,
                  suggestWords: false,
                )).result;
```
в логах пишет:
Could not cast value of type 'NSNull' (0x115507d30) to 'NSDictionary' (0x1155075e0).
и потом вылет. В Android все отлично.
flutter: 2.10.1
yandex_mapkit: 2.0.2

**Comment by the-thirteenth-fox** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by the-thirteenth-fox** [comment]
лог при flutter run --verbose:
```
[+2320 ms] yandex::maps::mapkit::tiles::MemoryCache::clear <warn>: Clearing cache
[+7912 ms] Could not cast value of type 'NSNull' (0x1163a3d30) to 'NSDictionary' (0x1163a35e0).
[  +51 ms] Service protocol connection closed.
[   +3 ms] Lost connection to device.
[   +6 ms] DevFS: Deleting filesystem on the device
(file:///Users/vladislavponomarev/Library/Developer/CoreSimulator/Devices/60744A79-894A-4CDD-A15C-530FB70E007A/data/Containers/Data/Application/4F2A1B8D-997E-4190-945D-7B464
2065DEC/tmp/MyItalygMPy8H/MyItaly/)
[ +261 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +32 ms] "flutter run" took 129 117ms.
[  +21 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

**Comment by the-thirteenth-fox** [comment]
При использовании параметров из примера все ок, но используя мои параметры происходит баг

**Comment by DCrow** [comment]
Добрый вечер!

Да, бага в десериализации данных. В мастере поправил. На pub.dev в ближайшее время тоже выйдет.
