### ISSUE TITLE
yandex_mapkit 2.0.2 Мерцает экран при переходе с таба содержащего карту на любой другой таб

### ISSUE THREAD

**Issue by alexanderkind** [Unact/yandex_mapkit#199]
Здравствуйте!
На странице 3 таба, первый содержит карту и при переходе с него на любой другой таб мерцает экран.
В yandex_mapkit 1.1.1 мерцания не возникает.
В чем может быть проблема?
Спасибо.
[tabs_page.txt](https://github.com/Unact/yandex_mapkit/files/8171079/tabs_page.txt)

**Comment by alexanderkind** [comment]
Обнаружил на Android, на iOS пока не проверял.

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1526], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by DCrow** [comment]
Похоже тут такая же проблема что и в #182.
У меня на 2.10.1 уже не воспроизводится.

**Comment by alexanderkind** [comment]
После обновления стало лучше, но всё равно иногда заметны мерцания. Сейчас как будто текущая страница на очень короткое время теряет видимость и через неё просвечивается предыдущая по стеку навигации.
```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale ru-RU)
```

**Comment by DCrow** [comment]
Тут остается только ждать, когда команда flutter исправит багу в движке

**Comment by kozhuhar** [comment]
Эта проблема не исправлена для ios. т.е. она исправлена для android, если ты используешь hybrid composition. А вот для веба и для iOS эта проблема остается. Вот я приложил видос с тем, как это работает на iPhone 13 pro max. 

https://user-images.githubusercontent.com/25579320/161934525-3a07840e-7d99-4f15-8909-4a7de50c9f74.MP4

**Comment by DCrow** [comment]
В текущей версии флаттера 3.0.0 не могу воспроизвести
