### ISSUE TITLE
Некорректно отображается метка пользователя (UserLocationView)

### ISSUE THREAD

**Issue by abigotado** [Unact/yandex_mapkit#201]
Добрый день!

Возникают проблемы с отображением метки пользователя.

Пытаюсь сделать так, чтоб местоположение пользователя отмечалось только pin с буквой "Я". Без стрелочки и радиуса точности. Выставляю view.arrow.copyWith(isVisible: false) и view.accuracyCircle.copyWith(isVisible: false), однако ничего не меняется.

Эмулятор iOS продолжает отображать синий круг:

<img width="400" alt="Снимок экрана 2022-03-11 в 19 23 16" src="https://user-images.githubusercontent.com/82471392/157907108-67199100-7148-4ed9-b93d-f68a39022062.png">

Телефон (не эмулятор) Android и вовсе показывает только стрелку и круг, а pin появляться не хочет:

![photo_2022-03-11_19-31-35](https://user-images.githubusercontent.com/82471392/157908421-32207f8e-7f0e-486a-a7a6-72bfc90aa6d0.jpg)

Пример кода:

```YandexMapController _controller;```

```
YandexMap(
              onMapCreated: (YandexMapController controller) async {
                _controller = controller;
                await _controller.toggleUserLayer(visible: true);
              },
              onUserLocationAdded: (UserLocationView view) async {
                view = view.copyWith(
                  pin: view.pin.copyWith(
                    opacity: 1.0,
                  ),
                  arrow: view.arrow.copyWith(isVisible: false),
                  accuracyCircle:
                      view.accuracyCircle.copyWith(isVisible: false),
                );
                return view;
              },
            ),
```

Как это исправить?

И ещё один момент - есть ли возможность сменить цвет pin? Или она по умолчанию зелёная и её можно только заменить на другую иконку?

**Comment by DCrow** [comment]
Добрый день!

Для объектов `UserLocationView`, `isVisible` не работает в нативной либе https://github.com/yandex/mapkit-ios-demo/issues/139

Можно обойти следующем путем
```dart
onUserLocationAdded: (UserLocationView view) async {
  view = view.copyWith(
    pin: view.pin.copyWith(
      opacity: 1.0,
    ),
    arrow: view.arrow.copyWith(
      icon: PlacemarkIcon.single(
        PlacemarkIconStyle(image: BitmapDescriptor.fromAssetImage('assets/arrow.png'), isVisible: false)
      )
    ),
    accuracyCircle: view.accuracyCircle.copyWith(
      fillColor: Colors.transparent,
      strokeColor: Colors.transparent
    ),
  );

  return view;
}
```

> И ещё один момент - есть ли возможность сменить цвет pin? Или она по умолчанию зелёная и её можно только заменить на другую иконку?

Это иконка ассет внутри нативной библиотеки. Тут только используя другой ассет можно изменить вид.

**Comment by abigotado** [comment]
@DCrow Спасибо! Вроде теперь исчезло лишнее.
