### ISSUE TITLE
Проблема с определением координат пользователя

### ISSUE THREAD

**Issue by abigotado** [Unact/yandex_mapkit#202]
При запуске карты координаты пользователя поначалу определяются где-то возле Африки.

<img width="403" alt="Снимок экрана 2022-03-11 в 19 58 20" src="https://user-images.githubusercontent.com/82471392/157913730-8afec9ac-a0f3-4d41-b18b-810ef2a23bbf.png">

По нажатию кнопки запускаю функцию смены позиции - экран перемещается к реальным координатам, однако метка пользователя вместе с экраном не перемещается.

<img width="400" alt="Снимок экрана 2022-03-11 в 19 58 43" src="https://user-images.githubusercontent.com/82471392/157913820-7a38a8ab-fe4a-4782-be49-8b0b3785b93e.png">

Пример кода:
 
Кнопка:
```
FloatingActionButton.small(
                    onPressed: () async {
                      final CameraPosition _userPosition =
                          await _controller.getUserCameraPosition();
                      await _controller.moveCamera(
                        CameraUpdate.newCameraPosition(
                          CameraPosition(
                            target: _userPosition.target,
                          ),
                        ),
                      );
                    },
)
``` 

Карта:
```
YandexMapController _controller;
```

```
YandexMap(
              onMapCreated: (YandexMapController controller) async {
                _controller = controller;
                await _controller.toggleUserLayer(visible: true);
              },
              onUserLocationAdded: (UserLocationView view) async {
                view = view.copyWith(
                  pin: view.pin.copyWith(
                    opacity: 1.0,
                  ),
                  arrow: view.pin.copyWith(isVisible: false),
                  accuracyCircle:
                      view.accuracyCircle.copyWith(isVisible: false),
                );
                return view;
              },
            ),
```

Возможно, проблема в iOS-эмуляторе, так как на Android-устройстве всё в порядке, метка перемещается, как только обновляются координаты пользователя.
При этом самое странное, что на эмуляторе проблема лечится вот таким костылём:

```
YandexMap(
              onMapCreated: (YandexMapController controller) async {
                _controller = controller;
                await _controller.toggleUserLayer(visible: true);
                **await _controller.toggleUserLayer(visible: false);
                await _controller.toggleUserLayer(visible: true);**
              },
              onUserLocationAdded: (UserLocationView view) async {
                view = view.copyWith(
                  pin: view.pin.copyWith(
                    opacity: 1.0,
                  ),
                  arrow: view.pin.copyWith(isVisible: false),
                  accuracyCircle:
                      view.accuracyCircle.copyWith(isVisible: false),
                );
                return view;
              },
            ),
```
То есть выключением и повторным включением UserLayer.

**Comment by DCrow** [comment]
Добрый день!

Не удается воспроизвести описанную проблему на эмуляторе iOS. 
Возможно проблема, в том как вы обновляете местоположение на эмуляторе?

**Comment by AndreyCh1989** [comment]
аналогичная проблема на адроид эмуляторе

**Comment by abigotado** [comment]
> Добрый день!
> 
> Не удается воспроизвести описанную проблему на эмуляторе iOS. Возможно проблема, в том как вы обновляете местоположение на эмуляторе?

@DCrow Добрый день! У меня при запуске экрана с картой сразу почему-то метка юзера в Африке появляется. И там и зависает навсегда на iOS-эмуляторе. На Андроиде через какое-то время перепрыгивает на реальные координаты (хотя не всегда) на iOS - только если обновить весь экран.

При запуске такой функции метка юзера остаётся в Африке, как и была (хотя экран центрируется на реальной позиции):
```
Future<void> getUserPosition(BuildContext context, {double zoom}) async {
    if (await Permission.location.isDenied) {
      _showMessage(
        context,
        Text(
            'Чтобы увидеть своё местоположение, разрешите отслеживать геопозицию'),
      );
    } else {
      final CameraPosition _userPosition =
          await _controller.getUserCameraPosition();
      if (_userPosition != null) {
        await _controller.moveCamera(
          CameraUpdate.newCameraPosition(
            CameraPosition(
              target: _userPosition.target,
              zoom: zoom,
            ),
          ),
        );
      } else {
        getUserPosition(context, zoom: zoom);
      }
    }
  }
```

```
  YandexMapController _controller;
```

```
onMapCreated: (YandexMapController controller) async {
                    _controller = controller;
}
```

Или единственный способ обновить метку - вызвать обновление состояния всей карты?

**Comment by DCrow** [comment]
Исправил в мастере. Теперь должно сразу отображать точку пользователя в нужном месте.
