### ISSUE TITLE
ошибка при сборке на xcode 13.3 

### ISSUE THREAD

**Issue by topor00** [Unact/yandex_mapkit#203]
Несколько дней назад вышла новая версия xcode 13.3, и при сборке проекта на реальное устройство (и в архив) возникает ошибка
in ***project***/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '***project***/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
на предыдущей версии xcode такой проблемы не было и все работало исправно.
Добавлю также, что при запуске на эмуляторе, сборка происходит успешно, но в самом приложении сама карта местности не отображается

**Comment by DCrow** [comment]
Дубль #146

> Добавлю также, что при запуске на эмуляторе, сборка происходит успешно, но в самом приложении сама карта местности не отображается

Если вы о том что видна сетка без отображения карты, значит проблема в ключе(либо не указан, либо не активирован).

**Comment by topor00** [comment]
думаю, это все же не дубль, ошибка иная, чем в той теме, на которую вы ссылаетесь.
на гите нативной библиотеки яндекс карт нашел схожую проблему https://github.com/yandex/mapkit-ios-demo/issues/106#issuecomment-1072275846
значит ли это, что решение будет только в следующей версии? или у вас исправно собирается проект на xcode 13.3 ?

по поводу подложки карт на эмуляторе - да, сама подложка не видна. что касается ключа - он активирован и приложение с этим ключом исправно работает (собранное на предыдущей версии xcode) на телефоне

**Comment by DCrow** [comment]
Да, действительно вы правы. Тут ошибка в новом XCode, и что текущая версия нативной либы не поддерживает его.

Таким образом остается только ждать, когда команда Яндекс поправит эту багу, только тогда можно будет и эту либу обновить.

На данный момент могу только посоветовать, как в комментах пишут, использовать более старую версию XCode.

**Comment by FeofanGreek** [comment]
Присоединяюсь к ветке. На Андроид блидится ОК. На симуляторы билдится ОК, при попытке созать билд на релиз в стор ошибит (ld: in /Users/***/Documents/flutter_project/toolsapp/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/dkoldashev/Documents/flutter_project/toolsapp/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

)

**Comment by remakerich** [comment]
> Присоединяюсь к ветке. На Андроид блидится ОК. На симуляторы билдится ОК, при попытке созать билд на релиз в стор ошибит (ld: in /Users/***/Documents/flutter_project/toolsapp/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/dkoldashev/Documents/flutter_project/toolsapp/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> )
> 
> Процессор М1, предыдущие билды шли нормально, проблема возникла после обновления xCode будь он не ладен Version 13.3 (13E113)

не подскажешь как ты запускал под м1?

**Comment by FeofanGreek** [comment]
> 

меняешь на armv7  и получается запустить на эмуляторе. Чтоб сделать билд для стора или реального устройства нужен arm64, он по прежнему ошибит

**Comment by akbarpulatov** [comment]
Есть новости?

**Comment by akbarpulatov** [comment]
Есть новости?

**Comment by akbarpulatov** [comment]
Есть новости?

**Comment by lappi** [comment]
Поговаривают что в 4.1.0 баг закрыли, когда планируется апдейт?
https://github.com/yandex/mapkit-ios-demo/issues/106#issuecomment-1130101072

**Comment by DCrow** [comment]
Когда 4.1.0 официально релизнут, тогда и здесь обновим. Пока что на [сайте](https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/versions.html#versions__versions) версии нет(кроме того и для андроид еще версия не вышла), поэтому пока ждем. 
Если все же про него забыли и тп, тогда через неделю-две обновлю.

**Comment by airsend** [comment]
> Когда 4.1.0 официально релизнут, тогда и здесь обновим. Пока что на [сайте](https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/versions.html#versions__versions) версии нет(кроме того и для андроид еще версия не вышла), поэтому пока ждем.
> Если все же про него забыли и тп, тогда через неделю-две обновлю.

Появилась новая версия

**Comment by bondsy777** [comment]
Не собирается на физическом ios девайсе:
Could not build the precompiled application for the device. Версия yandex_mapkit: ^2.0.6.
Error (Xcode): In ...ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file for architecture arm64

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-arm, locale en-RU)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)

**Comment by bondsy777** [comment]
когда планируется смержить?

**Comment by DCrow** [comment]
Обновлено в 3.0.0

**Comment by FeofanGreek** [comment]
чтоб запустить на симуляторе убираешь из архитектур в xCode  arm64 оставляешь только armv7. На симуляторе в этом случае билдится.
