### ISSUE TITLE
Некорректная работа кластеризации

### ISSUE THREAD

**Issue by ProstoCesar** [Unact/yandex_mapkit#204]
При приближении карты иногда не исчезают маркеры кластера. 
(маркеры 20 и 25 зависли) 
![image](https://user-images.githubusercontent.com/37967291/159727021-179ab93d-482a-404e-8e7c-4bcfb03c260d.png)
![image](https://user-images.githubusercontent.com/37967291/159727309-cd493221-1e72-4661-b52a-a071fef29dbe.png)
![image](https://user-images.githubusercontent.com/37967291/159727466-da3710b0-2e56-45dc-8e4e-c618062cb1b5.png)

**Ожидаемое поведение:**
Маркер кластера исчезает при достаточном приближении карты и появляются точки, которые находились в кластере.

**Фактическое поведение:**
Иногда маркер кластера не исчезает с карты и появляются точки, которые находились в кластере.

**Заметка:** 
"Зависший" маркер кластера не исчезнет до тех пор, пока он не будет объединен в больший кластер при отдалении карты.
После этого можно отдалять\приближать карту и кластер будет вести себя корректно.

После максимального отдаления все работает корректно.
![image](https://user-images.githubusercontent.com/37967291/159727191-b472cf3a-7807-460f-b4a5-5fe3af7f19de.png)
![image](https://user-images.githubusercontent.com/37967291/159727487-09827973-9e29-4d7b-9ae8-f51fa25ab0a8.png)

flutter doctor -v

[✓] Flutter (Channel stable, 2.8.0, on macOS 11.5.2 20G95 darwin-x64, locale ru-RU)
    • Flutter version 2.8.0 at /Users/eugenesorokin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/eugenesorokin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

**Comment by Cortrano** [comment]
Такая же проблема

**Comment by DCrow** [comment]
Добрый день.

Это происходит на Android или iOS?
Также просьба приложить пример кода, когда такое поведение воспроизводится.

На данный момент работа кластеров, в том числе их отображение и скрывание делигируется в нативную библиотеку. Исправить эту проблему может только команда Яндекс.

**Comment by DCrow** [comment]
Исправлено в мастере
