### ISSUE TITLE
При большом количестве полигонов серьёзные проблемы с оптимизацией

### ISSUE THREAD

**Issue by Cortrano** [Unact/yandex_mapkit#205]
Проблема заключается в следующем. Имеем достаточно большое количество точек для отрисовки полигонов. Получаем и фетчим мы их быстро (мерил через Stopwatch, это где-то 1.5 секунды), но отрисовываются на экране они только через +- 20 секунд после открытия экрана. А до этого момента - фриз без возможности что-либо делать с приложением, а иногда даже с ошибкой, что приложение не отвечает. Речь скорее про живое устройство (проверено на нескольких), потому что у эмулятора это протекает быстрее. Далее будет 3 скриншота состояний. 
1.  фриз состояние где невозможно ничего делать
2. фриз состояние где появляется сообщение о том,  что приложение не отвечает (появляется не всегда)
3. отвисло, всё работает (отвисает всегда)

![state1_freezed](https://user-images.githubusercontent.com/61734748/160105488-182ac539-e71f-4ac8-8fea-c167b8004d90.jpg)
![state2_freezed](https://user-images.githubusercontent.com/61734748/160105424-bb500277-9817-45dd-b445-3b429bef3d3c.jpg)
![state3_noraml](https://user-images.githubusercontent.com/61734748/160105436-03d8897d-5a59-45ed-aea7-ba80f2df5633.jpg)

Пробовал смотреть в DevTools, там картина яснее не становится, 20 секунд фриза и отвисание никак в CPU Profile и Performance Timeline не видны

![Screenshot 2022-03-25 at 1 14 48 PM](https://user-images.githubusercontent.com/61734748/160102107-70441a10-6330-47b9-9a62-26a648f38dd0.png)

Примерно аналогичная картина в Dart VM Observatory, там на Таймлайн мы видим записи не дольше трёх секунд, хотя полигоны на карте появились только спустя 20 секунд.

![Screenshot 2022-03-25 at 1 24 41 PM](https://user-images.githubusercontent.com/61734748/160103632-b1a306dd-3daa-4609-8d53-4ed782451ecf.png)

На всякий случай приложу снимки из DevTools и из Dart VM Observatory
[dart_timelines.zip](https://github.com/Unact/yandex_mapkit/files/8349569/dart_timelines.zip)

Дополнительные данные:
Flutter 2.10.3
Ноут с эмулятором: MacBook M1 Pro
Живой андроид: Xiaomi Mi 9 (Android 11, MIUI 12.5.2)

**Comment by DCrow** [comment]
Добрый день!

Это проблема нативной Android библиотеки. Тут остается ждать, только когда команда Яндекс поправит ошибку.
Уже похожие проблемы там были(например https://github.com/yandex/mapkit-android-demo/issues/156)
