### ISSUE TITLE
Крэшится приложение на андроиде, собранное на версиях плагина gradle, больше 4.0.2

### ISSUE THREAD

**Issue by pamir72** [Unact/yandex_mapkit#206]
Крэшится приложение (в том числе **пример из yandex_mapkit** без изменений кода) после выхода из него и последующего запуска. Запускал как на эмуляторе, так и на реальном устройстве. Подскажите пожалуйста где может быть проблема ?

_**Выход из приложения после 1го запуска**_
...
W/yandex.maps( 6754): yandex::maps::mapkit::map::MapImpl::onMemoryWarning: Got memory warning
E/BufferQueueProducer( 6754): [ImageReader-720x1184f1m3-6754-1](id:1a6200000001,api:1,p:6754,c:6754) cancelBuffer: BufferQueue has been abandoned
W/FlutterSurfaceView( 6754): detachFromRenderer() invoked when no FlutterRenderer was attached.
W/yandex.maps( 6754): yandex::maps::mapkit::tiles::MemoryCache::clear: Clearing cache

**_2й запуск приложения_**
...
D/EGL_emulation( 6754): eglMakeCurrent: 0xaee06d00: ver 3 0 (tinfo 0xb8bb4ab0) (first time)
D/AndroidRuntime( 6754): Shutting down VM
E/AndroidRuntime( 6754): FATAL EXCEPTION: main
E/AndroidRuntime( 6754): Process: com.unact.yandexmapkitexample, PID: 6754
E/AndroidRuntime( 6754): java.lang.AssertionError: setApiKey() should be called before initialize()!
E/AndroidRuntime( 6754): 	at com.yandex.mapkit.MapKitFactory.setApiKey(MapKitFactory.java:34)
E/AndroidRuntime( 6754): 	at com.unact.yandexmapkitexample.MainActivity.configureFlutterEngine(MainActivity.java:13)
E/AndroidRuntime( 6754): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
E/AndroidRuntime( 6754): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/AndroidRuntime( 6754): 	at android.app.Activity.performCreate(Activity.java:7994)
E/AndroidRuntime( 6754): 	at android.app.Activity.performCreate(Activity.java:7978)
E/AndroidRuntime( 6754): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime( 6754): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime( 6754): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime( 6754): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime( 6754): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6754): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6754): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 6754): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6754): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6754): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6754): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6754): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6754): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 6754): Sending signal. PID: 6754 SIG: 9

**_3й запуск ок, 4й крешится и т.д._**

**_MainActivity.java_**

package com.unact.yandexmapkitexample;
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import com.yandex.mapkit.MapKitFactory;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    MapKitFactory.setApiKey("XXXX-XXX-...");
    super.configureFlutterEngine(flutterEngine);
  }
}

**_flutter doctor -v_**

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale ru-RU)
    • Flutter version 2.10.4 at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ...
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • An

**Comment by DCrow** [comment]
Добрый день!

Подскажите, а какую версию проекта вы используете?
И что вы подразумеваете под 1, 2 запуском? Запуск скомпилированного под debug версию проекта? Под release? Или последовательные запуски с помощью VSCode/Android Studio/консоли ?

**Comment by DCrow** [comment]
Похоже что это такая же проблема что и в https://github.com/yandex/mapkit-android-demo/issues/219
Чтобы ее обойти надо в `android/build.gradle` указать `com.android.tools.build:gradle:4.0.2` вместо текущей версии.

**Comment by pamir72** [comment]
Да, действительно замена gradle 4.1.1 на 4.0.2 помогла !
Благодарю !

**Comment by pamir72** [comment]
Вышедший недавно Flutter 3.0 приносит с собой обновление плагина gradle до **7.1.2** (версия gradle 7.4). Однако замена версии **4.0.2** на любую, в том числе **7.1.2** вызывает описанный выше креш. Планируется ли как-то решать данную проблему ?

**Comment by DCrow** [comment]
Этот вопрос стоит задать команде Яндекс в https://github.com/yandex/mapkit-android-demo/issues/219, проблема в нативной либе.

**Comment by DCrow** [comment]
Насколько я вижу обновление нативных либ до 4.1 убрало эту проблему.

**Comment by pamir72** [comment]
К сожалению, проблема не решилась. Все осталось, как и было.

FATAL EXCEPTION: main
E/AndroidRuntime( 4858): Process: ru.serviopump.spmobile, PID: 4858
E/AndroidRuntime( 4858): java.lang.AssertionError: setApiKey() should be called before initialize()!
E/AndroidRuntime( 4858): 	at com.yandex.mapkit.MapKitFactory.setApiKey(MapKitFactory.java:34)
E/AndroidRuntime( 4858): 	at ru.serviopump.spmobile.MainActivity.configureFlutterEngine(MainActivity.java:13)
E/AndroidRuntime( 4858): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:200)
E/AndroidRuntime( 4858): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime( 4858): 	at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime( 4858): 	at android.app.Activity.performCreate(Activity.java:8270)
E/AndroidRuntime( 4858): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime( 4858): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
E/AndroidRuntime( 4858): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
E/AndroidRuntime( 4858): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime( 4858): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4858): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 4858): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
E/AndroidRuntime( 4858): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4858): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 4858): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 4858): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime( 4858): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4858): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 4858): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by DCrow** [comment]
Мне не удается воспроизвести с вашими параметрами ошибку. 
Кроме того в примере от яндекса, тоже указывается 7.1.3.

Возможно сейчас у вас проблема возникает из-за какого-то другого плагина.

**Comment by pamir72** [comment]
Проблема из за yandex_mapkit (или плагина).
До этого у меня были гугловские карты и gradle 4.1.1. Перешел на yandex_mapkit и возникла эта проблема (в том числе пробовал на вашем примере - там нет "левых" плагинов).

Чуть позже попробую пример из yandex_mapkit. Отпишусь по результатам.

**Comment by pamir72** [comment]
Как обещал - "голый" пример из yandex_maprit

E/AndroidRuntime(17346): FATAL EXCEPTION: main
E/AndroidRuntime(17346): Process: com.unact.yandexmapkitexample, PID: 17346
E/AndroidRuntime(17346): java.lang.AssertionError: setApiKey() should be called before initialize()!
E/AndroidRuntime(17346): 	at com.yandex.mapkit.MapKitFactory.setApiKey(MapKitFactory.java:34)
E/AndroidRuntime(17346): 	at com.unact.yandexmapkitexample.MainActivity.configureFlutterEngine(MainActivity.java:13)
E/AndroidRuntime(17346): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:200)
E/AndroidRuntime(17346): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(17346): 	at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(17346): 	at android.app.Activity.performCreate(Activity.java:8270)
E/AndroidRuntime(17346): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
E/AndroidRuntime(17346): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
E/AndroidRuntime(17346): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
E/AndroidRuntime(17346): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(17346): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17346): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17346): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
E/AndroidRuntime(17346): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17346): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(17346): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(17346): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(17346): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17346): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(17346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by pamir72** [comment]
> Мне не удается воспроизвести с вашими параметрами ошибку. Кроме того в примере от яндекса, тоже указывается 7.1.3.
>

Да, в примере яндекса 7.1.3, но там везде рекомендуют api key устанавливать с синглетоне  Application. И да, в этом случае все работает (пробовал на Java). Что касается плагина для dart/flutter, то как описано в readme.md работает с gradle 4.0.2, но не выше.
Видимо рекомендацию по Application как-то надо перенести в реализацию для yandex_mapkit dart/flutter.

**Comment by pamir72** [comment]
Важное добавление ! Обнаружил, что если после выхода из приложения его закрыть (выкинуть из сидящих в памяти), то все работает ок ! Видимо все же при выходе не происходит "деинициализация" MapKitFactory.
