### ISSUE TITLE
Как правильно получить ScreenRect из Point/BoundingBox 

### ISSUE THREAD

**Issue by abigotado** [Unact/yandex_mapkit#210]
У объекта YandexMap() есть параметр screenRect, который, если не ошибаюсь, при создании карты автоматом центрирует экран на определённой её области.

Если у меня есть Point() с определёнными координатами, который я хотел бы видеть в центре экрана при создании карты или BoundingBox() с областью, которую хотел бы видеть сразу при запуске карты - из них можно получить ScreenRect()?

Или необходимо каждый раз при старте карты запускать метод moveCamera() у YandecxMapController?

**Comment by DCrow** [comment]
Добрый день!

`YandexMap.screenRect` не центрирует карту, а задает границы внутри карты для работы камеры(меняет центр камеры, относительно заданных координат, вместо настоящего центра карты). 
Вот [тут](https://yandex.com/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKMapWindow.html#focusRect) более обширно описано.

Если хочется, чтобы какая-то определенная точка была в центре, то только через `YandexMapController.moveCamera`

**Comment by abigotado** [comment]
Добрый день!

Спасибо за объяснение!
