### ISSUE TITLE
Долго инициализирует карту на IOS

### ISSUE THREAD

**Issue by rkontrast** [Unact/yandex_mapkit#212]
Добрый день. Спасибо большое за порт карты.
Столкнулись с такой проблемой, что на ios сборках карта инициализируется относительно долго( +- 10 секунд ), тогда как как на эмуляторе это происходит считанные секунды. На андроид сборках также грузит относительно быстро.
Также прикладываю настройки Architectures из xcode.
С чем это может быть связано? С тем что для ios сборок используется иная архитектура в сравнении с симулятором?

https://user-images.githubusercontent.com/96019561/163567599-65f9f189-3323-47d7-8cb1-2a5692d35ceb.MP4

https://user-images.githubusercontent.com/96019561/163567633-fa75b646-4890-412b-83d5-cf8bf126b3b3.mov

<img width="970" alt="Снимок экрана 2022-04-15 в 14 50 01" src="https://user-images.githubusercontent.com/96019561/163567659-d196b926-7172-4599-989e-71fc3379afda.png">
<img width="973" alt="Снимок экрана 2022-04-15 в 14 50 09" src="https://user-images.githubusercontent.com/96019561/163567672-ce1fc418-ab86-4dd4-a4ad-6553b990ce64.png">

**Comment by DCrow** [comment]
Здравствуйте!

Не могу сказать с чем это может быть связано. В примере, который вы указали, это может быть как и какие-то зависимости в вашем коде, так и специфика инициализации во флаттер, так и, как вы говорите, сама библиотека yandex_mapkit.

Без примера кода и зависимостей нельзя однозначно сказать.

**Comment by DCrow** [comment]
Закрываю так как нет ответа.
