### ISSUE TITLE
YandexClusterizedPlacemarkCollectionController.swift line 125

### ISSUE THREAD

**Issue by overdrowe** [Unact/yandex_mapkit#217]
Добрый день, падает такая ошибка в крашлитику фб ios'а у наших пользователей, откуда именно падает ошибка не понимаю
Версия библиотеки 2.0.4
Версия флаттера 2.10.4

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x7964 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7378 pthread_kill + 268
2  libsystem_c.dylib              0x1ff50 abort + 164
3  libswiftCore.dylib             0x385e94 swift_vasprintf(char**, char const*, char*) + 58
4  libswiftCore.dylib             0x37c8c4 swift::swift_dynamicCastFailure(swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*, char const*) + 78
5  libswiftCore.dylib             0x37c940 swift::_conformsToProtocol(swift::OpaqueValue const*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptorRef<swift::InProcess>, swift::TargetWitnessTable<swift::InProcess> const**) + 122
6  libswiftCore.dylib             0x380ea0 swift_dynamicCast::$_0::__invoke(void*) + 306
7  Runner                         0x234eeb8 closure #2 in YandexClusterizedPlacemarkCollectionController.onClusterAdded(with:) + 125 (YandexClusterizedPlacemarkCollectionController.swift:125)
8  Runner                         0x23528d8 thunk for @escaping @callee_guaranteed (@in_guaranteed Any?) -> () + 224924 (<compiler-generated>:224924)
9  Flutter                        0x3a6ac (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
10 Flutter                        0x2fbbf0 (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
11 Flutter                        0x2ff1bc (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
12 CoreFoundation                 0xae318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
13 CoreFoundation                 0x32cf0 __CFRunLoopDoTimer + 1076
14 CoreFoundation                 0x2d4ec __CFRunLoopDoTimers + 328
15 CoreFoundation                 0xbd08 __CFRunLoopRun + 1944
16 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
17 GraphicsServices               0x138c GSEventRunModal + 164
18 UIKitCore                      0x5195d0 -[UIApplication _run] + 1100
19 UIKitCore                      0x297f74 UIApplicationMain + 364
20 Runner                         0x699c main + 6 (AppDelegate.swift:6)
21 ???                            0x105dc1aa4 (Missing)
```

**Comment by overdrowe** [comment]
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale ru-RU)
• Flutter version 2.10.4 at /Users/overdrowe/Development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
• Engine revision 57d3bac3dd
• Dart version 2.16.2
• DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
• Android SDK at /Users/overdrowe/Library/Android/sdk
• Platform android-32, build-tools 32.1.0-rc1
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
• Xcode at /Applications/Xcode.app/Contents/Developer
• CocoaPods version 1.11.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
• Android Studio at /Applications/Android Studio Preview.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
✗ Unable to find bundled Java version.
• Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
• iPhone 13 (mobile) • 86E900D5-1308-4260-B0DA-7D003F5AE61F • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
• Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
• All required HTTP hosts are available

**Comment by DCrow** [comment]
Добрый день!

Судя по ошибке, где-то в вашем коде в методе `ClusterizedPlacemarkCollection.onClusterAdded` происходит ошибка, и вместо возвращения в `Cluster`, у вас выбрасывается ошибка. 

В мастере это было не давно исправлено(сам креш), в pub.dart это еще не попало.

**Comment by overdrowe** [comment]
Тысяча благодарностей)
