### ISSUE TITLE
Не отображаются плейсмарки с кастомной иконкой в --release моде. Android

### ISSUE THREAD

**Issue by kidok313** [Unact/yandex_mapkit#219]
Все отлично работает в дебаге, но когда запускаю релиз или билжу бандл все плейсмарки просто невидно
Логи пустые, ошибок нет

Маркер ставится в начале билда при получении аргументов.

```
final args =
        ModalRoute.of(context)?.settings.arguments as AddressMapArguments?;
    if (args != null) {
      mapObjects = [
        Placemark(
          mapId: const MapObjectId('map_marker_id'),
          point: Point(
            latitude: args.location.latitude,
            longitude: args.location.longitude,
          ),
          opacity: 1,
          icon: PlacemarkIcon.single(
            PlacemarkIconStyle(
              image: BitmapDescriptor.fromAssetImage(
                getIconRatio('assets/markers/marker.png'),
              ),
              scale: 0.7,
            ),
          ),
        )
      ];
    }
```

**Comment by DCrow** [comment]
Здравствуйте!

В данном случае, видимо у вас различаются способы подгрузки ассетов в релизе. 
Библиотека использует флаттеровские способы получения ассетов, и разницы между релизом и дебагом не знает.

**Comment by kidok313** [comment]
Ассеты отлично грузятся, иконку пользователя подхватила карта, а вот маркеров нет. Так что странно что везде работают ассеты, а в маркерах нет.

**Comment by kidok313** [comment]
Вот без моих иконок 
```

if (args != null) {
      mapObjects.addAll([
        Placemark(
          mapId: const MapObjectId('marker_id'),
          point: Point(
            latitude: args.location.latitude,
            longitude: args.location.longitude,
          ),
          opacity: 1,
        )
      ]);
    }
```
![Дебаг](https://user-images.githubusercontent.com/42135981/165513363-c28e87ff-f3b4-4fce-b3f8-bb4176b22c69.png)

![--release](https://user-images.githubusercontent.com/42135981/165513421-4ed0abd9-5b98-4b85-938c-b70f45bc97ef.png)

**Comment by DCrow** [comment]
Судя по вашему скрину проблема в нативной библиотеке. Особенно если вы говорите, что у вас отображается метка пользователя(которая использует такой же механизм, что и обычные метки)

Возможно там такая же проблема, описанная тут https://github.com/yandex/mapkit-android-demo/issues/132

**Comment by kidok313** [comment]
Нет я уже даже подгрузил файл с веба с иконкой, закинул через BitmapDescriptor.fromBytes и такая же проблема.

**Comment by kidok313** [comment]
> Здравствуйте!
> 
> В данном случае, видимо у вас различаются способы подгрузки ассетов в релизе. Библиотека использует флаттеровские способы получения ассетов, и разницы между релизом и дебагом не знает.

короче проблема в extra-gen-snapshot-options=--obfuscate в gradle.properties

может вы знаете способ про обфусцировать приложение не ломая функционал yandex map?

**Comment by zemeister23** [comment]
@kidok313 

Вы смогли решить эту проблему?

У меня такая же проблема
