### ISSUE TITLE
Проблемы с производительностью отрисовки Placemark в режиме CameraTracking

### ISSUE THREAD

**Issue by lappi** [Unact/yandex_mapkit#220]
Добрый день!

Заметил проблему с производительностью отрисовки Placemark в режиме CameraTracking.
Для сравнения версии 1.1.1 (с использованием enableCameraTracking) и 2.0.4 (уже просто onCameraPositionChanged)
На 2.0.4 видно заметное дрожание Placemark при перемещении карты,
Вопрос, с чем связана депрекация enableCameraTracking и планируется ли в новых версиях поддержка плавной отрисовки Placemark в режиме слежения?

**2.0.4**
![IMG_9704](https://user-images.githubusercontent.com/3740390/165080840-8af20ffc-611a-4525-822f-86067f3b7b90.gif)

**1.1.1**
![IMG_9705](https://user-images.githubusercontent.com/3740390/165080916-6f1091d2-8a8a-43bc-9d29-41ff52c54a1d.gif)

**Comment by DCrow** [comment]
Здравсвуйте!

Депрекация связана с тем, что метод не позволял полноценно работать с изменениями камеры, не давал в полной мере работать с Placemark, кроме того имплементация сделана так, что дальнейшая доработка либы сильно усложнялась.

Дрожание получается из-за того, что связь между dart и iOS/Android во флаттер асинхронная. 
Функционал будет доработан, только когда флаттер сделает возможным обращаться с нативной стороной синхронно, пока этого не произойдет изменить этот функционал не предоставляется возможным.

**Comment by lappi** [comment]
Спасибо за ответ!
А что если сделать этот функционал чисто в нативной части как отдельный режим?
```
onCameraPositionChanged: (CameraPosition cameraPosition, CameraUpdateReason _, bool __) async {
    final placemark = mapObjects.firstWhere((el) => el.mapId == cameraMapObjectId) as Placemark;

    setState(() {
        mapObjects[mapObjects.indexOf(placemark)] = placemark.copyWith(point: cameraPosition.target);
    });
},
```
ведь по сути это сильно лишняя работа перекидывать одно только изменение координат через platform channels для этой конкретной задачи слежения маркера за перемещением карты 
даже в старой версии с **enableCameraTracking** все равно прокидывался коллбэк чтобы изменить координаты, что если координаты вообще не выносить из нативной части для этого режима, а только установить Placemark и включать/выключать слежение

**Comment by DCrow** [comment]
> ведь по сути это сильно лишняя работа перекидывать одно только изменение координат через platform channels для этой конкретной задачи слежения маркера за перемещением карты

Смысл метода, не в том чтобы повторять функционал старого, а дать пользователям либы возможность следить за изменениями камеры и не более.
