### ISSUE TITLE
Вопрос по маркерам

### ISSUE THREAD

**Issue by sk784** [Unact/yandex_mapkit#221]
Есть ли возможность в новой версии передавать и показывать внутри маркера помимо координат еще один параметр, который меняется динамически? И если есть, то можно показать на примере?

**Comment by DCrow** [comment]
Добрый день!

Для вашего случая вы можете на флаттере создавать png картинку, приводить ее к массиву байт и использовать его для отображения маркера. 
Пример такого поведения есть [тут](https://github.com/Unact/yandex_mapkit/blob/master/example/lib/examples/placemark_page.dart#L132-L191)

**Comment by sk784** [comment]
Супер, разобрался, спасибо)
