### ISSUE TITLE
Некорректное отображение маркеров на карте 

### ISSUE THREAD

**Issue by overdrowe** [Unact/yandex_mapkit#222]
Добрый день!
Иногда на карте отображаются лишние метки
Прикладываю скрин с отладкой соответствующей текущему моменту в видео

Версия библиотеки 2.0.4
Версия флаттера 2.10.5
 
[Видео демонстрирующее баг](https://user-images.githubusercontent.com/45872071/165271852-ee558791-7796-4b16-a8ef-af8f10344b7a.MP4)

![photo_2022-04-26_14-30-55](https://user-images.githubusercontent.com/45872071/165271892-0d85fac6-e308-4cf8-8a78-83e303cddff3.jpg)

`[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale ru-RU)
    • Flutter version 2.10.5 at /Users/overdrowe/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/overdrowe/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Users/overdrowe/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • iPhone (Антон) (mobile) • 00008030-001950C41A13402E            • ios            • iOS 15.4 19E241
    • iPhone 13 (mobile)      • 15A94437-C166-4111-AAF7-520CB2556CAE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 100.0.4896.127
    ! Error: iPhone (Антон) is busy: Preparing the watch for development via iPhone (Антон). Xcode will continue when iPhone (Антон) is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

**Comment by overdrowe** [comment]
Вот нормальное отображение
Но время от времени происходит то, что я прикрепил выше
![image](https://user-images.githubusercontent.com/45872071/165277704-b3c88263-90b9-465b-b626-bdd8d2fa70ca.png)

**Comment by DCrow** [comment]
Здравствуйте!

А что вы подразумеваете под лишними метками? 
Кластеры или точки внутри кластеров?

Из скрина не совсем понятно, какие точки должны быть, а какие нет

**Comment by overdrowe** [comment]
Добрый день, в метках подаем лишь 2 объекта, а отображается гораздо больше на видео в начале ишью и на скрине, который был прикреплен позже демонстрируется одно и то же состояние, но по какой-то причине поведение разное.
В первом случае отображается явно гораздо большее количество меток, при этом многие из них не нажимаются (Все которые не подаем в качестве объектов), во втором же случае все отображается корректно

Есть ли идеи почему это может происходить? Код написан не мной, но как я понимаю отображать должно только то , что мы подаем в виджет карт в поле mapObjects

**Comment by DCrow** [comment]
Вы хотите сказать, что вы передаете только две точки в ClusterizedPlacemarkCollection и открываете карту только с этим кластером, но после этого возникает куча других точек(не кластеров), которые вы не указывали?

**Comment by overdrowe** [comment]
Да, все верно

**Comment by overdrowe** [comment]
Может ли такое быть вообще? Насколько я заметил, точно именно на объектах стоят и в теории допускаю что они как то могли сохраниться после подачи новых mapObjects.

**Comment by overdrowe** [comment]
Понял, благодарю, будем смотреть дальше

**Comment by DCrow** [comment]
Пока закрываю, так как на данный момент похожую проблему в либе не нахожу.

**Comment by overdrowe** [comment]
Окей, пока что у меня так и не вышло найти в чем проблема
В _mapObjects так и лежит одно количество объектов а отображается совсем другое (иногда)
Такое у нас происходит при изменении набора placemarks

**Comment by DCrow** [comment]
В случае если просто обновить _mapObjects, и не вызывать setState, такая ситуация же может быть.
Может в вашем коде, где-то не происходит обновление state?
