### ISSUE TITLE
Проблема с отрисовкой Polyline

### ISSUE THREAD

**Issue by fivenation** [Unact/yandex_mapkit#225]
Здравствуйте!

Пишу приложение, где при смене геопозиции предыдущие зафиксированные точки связываются линией Polyline.
Столкнулся с проблемой (использую ScopedModel), что при работе логики и вызове notifyListeners(), параметры YandexMap меняются, но линия на карте не перерисовывается. Протестировал это дело на изменении параметра nightModeEnabled. (При нажатии на кнопку забегаем в логику-меняем параметр в модели, notifyListeners и всё, состояние обновляется и YandexMap с изменённым параметром выводит что нужно (true\false)). Просматривал значения полей YandexMap --- в MapObjects,  как и должно, лежит Polyline, все точки правильные. Но на карте линия не отображается.

Обнаружил ошибки ещё при первой попытке нарисовать Polyline, пытался отыскать значение, ничего не выяснил:
```
E/yandex.maps( 9192): yandex::maps::mapkit::images::PolylineImageAtlas::add: Width of pattern is equal to 268, but should be power of 2. Added transparent padding
W/yandex.maps( 9192): yandex::maps::mapkit::textures::Atlas::addTexture: Atlas: LayersAtlas. Page: 2 created. That could seriously decrease rendering speed
```

Ниже 3 фрагмента и вывод приложения. 1 - функция изменения MapObjects. 2 - Функция фиксации текущей позиции. 3 - Сам виджет YandexMap, обёрнутый в ScopedModelDescedant.

```dart
 void _updatePolyline() {
    if (objectsList.any((el) => el.mapId == _pathId)) {
      final polyline = objectsList.firstWhere((el) => el.mapId == _pathId) as Polyline;
      objectsList[objectsList.indexOf(polyline)] = polyline.copyWith(
        coordinates: _points,
        strokeColor: Colors.blue[700]!,
        strokeWidth: 7.5,
        outlineColor: Colors.blue[200]!,
        outlineWidth: 2.0,
        isVisible: true,
      );
      print('\nPOLYLINE UPDATED\n');
    } else {
      final polyline = Polyline(
        mapId: _pathId,
        coordinates: _points,
        strokeColor: Colors.blue[700]!,
        strokeWidth: 7.5,
        outlineColor: Colors.blue[200]!,
        outlineWidth: 2.0,
        isVisible: true,
      );
      objectsList.add(polyline);
      print('\nPOLYLINE ADDED\n');
    }
    if (_nightMode == true) {
      _nightMode = false;
    } else {
      _nightMode = true;
    }
  }
```

```dart
void _updatePosition() {
    _locationRepository.getCurrentLocation().then((value) async {
      _points.add(value);
      _updatePolyline();
      YandexMapController controller = await _completer.future;
      controller.moveCamera(CameraUpdate.newCameraPosition(CameraPosition(
          target: Point(latitude: value.latitude, longitude: value.longitude),
          zoom: _fixedZoom)));
      notifyListeners();
      print('LISTENERS NOTYFIED');
    });
  }
```
```dart
........
child: ScopedModelDescendant<MapController>(builder: (context, child, model) {
             return Column(
                children: [
                  Expanded(
                    child: YandexMap(
                      zoomGesturesEnabled: false,
                      scrollGesturesEnabled: false,
                      rotateGesturesEnabled: false,
                      //liteModeEnabled: true,
                      mapObjects: model.objectsList,
                      nightModeEnabled: model._nightMode,
                      onMapCreated: model._onMapCreated,
                    ),
                  ),
......
```

Подскажите пожалуйста, как быть. Вроде всё логично, но ничего не работает.
![image](https://user-images.githubusercontent.com/86624715/166154996-26b4de47-7339-4bcd-abed-de01a6a50de1.png)

**Comment by fivenation** [comment]
Спустя неделю попыток разобраться, что же не так происходит.... я тыкнул следующее и оно заработало!!!!!!

```dart
...
    final polyline = objectsList.firstWhere((el) => el.mapId == _pathId) as Polyline;
    objectsList[objectsList.indexOf(polyline)] = polyline.copyWith(
      strokeColor: Colors.primaries[Random().nextInt(Colors.primaries.length)],
      strokeWidth: 7.5,
      coordinates: points
    );
    notifyListeners();
```
А вот этот код не будет рисовать линию:

```dart
    final polyline = objectsList.firstWhere((el) => el.mapId == _pathId) as Polyline;
    objectsList[objectsList.indexOf(polyline)] = polyline.copyWith(
      strokeColor: Colors.blue[700]!,
      strokeWidth: 7.5,
      coordinates: points
    );
    notifyListeners();
```
Как такое могло произойти? Почему это так работает. Объясните пожалуйста!
Неужели, чтобы перерисовать любой объект карты необходимо изменить его параметры визуализации, притом при отсутствии их, ничего не произойдёт? Как мне это обойти, и просто добавлять точки в линию?

**Comment by DCrow** [comment]
Здравствуйте!

Это происходит потому что вы меняете один и тот же `points` объект.
Поэтому при вызове copyWith вы получаете такой же объект Polyline, из-за чего карта не обновляется, так как не видит изменений.

В вашем примере это хорошо иллюстрируется, в первом варианте, вы каждый раз меняете цвет, из-за чего объекты возвращаются разные, а во втором случае, вы используете один и тот же объект points, поэтому и получаете один и тот же polyline.

Момент в том, что points до вызова `add` и points после вызова `add`, являются одним объектом.

В мастере исправил.
