### ISSUE TITLE
Is it going to change app size after publishing to Google play?

### ISSUE THREAD

**Issue by AbbosSaidov** [Unact/yandex_mapkit#226]
After adding this package my apk size has increased almost 60mb. Is it going to change app size after publishing to Google play?

**Comment by iska9der** [comment]
If you publishing your app on google play as appbundle (aab), it will split for various architectures.

If you'll build your apk with --split-per-abi argument, you can see a real size for of each architecture.
`
flutter build apk --release --split-per-abi
`

When i first time added this package, size of my app increased from \~25 to 77\~mb.
https://github.com/Unact/yandex_mapkit/issues/186#issue-1110212778

With --split-per-abi it was \~7 to 20\~mb.

**Comment by DCrow** [comment]
Hello!

Size is mostly dependent on native library size. 
Unfortunately it is impossible to reduce it.
