### ISSUE TITLE
Работа с Polyline

### ISSUE THREAD

**Issue by nikit106** [Unact/yandex_mapkit#227]
Здравствуйте. Подскажите пожалуйста, есть ли сейчас в yandex_mapkit функционал более детальной кастомизации Polyline? Например:
1) Отображать сразу несколько Polyline, чтобы для каждого из них присвоить свой цвет и размер(первый лист с точками будет пройденный маршрут и его надо окрасить одним цветом, второй лист это оставшийся путь и его надо закрасить другим цветом )?
2) Возможность изменять вид линии, не только цвет(например сделать пунктирными).

Заранее благодарю за ответ.

**Comment by DCrow** [comment]
Здравствуйте!

1. Вы можете для YandexMap.mapObjects указать несколько Polyline с разными mapId, таким образом обе линии будут отображены.
2. Пунктирность можно включить через Polyline.dashLength/Polyline.gapLength.
