### ISSUE TITLE
Пропадает pin 

### ISSUE THREAD

**Issue by urusai88** [Unact/yandex_mapkit#231]
Здравствуйте! На картах сама по себе пропадает метка "Я".
<details>
  <summary>Код</summary>

  ```dart
  Future<UserLocationView> _onUserLocationAdded(UserLocationView view) async {
    return view.copyWith(
      accuracyCircle: view.accuracyCircle.copyWith(
        isVisible: false,
        fillColor: Colors.transparent,
        strokeColor: Colors.transparent,
      ),
      arrow: view.arrow.copyWith(
        isVisible: false,
        opacity: 0,
      ),
      pin: view.pin.copyWith(
        // isVisible: true,
        opacity: 1.0,
      ),
    );
  }
  ```
</details>
<details>
  <summary>Видео</summary>

https://user-images.githubusercontent.com/13536462/169974374-f06c930f-22d5-4c41-b46b-4bbc65124f51.mp4

</details>

```
isVisible: true
``` 

не помогает

**Comment by DCrow** [comment]
Добрый день!

Скорее всего в вашем случае, карта решает, что надо отобразить arrow, вместо pin, поэтому вы и не видите ничего.

`isVisible` для объектов UserLocationView управляется самой картой, их изменить нельзя(карта просто проигнорирует это)
