### ISSUE TITLE
Не приходят данные района

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [Unact/yandex_mapkit#235]
Привет! Я почему то не могу найти данные района в методе searchByText. Я живу в Бишкеке. Думал может какие-то параметры надо добавить

**Comment by DCrow** [comment]
Здравствуйте!

Не удается воспроизвести вашу проблему, не могли бы приложить пример? 
Также вы настроили приложение так как в readme указано?

**Comment by tologonkudaiberdiuulu** [comment]
@DCrow на карту Бишкека посмотрите. Если выбрать внутри Бишкека иногда не приходят данные района. У нас есть 
4 района: 
1. Первомайский район
2. Свердловский район
3. Октябрьский район
4. Ленинский район
Я думаю районы тоже должны приходить
