### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by subzero911** [Unact/yandex_mapkit#237]
Иногда при запуске ругается на яндекс.карты

![image](https://user-images.githubusercontent.com/12999702/171429868-d1098833-1564-44f3-8b53-82cf1378e0dd.png)

На работоспособность приложения не влияет, но из-за этого задержка при запуске несколько секунд.
Проверял на Андроиде. Версия пакета 2.0.6.

**Comment by DCrow** [comment]
Здравствуйте!

Тут стоит обратится в [mapkit-android](https://github.com/yandex/mapkit-android-demo). 
Данная либа не имеет контроля над сообщениями в логе.
