### ISSUE TITLE
Is it possible to remove polylines from map after using them. Even in example project can't remove polylines after drawing.

### ISSUE THREAD

**Issue by Isko21** [Unact/yandex_mapkit#238]
<h3>This is the output when I'm trying remove polylines.</h3>
<img src="https://user-images.githubusercontent.com/76448222/171836756-42d5ad0e-4ab5-4062-aeca-176e87b0bbf6.png"></img>

**Comment by suiebay** [comment]
Hello, could you please share with your solution for this problem? I have a same problem too

**Comment by tkas9mbek** [comment]
> Hello, could you please share with your solution for this problem? I have a same problem too

This error occurred in the old version of yandex_mapkit (2.x.x). When the package updated to version 3, we no longer face this problem. So, please, update the package.
