### ISSUE TITLE
Ограничить зону просмотра карты определенной страной или произвольным прямоугольником

### ISSUE THREAD

**Issue by Ilushnik** [Unact/yandex_mapkit#239]
Добрый день.

Возможно ли ограничить работу карты только определенной страной или указать границы при котором пользователю будет запрещено выходить. В примерах такой штуки не нашел и при поиске в доступных методах - тоже.

Нужно что-то вроде [такой](https://yandex.ru/dev/maps/jsbox/2.1/restrict_map_area/) штуки

**Comment by Isko21** [comment]
тоже ищу

**Comment by DCrow** [comment]
Здравсвуйте!

Насколько я знаю нативная либа такого функционала не предоставляет.
