### ISSUE TITLE
Проблема со зуумом

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [Unact/yandex_mapkit#240]
На странице Reverse search example(reverse_search_page в файлах), после зуума, если ещё раз зуумить, то зуум начитается с первого места(т.е с того места где ты при создании задал). Груба говоря не работает зуум. По идее же он должен работать с того места где ты остановился. Попробуйте сделать zoom out 3-4 раза

**Comment by DCrow** [comment]
Здравствуйте!

Что вы подразумеваете под "первого места"?

Метод `YandexMapController.moveCamera` для экземпляра `CameraUpdate.zoomOut`, всегда производит зум с учетом текущего положения камеры(можно посмотреть с помощью `YandexMapController.getCameraPosition`).
Кроме того движение камеры методом `YandexMapController.moveCamera` может и не выполнится. Выполнилось оно или нет определяется результатом этого метода, если камера успешно передвинулась, то вернется true, иначе false.
