### ISSUE TITLE
Дико лагает на m1 симуляторе

### ISSUE THREAD

**Issue by remakerich** [Unact/yandex_mapkit#241]
Установил последнюю версию 3.0

На эмуляторе android вроде все ок
на симуляторе ios arm (m1) дикие лаги и краш после hot restart-а

на реальном ios девайсе все норм... но толку? если ждали под симулятор на m1

**Comment by DCrow** [comment]
Здравствуйте!

А не могли бы приложить лог креша?

**Comment by remakerich** [comment]
ну ок

**Comment by vsly-ru** [comment]
> протестил у себя локально: лаги ушли вот тут надо поставить флаг:
> 
> https://github.com/Unact/yandex_mapkit/blob/9a1979672dc4d74da89d78ada38f59c289a6e553/ios/Classes/YandexMapController.swift#L34
> 
> 
> Есть мак на m1 протестить?

Вы могли бы оформить это исправление как PR 👍

**Comment by DCrow** [comment]
Поменял инициализацию в мастере
