### ISSUE TITLE
iOS не собирается архив и не запускается на iOS 15.5 Xcode 13.4.1

### ISSUE THREAD

**Issue by Zandreks** [Unact/yandex_mapkit#242]
Error (Xcode): In
/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Bin
ding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file
'/ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for
architecture arm64

**Comment by DCrow** [comment]
Дубль #203
