### ISSUE TITLE
Some map objects are not removed from the map when there are many of them

### ISSUE THREAD

**Issue by tkas9mbek** [Unact/yandex_mapkit#250]
In our application, we add lots of map objects to the map, mostly polylines, and when we want to remove all map objects, some of them still remain on the map, although the list given as a parameter is empty.

To check whether the problem is only related to our application, we created a simple test application and the problem occurred here as well. Test application repository: https://github.com/tkas9mbek/yandex_mapkit_test. 

### Steps to reproduce
Add some map objects to the map and try removing them.

You can refer to the video below:

https://user-images.githubusercontent.com/22130883/175514174-7aa1af95-f166-4416-b9f7-79b772df245d.mp4

**Comment by Isko21** [comment]
I have the same problem

**Comment by icanall10** [comment]
У меня тоже есть проблема. При чем она есть и версии 2, и в 3

**Comment by tologonkudaiberdiuulu** [comment]
У меня проблема даже когда объектов только 1. Но это проблема иногда выходит. Я думал это только у меня проблема. Удаляю по id, потом обратно добавляю и в некоторых(редко) случаях не удаляет. А просто добавляет сверху и у меня дубликат выходит

**Comment by Aleksandr123ru** [comment]
У меня тоже есть эта проблема.

**Comment by DCrow** [comment]
Hello!

This should be fixed in 3.0.2
