### ISSUE TITLE
Плейсмарки не отображаются на карте + карта зависает либо теряет взаимодействие после возврата из бэкграунда

### ISSUE THREAD

**Issue by scrinoman** [Unact/yandex_mapkit#253]
Версия 3.0.2

Нашел 2 проблемы в своем проекте, но они воспроизводятся и в exаmple самого плагина:

1) В "Placemark example" при нажатии на любой Add на карте не появляются плейсмарки до тех пор, пока не выполнено любое действие с картой (любые жесты, любые add, любые update). Воспроизводится на всех имеющихся тестовых андроид девайсах
2) Если свернуть приложение с открытой картой, повзаимодействовать с другим приложением и вернуться обратно к карте, то карта либо полностью зависает, либо теряет весь инпут от жестов. Воспроизводится не на всех андроид девайсах

Обеих проблем нет на ios

https://user-images.githubusercontent.com/10988072/176918177-b34b1eb5-504d-40a8-a5a2-97d87425b92c.mp4

**Comment by DCrow** [comment]
Добрый день!

Тут проблема такая же как и в https://github.com/flutter/flutter/issues/103686
Пока что применю такое же решение, что и в https://github.com/flutter/plugins/pull/5787
