### ISSUE TITLE
Some map objects are not removed from the map #250

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [Unact/yandex_mapkit#254]
Это проблема все ещё появляется иногда

**Comment by Aleksandr123ru** [comment]
+1
Проблема полностью не решилась.

**Comment by tologonkudaiberdiuulu** [comment]
@DCrow есть новости?

**Comment by DCrow** [comment]
Добрый день! 

Нужен пример, в котором ошибка воспроизводится, в моих тестах пример указанный в #250 не воспроизводится.

**Comment by tologonkudaiberdiuulu** [comment]
Я вечером(по +6) попробую сделать пример

**Comment by DCrow** [comment]
Закрываю так как нет примера демонстрирующего ошибку.
