### ISSUE TITLE
Некорректное отображение ClusterizedPlacemarkCollection

### ISSUE THREAD

**Issue by OVERENSAL** [Unact/yandex_mapkit#255]
Я пытаюсь добиться отображения двух кластеров. В одном точки города Санкт-Петербург, в другом точки Москвы.
Что хочу получить: при отрисовке карты отображение двух кластеров без приближения (каждый кластер для своего города).
Что происходит: при отрисовке карты не всегда показываются все кластеры, когда то только один кластер, либо в Москве либо в Питере, реже показываются все. Приближая в город, где не отображается кластер при некотором зуме начинают отображаться точки.
Также при Hot Reload на странице, где открыта карта, кластер, который не отображается, появляется.
Возможно я неправильно использую кластеры. Но такого поведения, как на видео явно не должно быть. Прикладываю код и видео. Спасибо

https://user-images.githubusercontent.com/42511187/177558090-27c1c860-2f6a-4238-9b07-537032e9520e.mp4

```
YandexMap(
                mapObjects: widget.points
                    .map( 
                      (points) => ClusterizedPlacemarkCollection(
                        mapId: MapObjectId(points.hashCode.toString()),
                        radius: 30,
                        minZoom: 15,
                        onClusterAdded: (self, cluster) async {
                          return cluster.copyWith(
                            appearance: cluster.appearance.copyWith(
                              opacity: 1,
                              icon: PlacemarkIcon.single(
                                PlacemarkIconStyle(
                                  image: BitmapDescriptor.fromAssetImage(
                                    Assets.components.clinicPin.path,
                                  ),
                                  scale: 2,
                                  anchor: const Offset(0.5, 1),
                                ),
                              ),
                            ),
                          );
                        },
                        placemarks: points
                            .map(
                              (point) => PlacemarkMapObject(
                                mapId: MapObjectId(
                                  point.hashCode.toString(),
                                ),
                                point: Point(
                                  latitude: point.x,
                                  longitude: point.y,
                                ),
                                opacity: 1,
                                icon: PlacemarkIcon.single(
                                  PlacemarkIconStyle(
                                    image: BitmapDescriptor.fromAssetImage(
                                      Assets.components.clinicPin.path,
                                    ),
                                    scale: 2,
                                    anchor: const Offset(0.5, 1),
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    )
                    .toList(),
                onMapCreated: (YandexMapController controller) async {
                  _controller = controller;
                  final visibleRegion = await controller.getVisibleRegion();

                  //TODO: rewrite this hack
                  if (visibleRegion.topLeft == visibleRegion.bottomRight) {
                    return;
                  }

                  // _updateCamera(widget.points, showAnimation: false);
                },
              ),
```

**Comment by tologonkudaiberdiuulu** [comment]
Я думаю это тоже относится к багу #250. Просто объекты не обновляются

**Comment by OVERENSAL** [comment]
У меня 3.0.2 версия, проблема сохраняется

**Comment by DCrow** [comment]
Добрый день! 

Сейчас должно быть исправлено в мастере.

**Comment by OVERENSAL** [comment]
Не поправлено.
На видео продемонстрировал что происходит сейчас. Показываются то оба кластера, то один, то другой, то вообще ни одного. Хотя точки имеются. При хот релоад на карте все кластеры появляются.

https://user-images.githubusercontent.com/42511187/180489052-bd1727a8-bd87-4756-8749-3506f2cffaf7.mp4

**Comment by DCrow** [comment]
Без полноценного примера я не могу сказать в чем ошибка. 
На основе первого коммента, какие ошибки нашел те исправил, вполне возможно ваша ошибка уже является ошибкой нативной либы, в таком случае только разработчики нативной либы могут ее исправить.

Еще, более внимательно посмотрев видео, не используется ли в вашем приложении YandexMap, где логотип "Yandex Maps" передвинут налево?

**Comment by OVERENSAL** [comment]
Логотип "YandexMaps" я сам наложил слева виджетом Stack, ибо на некоторых устройствах не отображается логотип.

**Comment by StrelkovIvan** [comment]
Аналогичная проблема. Некоторые кластеры просто не отображаются
