### ISSUE TITLE
Синие маркеры - плейсхолдеры при загрузке большого количества объектов на карту

### ISSUE THREAD

**Issue by Ilushnik** [Unact/yandex_mapkit#256]
Добрый день.

В моем проекте необходимо отрисовать огромное количество меток за раз (~2000). При добавлении всех объектов в список, появляются синие метки, на нужных координатах, а далее уже  на их месте отрисовываются требуемые маркеры. 
![image](https://user-images.githubusercontent.com/86308077/178552995-a12e7e4a-010c-4642-9ea6-6ffaa0705a34.png)
Пользователю приходится ждать около 20-25 секунд, чтобы все маркеры отрисовались. 

Возможно ли сделать отображение маркеров только после того как они все обработались? Лучше пусть пользователь подождет необходимое количество времени с загрузчиком, чем смотреть на прогружающиеся точки.

**Comment by DCrow** [comment]
Здравствуйте!

Такой возможности нет(отображением точек занимается нативная либа и повлиять на нее нет возможности), сама по себе нативная либа не рассчитывалась на такие объемы.
https://github.com/yandex/mapkit-android-demo/issues/40#issuecomment-433731650

**Comment by ivtimur** [comment]
Такое происходит не только при большом количестве меток, например
