### ISSUE TITLE
Карта неточно фокусируется на плейсмарках

### ISSUE THREAD

**Issue by subzero911** [Unact/yandex_mapkit#259]
Вот код.
```dart
    final MapAnimation? animation = MapAnimation(duration: 0.5, type: MapAnimationType.linear);

    if (points.length == 1) {
      await mapController.moveCamera(
        CameraUpdate.newCameraPosition(
          CameraPosition(
            target: Point(
              latitude: points.first.latitude,
              longitude: points.first.longitude,
            ),
          ),
        ),
        animation: animation,
      );
```
Ожидаемый результат: камера наезжает на точку, и точка оказывается по центру карты.
Фактический результат: точка оказывается не по центру, а иногда и вообще не попадает в камеру.

https://user-images.githubusercontent.com/12999702/180820569-85a53915-c986-4016-8a94-462d283bbff8.mp4

Предполагаю, что причиной этому является баг в самих картах. Возможно, происходит округление координат (слишком грубое), и из-за этого камера нацеливается мимо точки.

**Comment by DCrow** [comment]
Здравствуйте!

Просьба приложить полноценный пример, демонстрирующий данную ошибку. 
На данный момент я не вижу никаких связанных проблем в библиотеке.

Также не используется ли в проекте YandexMap.focusRect? так как он влияет на расчет центра карты для камеры.

**Comment by DCrow** [comment]
Закрываю так как небыло ответа на предыдущий вопрос.
