### ISSUE TITLE
ошибка компиляции для iOS (симулятор и реальный девайс) после обновления пакета

### ISSUE THREAD

**Issue by FeofanGreek** [Unact/yandex_mapkit#260]
Прошу помочь разобраться, использую версию yandex_mapkit: ^3.0.3

[!] CocoaPods could not find compatible versions for pod "YandexMapsMobile":
      In snapshot (Podfile.lock):
        YandexMapsMobile (= 4.0.0-full)

      In Podfile:
        yandex_mapkit (from .symlinks/plugins/yandex_mapkit/ios) was resolved to 0.0.1, which depends on
          YandexMapsMobile (= 4.1.0-full)

    You have either:
     * out-of-date source repos which you can update with pod repo update or with pod install --repo-update.
     * changed the constraints of dependency YandexMapsMobile inside your development pod yandex_mapkit.
       You should run pod update YandexMapsMobile to apply changes you've made.

**Comment by buzzySmile** [comment]
- remove Podfile.lock
- run `pod install` again

**Comment by DCrow** [comment]
Здравствуйте!

Тут решение либо так как говорит коммент
>  * out-of-date source repos which you can update with pod repo update or with pod install --repo-update.

Либо как @buzzySmile

**Comment by cup-of-Aygiz** [comment]
Если используете Mac m1 то надо запустить через `arch -x86_64 pod install`

**Comment by iksent** [comment]
> Если используете Mac m1 то надо запустить через `arch -x86_64 pod install`

Что делать, если команда просто зависает? VPN не помог.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/32956521/236670458-a4261e51-1a17-461b-92df-699efb24ab69.png">

**Comment by iksent** [comment]
> Что делать, если команда просто зависает? VPN не помог.

Отбой: нужно было дольше ждать (1-2 минуты)
