### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by a-reznic** [Unact/yandex_mapkit#262]
version 3.0.3

D/yandex.maps.runtime( 7750): Java object is already finalized. Nothing to do.
W/yandex.maps( 7750): yandex::maps::mapkit::tiles::MemoryCache::clear: Clearing cache
F/libc    ( 7750): Fatal signal 11 (SIGSEGV), code -6 (SI_TKILL) in tid 7750 (xx.group), pid 7750 (xx.group)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_phone_arm64/emulator_arm64:11/RSR1.210722.012/7758210:userdebug/test-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-08-16 16:34:15+0300
pid: 7750, tid: 7750, name: xx.group  >>> xx.group <<<
uid: 10132
signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr --------
x0  b4000075c9008260  x1  000000770f5f14f8  x2  00000073f6c8e5dc  x3  0000000000000001
x4  000000007003c350  x5  0000007ffdd77fb8  x6  0000000000000000  x7  0000000000000000
x8  0000007ffdd77f88  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
x12 0000000000000000  x13 0000000000000000  x14 001a356ec2110800  x15 0000000000000007
x16 00000073f7eb8158  x17 00000077096f695c  x18 000000770eaca000  x19 b400007558e08c80
x20 000000770e39f000  x21 0000000000000001  x22 0000000013700090  x23 b400007498ec5b60
x24 0000000000000001  x25 0000000000000001  x26 0000000000000001  x27 000000007102cb40
x28 0000000000000000  x29 0000000000000000
lr  00000073f6c8c54c  sp  0000007ffdd77f80  pc  0000000000000000  pst 0000000020001000
backtrace:
#00 pc 0000000000000000  <unknown>
#01 pc 0000000002247548  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#02 pc 0000000001c3ef4c  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#03 pc 0000000001a5074c  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#04 pc 0000000001a506ec  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#05 pc 0000000001a4fd14  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#06 pc 0000000001a40ee4  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (BuildId: 0a8150a6ef617932)
#07 pc 0000000001a29590  /data/app/~~EBeBdZIdTrqYTFpE8eiCsw==/xx.group-QQmDmbBYcL0JVX1UzgeOCw==/base.apk!libmaps-mobile.so (offset 0x2258000) (Java_com_yandex_runtime_internal_Scheduler_run+36) (BuildId: 0a8150a6ef617932)
#08 pc 0000000002037a78  /memfd:jit-cache (deleted) (offset 0x2000000) (art_jni_trampoline+152)
#09 pc 00000000020136f8  /memfd:jit-cache (deleted) (offset 0x2000000) (com.yandex.runtime.internal.Scheduler.handleMessage+104)
#10 pc 000000000201b258  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.Handler.dispatchMessage+168)
#11 pc 0000000002038280  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.Looper.loop+1328)
#12 pc 000000000013387c  /apex/com.android.art/lib64/libart.so (art_quick_osr_stub+60) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#13 pc 000000000033d108  /apex/com.android.art/lib64/libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*)+344) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#14 pc 000000000068ae84  /apex/com.android.art/lib64/libart.so (MterpMaybeDoOnStackReplacement+208) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#15 pc 0000000000132350  /apex/com.android.art/lib64/libart.so (MterpHelpers+240) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#16 pc 0000000000397020  /system/framework/framework.jar (offset 0x92b000) (android.os.Looper.loop+1084)
#17 pc 0000000000305c58  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+268) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#18 pc 000000000030dc48  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#19 pc 000000000030f030  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1772) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#20 pc 0000000000177f40  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+57848) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#21 pc 000000000013f7d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#22 pc 00000000001a180c  /system/framework/framework.jar (android.app.ActivityThread.main)
#23 pc 0000000000305d60  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+532) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#24 pc 000000000066b1fc  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#25 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#26 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#27 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#28 pc 00000000005556f8  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#29 pc 00000000004d4f04  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#30 pc 00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 13577ce71153c228ecf0eb73fc39f45010d487f8)
#31 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#32 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#33 pc 0000000000318330  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#34 pc 000000000030e65c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#35 pc 000000000067c4f4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#36 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#37 pc 0000000000449626  /system/framework/framework.jar (offset 0x125d000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
#38 pc 0000000000305c58  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+268) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#39 pc 000000000066b1fc  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#40 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#41 pc 0000000000897608  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2280) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
#42 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#43 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#44 pc 0000000000554134  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#45 pc 00000000005545e8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#46 pc 0000000000438b1c  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+656) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
#47 pc 0000000000099424  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: dc13c3ae89f2044ec9e55326de275210)
#48 pc 00000000000a08b0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836) (BuildId: dc13c3ae89f2044ec9e55326de275210)
#49 pc 0000000000003580  /system/bin/app_process64 (main+1336) (BuildId: 3254c0fd94c1b04edc39169c6c635aac)
#50 pc 0000000000049418  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: ac8f7173c886715a2f2fec67246e21da)

**Comment by DCrow** [comment]
Добрый день!

Подскажите при каких обстоятельствах у вас появляется данный креш?

**Comment by a-reznic** [comment]
на эмуляторе запускал карты

**Comment by DCrow** [comment]
Просьба приложить кусок кода при выполнении, которого произошел креш

**Comment by DCrow** [comment]
Закрываю так как нет ответа на предыдущий вопрос.
