### ISSUE TITLE
Как поменять цвет маркера 

### ISSUE THREAD

**Issue by cup-of-Aygiz** [Unact/yandex_mapkit#264]
Приходит несколько объектов, в которых указан цвет маркера. Но не могу найти где его поменять в PlacemarkIcon. 
В PlacemarkIconStyle и BitmapDescriptor такой возможности тоже нет

**Comment by DCrow** [comment]
Добрый день!

`PlacemarkIcon` не дает возможности менять внешний вид передаваемого `BitmapDescriptor`.
