### ISSUE TITLE
Отсутствует BoundingBoxHelper

### ISSUE THREAD

**Issue by IncM** [Unact/yandex_mapkit#265]
Невозможно получить BoundingBox по списку точек (Point). Хотя в самом KIT'е есть класс BoundingBoxHelper ([документация](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/geometry/BoundingBoxHelper.html)), преназначенный для этого.
Это нужно, например, для центрирования камеры по всем точкам на карте

```dart
YandexMap(
  mapObjects: _mapObjects,
  mapType: MapType.vector,
  onMapCreated: (YandexMapController yandexMapController) async {
    _controller = yandexMapController;
    await _load();
    _controller.moveCamera(
      CameraUpdate.newBounds(
         BoundingBox(
           northEast: northEast, //  Как его получить по всем точкам?
           southWest: southWest, //  Как его получить по всем точкам?
         ),
      ),
    );
  },
)
```

**Comment by DCrow** [comment]
Дубль #163
