### ISSUE TITLE
Вопрос по методу onTap() класса MapObjectCollection

### ISSUE THREAD

**Issue by Arthur-Zaripov** [Unact/yandex_mapkit#268]
Здравствуйте! Вопрос по методу onTap класса MapObjectCollection.
` onTap: (MapObjectCollection self, Point point) => print('Tapped me at $point'),`
Данный метод каждый возвращает разный point. Так и должно быть?  Нажимаю же на один и тот же mapObjects. Почему координаты всегда разные?

**Comment by DCrow** [comment]
Добрый день!

Да, так и должно быть. Всегда возвращается точка карты на которую пользователь нажал. 
Само отображение объекта `MapObject` на карте занимает некоторое пространство точек, при нажатии возвращается одна из точек.
