### ISSUE TITLE
examples/user_layer_page invalid offset constructor

### ISSUE THREAD

**Issue by ivanbogomoloff** [Unact/yandex_mapkit#274]
Привет.

В примерах ошибка перепутаны местами width, height

https://github.com/Unact/yandex_mapkit/blob/master/example/lib/examples/user_layer_page.dart#L86

Должно быть 

```dart
anchor: UserLocationAnchor(
    course: Offset(0.5 * width , 0.5 * height), 
    normal: Offset(0.5 * width, 0.5 * height) 
)
```

**Comment by DCrow** [comment]
Здравствуйте! 

Спасибо, действительно не верно было указано в примере.
Поправил в мастере.
