### ISSUE TITLE
iOS ошибка метода onCameraPositionChanged

### ISSUE THREAD

**Issue by pogrammist** [Unact/yandex_mapkit#277]
iOS
flutter: 2.10.5
yandex_mapkit: 3.1.1
Ошибка метода onCameraPositionChanged.
При первом запуске карты, метод вызывается с "левыми" координатами:
Point(latitude: 55.25866066312835, longitude: 90.0)
<img width="837" alt="Снимок экрана 2022-10-11 в 03 29 37" src="https://user-images.githubusercontent.com/10690719/194961744-8c6a65ac-ec10-41f9-a700-4d2ae24cbebc.png">

**Comment by mozerrr** [comment]
Дополню: Проблема повторяется только на ios и при "вторичной" инициализации (`weak var weakSelf = self`). После инициализации срабатывает weakSelf?.handle, который вызывает moveCamera -> а он уже onCameraPositionChanged . На андроид такого не происходит.

**Comment by DCrow** [comment]
Доброе утро!

Не совсем понимаю, что такое "левые" координаты?

**Comment by mozerrr** [comment]
При запуске ios версии мапкит, от контроллера приходит координата с причиной application.
На android mapkit такого поведения не наблюдается. Хотелось бы консистентности, либо в обоих случаях приходит, либо не приходит.

**Comment by DCrow** [comment]
В текущей версии приложения данную проблему не наблюдаю.
