### ISSUE TITLE
zIndex не работает для UserLocationView

### ISSUE THREAD

**Issue by alexanderkind** [Unact/yandex_mapkit#278]
Добрый день!
Не меняется положение маркера пользователя (userLocationView) по отношению к другим маркерам (mapObjects).
Маркеру пользователя (userLocationView) устанавливается zIndex меньше, чем у других (mapObjects), но он всегда перекрывает их.
Я что-то делаю не так?

Изменение zIndex иконки не даёт результата.
```
final _userPlacemarkIcon = PlacemarkIcon.single(PlacemarkIconStyle(
    image: BitmapDescriptor.fromAssetImage(Assets.imYourMapMarker),
    zIndex: 1,
));
```
Изменение zIndex у экземпляра userLocationView - тоже.
```
var newView = view.copyWith(
  pin: view.pin.copyWith(opacity: 1, icon: _userPlacemarkIcon, zIndex: 1,),
  arrow: view.arrow.copyWith(opacity: 1, icon: _userPlacemarkIcon, zIndex: 1,),
  accuracyCircle:view.accuracyCircle.copyWith(
    fillColor: ThemeColors.baseColor.withOpacity(0.25),
    strokeColor: ThemeColors.baseColor,
  ),
);
```

Я неправильно использую zIndex?

Flutter doctor
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.2006], locale ru-RU)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.1)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```
![image](https://user-images.githubusercontent.com/67633406/195342407-bac723e5-52d7-40f3-ad3b-2f459f2ddae1.png)
![image](https://user-images.githubusercontent.com/67633406/195342452-d88b1111-7844-4ee2-be68-49df95194404.png)

**Comment by DCrow** [comment]
Здравствуйте!

Тут такая же проблема описанная в https://github.com/yandex/mapkit-ios-demo/issues/139
Похоже что иконки для отображения местоположения пользователя реагируют только на изменение изображения иконки

**Comment by DCrow** [comment]
В текущей версии(4.5.1) не воспроизводится.

**Comment by Sarexer** [comment]
@DCrow Здравствуйте. Как будто в последней версии плагина воспроизводится и на индроид и на ios. Какой бы z индекс не ставил пину местоположения, он никак не хочет оказываться под остальными объектами. При этом z индекс у остальных объектов работает как и должно.

flutter: yandex_mapkit: 4.1.0
android: 'com.yandex.android:maps.mobile:4.5.1-full'
ios: YandexMapsMobile (= 4.6.1-full)


`import 'package:flutter/material.dart';
import 'package:yandex_mapkit/yandex_mapkit.dart';

class YandexMapUserPinZindex extends StatelessWidget {
  const YandexMapUserPinZindex({super.key});

  final point = const Point(latitude: 55.7007, longitude: 37.6317);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: YandexMap(
        mapObjects: [
          CircleMapObject(
            zIndex: 2,
            mapId: const MapObjectId('circle1'),
            circle: Circle(
              center: point,
              radius: 1000,
            ),
          ),
          CircleMapObject(
            zIndex: 3,
            mapId: const MapObjectId('circle2'),
            fillColor: Colors.red,
            circle: Circle(
              center: point,
              radius: 400,
            ),
          ),
        ],
        onMapCreated: (controller) async {
          await controller.toggleUserLayer(
            visible: true,
          );
        },
        onUserLocationAdded: (view) async {
          return view.copyWith(
            pin: view.pin.copyWith(zIndex: 1, opacity: 1),
            arrow: view.arrow.copyWith(zIndex: 1, opacity: 1,),
          );
        },
      ),
    );
  }
}`

<img width="404" alt="image" src="https://github.com/user-attachments/assets/d5b088e3-03e6-4de8-a689-bac8c50753b2">
