### ISSUE TITLE
При восстановлении приложения после его убийства системой (при недостаче оперативной памяти) не работают жесты по карте

### ISSUE THREAD

**Issue by IncM** [Unact/yandex_mapkit#282]
Алгоритм воспроизведения такой:
1. Открываем экран приложения с картой
2. Сворачиваем приложение в фон
3. Включаем много разных программ
4. Система выгружает из памяти наше приложение
5. Из списка запущенных программ открываем своё приложение
6. Скролить и зумить карту больше не получается (пока не уйти с экрана и не вернуться обратно)
При этом при попытках скролить/зумить карту в консоль сыпится большое количество сообщений
`W/OpenGLRenderer(14655): The surface had destroyed before draw`

Версия yandex_mapkit: 3.1.1

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel release, 3.1.0, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale ru_RU.UTF-8)
    • Flutter version 3.1.0 at /mnt/hdd/dev-env/flutter-3.1.0
    • Upstream repository unknown
    • Framework revision bcea432bce (5 месяцев назад), 2022-05-26 09:05:34 -0700
    • Engine revision 44e5b38ee8
    • Dart version 2.18.0 (build 2.18.0-44.1.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /mnt/hdd/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /mnt/hdd/Android/sdk
    • Java binary at: /home/xxx/JetBrains/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/xxx/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/xxx/JetBrains/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • Mi 9T (mobile)  • xxx • android-arm64  • Android 11 (API 30)
    • Linux (desktop) • linux    • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)    • chrome   • web-javascript • Chromium 106.0.5249.91 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by DCrow** [comment]
Здравствуйте!

Это очень похоже на https://github.com/flutter/flutter/issues/103870
На 3.3.6 ваша ошибка воспроизводится?
