### ISSUE TITLE
Как подавить мусор, идущий в консоль?

### ISSUE THREAD

**Issue by subzero911** [Unact/yandex_mapkit#283]
Консоль без конца засоряется вот такими бессмысленными сообщениями
![image](https://user-images.githubusercontent.com/12999702/196029523-233fe821-6aaa-42d5-b3ba-57dbf7fcfbb0.png)
![image](https://user-images.githubusercontent.com/12999702/196029536-187dbcab-099f-4e34-858a-a3641d3e9c59.png)
Из-за этого невозможно найти полезные логи в консоли.
Сделайте флажок, чтобы отключить сообщения из плагина.

**Comment by DCrow** [comment]
Здравствуйте!

Кроме как https://github.com/Unact/yandex_mapkit/issues/72#issuecomment-726193784 больше никак
