### ISSUE TITLE
YandexMapController was used after being disposed

### ISSUE THREAD

**Issue by Ramazon-dev** [Unact/yandex_mapkit#286]
when i try to close YandexMapKit Page while disposing YandexMapController get this error:

Unhandled Exception: A YandexMapController was used after being disposed.
E/flutter (10961): Once you have called dispose() on a YandexMapController, it can no longer be used.

```
import 'package:yandex_mapkit/yandex_mapkit.dart';

class AnotherMap extends StatefulWidget {
  const AnotherMap({super.key});

  @override
  State<AnotherMap> createState() => _AnotherMapState();
}

class _AnotherMapState extends State<AnotherMap> {
  YandexMapController? yandexMapController;

  @override
  void dispose() {
    yandexMapController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: YandexMap(
        onMapCreated: (controller) {
          yandexMapController = controller;
          yandexMapController?.moveCamera(
            animation: const MapAnimation(
              duration: 0.5,
            ),
            CameraUpdate.newCameraPosition(
              const CameraPosition(
                zoom: 11,
                target: Point(
                  latitude: 42,
                  longitude: 70,
                ),
              ),
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          yandexMapController?.moveCamera(
            animation: const MapAnimation(
              duration: 0.5,
            ),
            CameraUpdate.newCameraPosition(
              const CameraPosition(
                zoom: 11,
                target: Point(
                  latitude: 41,
                  longitude: 69,
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
```

**Comment by Isko21** [comment]
try just removing the dispose method, I think it will work fine

**Comment by pvlKryu** [comment]
You do not have to dispose Yandex Map controller as it disposes automatically.

**Comment by dumptyhumpty2014gmail** [comment]
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: A YandexMapController was used after being disposed.
Once you have called dispose() on a YandexMapController, it can no longer be used.
       at ChangeNotifier.debugAssertNotDisposed.<fn>(change_notifier.dart:179)
       at ChangeNotifier.debugAssertNotDisposed(change_notifier.dart:186)
       at ChangeNotifier.dispose(change_notifier.dart:345)
       at _YandexMapState.dispose(yandex_map.dart:164)

**Comment by DCrow** [comment]
You don't need to use `YandexMapController.dispose()`. It's automatically disposed by the view.
