### ISSUE TITLE
Экран с картами иногда становится черным (Android)

### ISSUE THREAD

**Issue by subzero911** [Unact/yandex_mapkit#287]
Если свернуть приложение, подождать какое-то время, и развернуть, карта иногда становится черной, и невозможно вернуть её.
Предполагаю, что система каким-то образом убивает фоновый поток, в котором рендерится карта.
Также сообщали, что при следующей последовательности действий, карта становится черной:
- открыть приложение с картами
- сделать скриншот
- свернуть его
- перейти в любое другое приложение
- вернуться на наше приложение

https://user-images.githubusercontent.com/12999702/199721622-636302c0-440b-4235-800f-1a2f76c57cd9.mp4

Воспроизводится на устройствах с оболочкой MiUI: Redmi Note 8 Pro, XiaoMi Mi 11 Lite.

**Comment by DCrow** [comment]
Добрый день!

Тут похоже такая же проблема что и в https://github.com/flutter/flutter/issues/98865
Ждем когда исправят в engine.

**Comment by DCrow** [comment]
В текущей версии флаттера(3.19) не воспроизводится
