### ISSUE TITLE
Установка ключа карт и реинициализация

### ISSUE THREAD

**Issue by ProstoCesar** [Unact/yandex_mapkit#288]
Доброго времени суток!
Прошу добавить в функционал разрабатываемой библиотеки установку ключа Яндекс карт не только во время конфигурации приложения, но и во время его работы. Так как возникла необходимость не жестко зашивать ключ (который "протухает" через год) в приложение, а получать его с сервера.

**Comment by DCrow** [comment]
Здравствуйте! К сожалению нативная либа Яндекс такое не позволяет делать. 
Можете обратиться в https://github.com/yandex/mapkit-ios-demo или https://github.com/yandex/mapkit-android-demo 
Возможно разработчики нативной либы добавят такой функционал, и тогда его можно будет добавить сюда.
