### ISSUE TITLE
Крашится на ios при тапе на маркер

### ISSUE THREAD

**Issue by bondsy777** [Unact/yandex_mapkit#289]
*** Assertion failure in -[YMKCluster appearance], YMKCluster_Binding.mm:102
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Native object's weak_ptr for N6yandex4maps6mapkit3map7ClusterE has expired
Exception stack trace (top 20 entries):
0   Runner                              0x00000001030222a8 _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev + 76
1   Runner                              0x0000000103027c0c _ZN6yandex4maps7runtime9Exception4Impl7captureEv + 32
2   Runner                              0x0000000103027b80 _ZN6yandex4maps7runtime9ExceptionC2ERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS2_8SeverityE + 124
3   Runner                              0x000000010399a34c _ZN6yandex4maps7runtime3ios7weakGetINS0_6mapkit3map7ClusterEEENSt3__110shared_ptrIT_EERKNS7_8weak_ptrIS9_EE + 148
4   Runner                              0x000000010399b2f8 -[YMKCluster appearance] + 56
5   Runner                              0x0000000104a53edc $s13yandex_mapkit40ClusterizedPlacemarkCollectionControllerC14onClusterAdded4withySo10YMKClusterC_tFyypSgcfU0_ + 796
6   Runner                              0x0000000104a54124 $sypSgIegn_yXlSgIeyBy_TR + 160
7   Flutter                             0x000000010cc1b184 _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter29PlatformMessageResponseDarwin8CompleteENS_10unique_ptrINS2_7MappingENS_14default_deleteIS8_EEEEE3$_0EENS_9allocatorISD_EEFvvEEclEv + 116
8   Flutter                             0x000000010cece3d0 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1636
9   Flutter                             0x000000010ced1ebc _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
10  CoreFoundation                      0x00000001b5f72678 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 714360
11  CoreFoundation                      0x00000001b5ef6654 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 206420
12  CoreFoundation                      0x00000001b5ef0e00 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 183808
13  CoreFoundation                      0x00000001b5ecf4b0 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 46256
14  CoreFoundation                      0x00000001b5ee2bc8 CFRunLoopRunSpecific + 600
15  GraphicsServices                    0x00000001d204d374 GSEventRunModal + 164
16  UIKitCore                           0x00000001b8856b58 137A95AA-DA6D-332C-BC01-E13BB9B6E317 + 5327704
17  UIKitCore                           0x00000001b85d8090 UIApplicationMain + 364
18  Runner                              0x0000000102402d30 main + 64
19  dyld                                0x000000010965dda4 start + 520
'
*** First throw call stack:
(0x1b5f5d288 0x1cec8c744 0x1b77ee340 0x10399b5b4 0x104a53edc 0x104a54124 0x10cc1b184 0x10cece3d0 0x10ced1ebc 0x1b5f72678 0x1b5ef6654 0x1b5ef0e00 0x1b5ecf4b0 0x1b5ee2bc8 0x1d204d374 0x1b8856b58 0x1b85d8090 0x102402d30 0x10965dda4)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ed9ffb38 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1ed9ffb38 <+8>:  b.lo   0x1ed9ffb58               ; <+40>
    0x1ed9ffb3c <+12>: pacibsp
    0x1ed9ffb40 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1ed9ffb44 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by DCrow** [comment]
Здравствуйте!

Должно быть исправлено в новой версии.
