### ISSUE TITLE
Не отображаются плейсмарки с кастомной иконкой при obfuscate

### ISSUE THREAD

**Issue by castletaste** [Unact/yandex_mapkit#292]
Проблема уже была частично описана #219

При `flutter build apk/ipa` проблема отсутствует, 
но `flutter build apk/ipa --obfuscate` воспроизводит проблему. 

Думаю проблема находится на стыке нативных imageProvider'ов и flutter, как решение предлагаю использовать встроенные во flutter imageProvider, так при передаче asset'а не будет возникать данных проблем

**Comment by castletaste** [comment]
![image](https://user-images.githubusercontent.com/74972418/202478241-ca7a884c-026f-4dac-901d-c56c455ef12e.png)
![image](https://user-images.githubusercontent.com/74972418/202478290-8b3a4cbf-1080-4108-9043-601eeed125c3.png)

**Comment by Likhachev17** [comment]
Пните как появится решение, тоже полетели иконки

**Comment by DCrow** [comment]
Здравствуйте!

Это до сих пор проблема нативной либы. Даже если не указывать иконку для метки, на карте должна отображаться дефолтная метка, но при обфускации даже она не отображается.

**Comment by weter120** [comment]
@DCrow, похоже что проблема с иконками возникает из-за того, что в методах `_createJson`, `_updateJson` и `_removeJson` у всех `MapObject` в `type` передается `runtimeType.toString()`, и при обфускации названия этих Dart классов могут быть рандомные, нужно передавать в `type` названия классов просто строкой.

![code](https://github.com/Unact/yandex_mapkit/assets/27557517/7ce4a30c-9dc7-4c1f-ad3b-2b58adb37c49)

**Comment by DCrow** [comment]
@weter120 Да, действительно как вы говорили, не думал что runtimeType будет меняться.
Исправил в новой версии.

**Comment by yasha-runner** [comment]
@DCrow  @castletaste  Добрый день, подскажите пожалуйста, нашлось ли какое то решение?
Ошибка повторяется, при дебаге иконки отображаются окей, при релизе картинки в иконках пропадают
![photo_2024-02-13_21-42-24](https://github.com/Unact/yandex_mapkit/assets/41083266/56dc5eea-7022-44ba-8b16-8cd42b1ce91d)
![photo_2024-02-13_21-42-28](https://github.com/Unact/yandex_mapkit/assets/41083266/ebccf0f7-e047-428c-848c-391e3baa9959)
