### ISSUE TITLE
На некоторых устройствах невозможно зумить карту в onMapCreated()

### ISSUE THREAD

**Issue by OVERENSAL** [Unact/yandex_mapkit#294]
Когда я вызываю controller.moveCamera() вылетает приложение. Погуглив нашел обходное решение 
`final visibleRegion = await controller.getVisibleRegion();
if (visibleRegion.topLeft == visibleRegion.bottomRight) {
    return;
}`
Теперь приложение не вылетает при открытии карты, но проблема данного решения в том, что карту нельзя зазумить автоматически.
Встречалось это на Iphone 13 pro

**Comment by DCrow** [comment]
Здравствуйте!

Должно быть исправлено в новой версии.
