### ISSUE TITLE
Is it posible to move mapobjects ?

### ISSUE THREAD

**Issue by AbbosSaidov** [Unact/yandex_mapkit#296]
I want to do some animation . For this animation I need to move some mapobjects. Or if you have better solution for creating an animation with mapobjects ,can you help me with that. I could not find anything about creating animation in yandex map.

**Comment by DCrow** [comment]
Hello!

Do you need an animated `MapObject`? Or do you need to animate `MapObject` movement on map?

**Comment by AbbosSaidov** [comment]
I need animate MapObject movement on map

**Comment by DCrow** [comment]
Unfortunately this functionality is not implemented in the native library.
