### ISSUE TITLE
Не подтягиваются зависимости на iOS

### ISSUE THREAD

**Issue by makwin123** [Unact/yandex_mapkit#298]
При попытке выполнить команду pod install получаю ошибку

[!] CocoaPods could not find compatible versions for pod "yandex_mapkit":
  In Podfile:
    yandex_mapkit (from `.symlinks/plugins/yandex_mapkit/ios`)

Specs satisfying the `yandex_mapkit (from `.symlinks/plugins/yandex_mapkit/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by TyM6JIep** [comment]
Помогла установка версии platform :ios, '12.0'
