### ISSUE TITLE
Карта не отображается

### ISSUE THREAD

**Issue by han-tm** [Unact/yandex_mapkit#299]
Ребята, подскажите, в чем может быть проблема в отображении карты?

Вместо карты показывается квадраты. Явных ошибок в консоли нет. Все что есть указал внизу.

Отображение:
![image](https://user-images.githubusercontent.com/85815609/212960538-6d8c80ac-a237-4de4-b387-db075b19639d.png)

Код с консоли:
![image](https://user-images.githubusercontent.com/85815609/212960312-36682293-cedf-4e5e-8bab-df1e8a258bef.png)

Мой MainActivity.kt
`package com.example.yandex_map_test

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import com.yandex.mapkit.MapKitFactory

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    MapKitFactory.setLocale("ru_RU") // Your preferred language. Not required, defaults to system language
    MapKitFactory.setApiKey("API KEY") // Your generated API key
    super.configureFlutterEngine(flutterEngine)
  }
}`

Также добавил в build.gradle:
`dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.yandex.android:maps.mobile:4.2.2-full'
}`

**Comment by Me262a** [comment]
Такое обычно происходит, когда АПИ ключ неправильный.

**Comment by DCrow** [comment]
Доброе утро! 
Такое бывает в случае когда ключ не активный. 
Тут стоит обратиться в тех. поддержку яндекса для активации, либо подождать(если ключ только что сгенерили).
