### ISSUE TITLE
Drag placemark

### ISSUE THREAD

**Issue by Ilya-Vys** [Unact/yandex_mapkit#302]
Подскажите почему маркер не становится draggable. 
isDraggable: true, consumeTapEvents: true сделал.
Ни onDrag, ни onDragstart ни onDragEnd не реагируют.
Реагирует только onTap.
Просто карта тянется а не маркер.

**Comment by subzero911** [comment]
Этот пакет, похоже, заброшен авторами.
Спросите сюда https://pub.dev/packages/yandex_mapkit_community
Тут чуваки активно фиксят баги и поддерживают.

**Comment by DCrow** [comment]
Добрый день!

Просьба приложить пример. 
Также стоит обратить куда производится тап(зона в которой регистрируется drag может отличаться от отображения `PlacemarkMapObject` на карте) и как долго(требуется чуть больше чем `YandexMap.onMapLongTap` для карты)
