### ISSUE TITLE
app crashes on controller.toggleUserLayer(visible: true)

### ISSUE THREAD

**Issue by assanbayev** [Unact/yandex_mapkit#303]
I wanted to add user location on map but whenever I run app crashes on controller.toggleUserLayer(visible: true) this function app crashes. If visible is false app does not crash. 

Android 13, samsung. Havent tested on IOS.

flutter doctor:
Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2604], locale ru-RU)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

I wanted to add user location on map with user heading direction shown as arrow or someting. Any help appreciated.

**Comment by isshort** [comment]
same issue

**Comment by DCrow** [comment]
Hello!

Please also include the full error message, and if possible a reproducible example.
