### ISSUE TITLE
Утечка памяти _YandexMapState

### ISSUE THREAD

**Issue by r-i-c-o** [Unact/yandex_mapkit#307]
Объекты YandexMapController и _YandexMapState не удаляются из памяти при удалении YandexMap виджета из дерева, тем самым вызывая утечку памяти. Воспроизводится даже с пустым конструктором YandexMap(), без параметров. 
Версия yandex_mapkit 3.2.0
Flutter 3.7.3

Скриншоты из Memory Profiler 
![image](https://user-images.githubusercontent.com/54285735/234596353-5b60957d-9d9e-44a0-984b-af18e03a74ed.png)
![image](https://user-images.githubusercontent.com/54285735/234599154-f43859f1-8bd1-4edf-bd70-e518a60be233.png)

**Comment by subzero911** [comment]
Супер, может, предложите исправление в  https://pub.dev/packages/yandex_mapkit_community ?
Этот пакет, похоже, заброшен, поэтому делаем коммьюнити-версию.

**Comment by subzero911** [comment]
@r-i-c-o супер, может, предложите исправление в  https://pub.dev/packages/yandex_mapkit_community ?
Этот пакет, похоже, заброшен, поэтому делаем коммьюнити-версию.

**Comment by DCrow** [comment]
Merged and fixed in 3.3.0
