### ISSUE TITLE
andex::maps::runtime::vulkan::BufferPool::allocate <warn>: Buffer pool: [Styles ubo allocator] increased, new size: 256 kb

### ISSUE THREAD

**Issue by bakhanets** [Unact/yandex_mapkit#309]

**Comment by bakhanets** [comment]
yandex::maps::runtime::vulkan::BufferPool::allocate <warn>: Buffer pool: [Styles ubo allocator] increased, new size: 256 kb

Ошибка возникает в runtime, использую последнюю версию библиотеки и flutter 3.3.10

**Comment by subzero911** [comment]
попробуйте сюда написать https://pub.dev/packages/yandex_mapkit_community 
возможно, тут уже пофиксили или исправят оперативно

**Comment by DCrow** [comment]
Добрый день!

warn сообщения идут из нативной либы, и по словам разработчиков нативных либ нужны для debug целей, выключить их, к сожалению нельзя.
