### ISSUE TITLE
Не отображается логотип в релизной версии приложения (Android)

### ISSUE THREAD

**Issue by Legendorik** [Unact/yandex_mapkit#311]
Закрытая issue https://github.com/Unact/yandex_mapkit/issues/154

Сейчас ситуация изменилась, судя по https://github.com/yandex/mapkit-android-demo/issues/132#issuecomment-1360904486
Проблема должна быть исправлена со стороны нативной либы (последняя версия там 4.3.1). Можно ли перенести эти правки сюда? Просто модификация версии в dependencies в .gradle к сожалению что-то ломает

**Comment by subzero911** [comment]
Этот пакет, похоже, заброшен авторами.
Спросите сюда https://pub.dev/packages/yandex_mapkit_community
Тут чуваки активно фиксят баги и поддерживают.

**Comment by DCrow** [comment]
Доброе утро!

Нативная либа была обновлена до 4.3.2
