### ISSUE TITLE
не смотря на то что метод toggleUserLayer является асинхронным, методы идущие после него вызываются моментально

### ISSUE THREAD

**Issue by Kizat** [Unact/yandex_mapkit#313]

**Comment by subzero911** [comment]
заэвэйтить пробовали?
то, что асинхронный, само по себе не значит, что код на этом месте остановится

**Comment by DCrow** [comment]
Добрый день!

Просьба приложить пример использования.

**Comment by Kizat** [comment]
то есть если я вызываю метод toggleUserLayer , а затем в методе then пропишу какой нибудь метод, то метод внутри then срабатывает не дожидаясь завершения метода toggleUserLayer

**Comment by DCrow** [comment]
Что вы подразумеваете под "завершением метода toggleUserLayer"? Отображение юзера на карте? Метод только позволяет либе яндекса отображать юзера, но не гарантирует что юзер будет отображен.

**Comment by Kizat** [comment]
обычно когда мы вызывается метод `await Future.delayed(const Duration(second: 5));` а потом вызываем метод `print('hello world');` мы ждем 5 секунд а потом получаем hello world, так вот, после вызова метода await `yandexMapController.toggleUserLayer(visible: true);` тоже хочется чтобы методы после него стоящие дожидались, например для того чтобы узнать показывает в итоге пользователя на карте или нет (иконка кнопки местоположения менять на обозначение что его показывает на карта или нет)

**Comment by DCrow** [comment]
Метод только меняет свойства пользовательского слоя, в какой момент отображать его зависит от внутренней либы, на что повлиять не возможно.
