### ISSUE TITLE
newCameraPosition is working with problem on iOS

### ISSUE THREAD

**Issue by Ibrokihimbek** [Unact/yandex_mapkit#315]
Good day friends, I have a problem in iOS system when the button is pressed to move the camera to the place where the user is, that is, it freezes for 2 or 3 seconds. There is no problem with Android, as soon as the button is pressed, it moves the camera to where the user is. Do you have a solution for this?

**Comment by subzero911** [comment]
Try to ask here https://pub.dev/packages/yandex_mapkit_community
It's a successor of the current (abandoned) package.

**Comment by DCrow** [comment]
Hello!

Please include an example.
