### ISSUE TITLE
Как самостоятельно изменять поворот маркера пользователя

### ISSUE THREAD

**Issue by Darkildo** [Unact/yandex_mapkit#316]
Есть ли механика для поворота маркера пользователя на карте? Не нашёл в api подобного, а onUserLocationAdded на сколько я понимаю просто игнорирует параметр direction и позже подхватывает эту информацию из внутреннего геолокатора.

**Comment by subzero911** [comment]
Этот пакет, похоже, заброшен авторами.
Спросите сюда https://pub.dev/packages/yandex_mapkit_community
Тут чуваки активно фиксят баги и поддерживают.

**Comment by DCrow** [comment]
Доброе утро!

Указывать вид метки пользователя можно только один раз в onUserLocationAdded.
Подскажите, указали ли вы для `PlacemarkIconStyle` метки `rotationType: RotationType.rotate`?(Это требуется для поворота иконки метки)
