### ISSUE TITLE
Когда ожидать обновление пакета для Flutter?

### ISSUE THREAD

**Issue by Likhachev17** [Unact/yandex_mapkit#317]
версия в пабе не обновлялась 7 месяцев. Было бы здорово увидеть обновление с фиксом обфусцакии и уменьшенным размером. Яндекс карты сейчас единственный вменяемый вариант для карт для ру комьюнити

**Comment by subzero911** [comment]
Переезжайте на форк https://pub.dev/packages/yandex_mapkit_community
Тут чуваки активно фиксят баги и поддерживают.

**Comment by DCrow** [comment]
Обновил нативные либы до 4.3.2 и смерджил фиксы

**Comment by Likhachev17** [comment]
@DCrow Огромное спасибо!
