### ISSUE TITLE
навигатор и отображение траффика на polyline

### ISSUE THREAD

**Issue by EbriusQuasimodo** [Unact/yandex_mapkit#318]
Привет! не могу найти метода для реализации навигатора(как яндекс навигатор) в приложении, такой есть? 
Сейчас мы используем yandexnavi, он просто открывает приложение навигатора, но хотелось бы реализовать это в нашем приложении на flutter. 
Пока что я нашла только как получить маршрут от точки а к точке б, и информацию о расстоянии и времени в пути

**Comment by subzero911** [comment]
Этот пакет, похоже, заброшен авторами.
Спросите сюда https://pub.dev/packages/yandex_mapkit_community
Тут чуваки активно фиксят баги и поддерживают.

**Comment by DCrow** [comment]
Добрый день!

Похожий пример(построение маршрута) можно посмотреть в `examples/driving_page.dart`
Для отображения самого пользователя можно использовать как в `examples/user_layer_page.dart`

**Comment by Ahrorxoja** [comment]
> ривет! не могу найти метода для реализации навигатора(как яндекс навигатор) в приложении, такой есть?
> Сейчас мы используем yandexnavi, он просто открывает приложение навигатора, но хотелось бы реализовать это в нашем приложении на flutter.
> Пока что я нашла только как получить маршрут от точки а к точке б, и информацию о расстоянии и времени в пути

У меня такая же проблема, как ты это сделал?

**Comment by Ahrorxoja** [comment]
Can selectedWayList.add(PolylineMapObject(
                mapId: MapObjectId('route_${results.length}_polyline'),
                polyline: Polyline(points: result.routes!.asMap()[i]!.geometry),
                strokeColor: Colors.blue,
                strokeWidth: 2,
              )); do this only to onTrafficChanged: (TrafficLevel? trafficLevel) {
              setState(() {
                level = trafficLevel?.level ?? 0;
                trafficColor = trafficLevel != null
                    ? _colorFromTraffic(trafficLevel.color)
                    : Colors.white;
              });?
