### ISSUE TITLE
После обновления до 3.3.0 ексепшн "java.lang.AssertionError: setApiKey() should be called before initialize()" появляется и на релизе

### ISSUE THREAD

**Issue by pamir72** [Unact/yandex_mapkit#321]
После обновления до 3.3.0 ексепшн "java.lang.AssertionError: setApiKey() should be called before initialize()" теперь появляется и на релизе.  До 3.3.0 это было только в debug. См. закрытые топики #271 and #206.
Яндекс не рекомендует вставлять MapKitFactory.setApiKey("Your API key") в MainActivity, а рекомендует это делать в onCreate Application. Подскажите пожалуйста, кто-нибудь уже решал успешно данную проблему во flutter ?

**Comment by AbrorEsonov** [comment]
same too, any news?

**Comment by intraector** [comment]
same here

**Comment by Vigorouzis** [comment]
Добавил setApiKey() в onCreate и ошибка пропала
`import android.os.Bundle
import android.os.PersistableBundle
import androidx.annotation.NonNull
import com.yandex.mapkit.MapKitFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
    }

    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        MapKitFactory.setApiKey("YOUR KEY")
        super.onCreate(savedInstanceState, persistentState)
    }
}`

**Comment by Vigorouzis** [comment]
Добавил setApiKey() в onCreate и ошибка пропала
```
import android.os.Bundle
import android.os.PersistableBundle
import androidx.annotation.NonNull
import com.yandex.mapkit.MapKitFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
    }

    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        MapKitFactory.setApiKey("YOUR KEY")
        super.onCreate(savedInstanceState, persistentState)
    }
}
```

**Comment by AlexSmirnov9107** [comment]
Временно помогло решение обернуть в try catch


```

import com.yandex.mapkit.MapKitFactory
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterFragmentActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        try {
            MapKitFactory.setApiKey("")
        } catch (e: AssertionError) {

        }
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }


}
```
<img width="1265" alt="image" src="https://github.com/Unact/yandex_mapkit/assets/32673518/c055eda9-9a14-429a-a68e-43443a4e5c8b">

**Comment by pamir72** [comment]
Спасибо, добрый человек ! Вроде как работает !

**Comment by Ravensof** [comment]
в документации яндекса для андроид написано делать setApiKey в Application. вынес в Application.onCreate и краши прекратились

**Comment by pamir72** [comment]
Не поделитесь со всеми ?

**Comment by Ravensof** [comment]
https://yandex.ru/dev/mapkit/doc/ru/android/quickstart#setup

![image](https://github.com/Unact/yandex_mapkit/assets/47619905/4b422e44-16ef-4aca-80b4-e526e6c63820)

**Comment by pamir72** [comment]
Именно для flutter. Мне не удалось добиться.

**Comment by dumptyhumpty2014gmail** [comment]
try catch не помогает. Все равно в Firebase сыпет ошибку.
А где найти FlutterApplication, я не понимаю.
В OnCreate у MainActivity  не срабатывает. А в проекте флаттера я не вижу, где у нас FlutterApplication.

**Comment by DaryaRyz** [comment]
Не подскажете, как именно добавлять FlutterApplication в проекте Flutter исходя из этого ответа https://github.com/Unact/yandex_mapkit/issues/321#issuecomment-1700820245?

**Comment by Ravensof** [comment]
у вас ОДИН единственный Application на всё флаттер приложение:/
ищите в android/app/src/
