### ISSUE TITLE
User Location Accuracy

### ISSUE THREAD

**Issue by Destanci** [Unact/yandex_mapkit#327]
while using a user layer, we can reach the point, zoom and tilt of the camera but cant reach to the accuracy of the user location.
The package it self can reach to the accuracy but I couldn't find a way to reach that informatiion, so im using an other location package for it which is not the same as the map shows. So is there a way that I didn't see ? If not it would be very nice if implemented to this package.

**Comment by DCrow** [comment]
Hello!

No, the only way to get location accuracy is to use other libraries.
Unfortunately native implementations of `YandexMapController.getUserCameraPosition` can only return what is currently returned. If and when the native libraries will support returning accuracy depends on the developers of iOS/Android yandex library.
