### ISSUE TITLE
Ошибка: No interface method setModelsEnabled(Z)V

### ISSUE THREAD

**Issue by BDemetrix** [Unact/yandex_mapkit#331]
При вызове `YandexMap()` в flutter    
падает с ошибкой:   
```
java.lang.NoSuchMethodError: No interface method setModelsEnabled(Z)V in class Lcom/yandex/mapkit/map/Map; or its super classes (declaration of 'com.yandex.mapkit.map.Map' appears in /data/app/~~rQjAcqYHSxdAGRDLDK1Xo==/com.devstars.smart_client_app--5iWkMDw6_TKkF6FFj3AeA==/base.apk!classes19.dex)
```

**Comment by DCrow** [comment]
Добрый день!

Вы инициализируете проект так как в README указано? 
Просьба приложить `flutter doctor --verbose`

**Comment by azakost** [comment]
Подтверждаю.  
На `com.yandex.android:maps.mobile:4.4.0-full` крашится. 
При смене на `com.yandex.android:maps.mobile:4.3.2-full` работает нормально. 

Инициализировал как указано в Readme

**Comment by DCrow** [comment]
@azakost 
Для какой версии yandex_mapkit?

**Comment by azakost** [comment]
@DCrow стояла 3.3.3. Апгрейднул до ^3.4.0 и проблема ушла =)

**Comment by DCrow** [comment]
Все верно, с 3.3.3 только `com.yandex.android:maps.mobile:4.3.2-full` может работать, с 3.4.0 только `com.yandex.android:maps.mobile:4.4.0-full`
