### ISSUE TITLE
PlacemarkIcon image from network.

### ISSUE THREAD

**Issue by isroiloglu** [Unact/yandex_mapkit#332]
How can I use NetworkImage to PlacemarkIcon in YandexMap?

**Comment by Bagmet-Denis** [comment]
find solution ?

**Comment by isroiloglu** [comment]
unfortunately no

**Comment by DCrow** [comment]
Hello!

YandexMapkit doesn't support using images from external sources directly but you can use [ImageProvider](https://api.flutter.dev/flutter/painting/ImageProvider-class.html) to load your image and then update `PlacemarkIcon` with loaded data.
