### ISSUE TITLE
I should do the same. How can one tell where to turn and only see traffic on that drawn line?

### ISSUE THREAD

**Issue by Ahrorxoja** [Unact/yandex_mapkit#333]
![image](https://github.com/Unact/yandex_mapkit/assets/79145126/d1a92946-222a-47f2-bfb2-e3fc1681ce57)
![image](https://github.com/Unact/yandex_mapkit/assets/79145126/756e2564-f770-431b-9cc6-36c074aca68a)
I should do the same. How can one tell where to turn and only see traffic on that drawn line?

**Comment by DCrow** [comment]
Hello!

The first screenshot is not supported. You have to use https://yandex.ru/maps-api/products/navikit for this.
