### ISSUE TITLE
Got memory warning YandexMap

### ISSUE THREAD

**Issue by kalanchik** [Unact/yandex_mapkit#335]
`W/yandex.maps(20438): ohd/d3Tagjy1s/CO1noz: Got memory warning`
Is this warning a bad sign? Maybe I did something wrong?

**Comment by DCrow** [comment]
Hello!

Could you provide more details on when it happens?(`flutter doctor -v` and after what the message is displayed)  
Also a reproducible example would be very much appreciated.
