### ISSUE TITLE
Краш примера на IOS 12.5.7

### ISSUE THREAD

**Issue by sorgfal** [Unact/yandex_mapkit#338]
✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone Даниил  Колясников. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

При запуске примера из папки example (ничего не меняя, кроме ключа и локали в AppDelegate.swift) приложение доходит до нативного лаунч экрана и закрывается(но превью приложения висит в запущенных).

Запуск на Iphone 6 Ios 12.5.7

Никаких логов не дает

Отладчик Xcode 

![image](https://github.com/Unact/yandex_mapkit/assets/38051021/8123259f-96e8-47f4-a165-1377392d9ea0)

**Comment by DCrow** [comment]
Добрый день!

Тут ошибка внутри нативной либы, придется ждать когда ее поправят разработчики Яндекс.

**Comment by EktoryMoor** [comment]
Hello! The following error occurs on the second run in the emulator:
```
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate

```
When tracing in Xcode 15.0.1 (yandex_mapkit 3.4.0), a similar error occurs as the author's.

**Comment by DCrow** [comment]
В [Xcode 15.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes) не должно воспроизводится.
