### ISSUE TITLE
implement Router support

### ISSUE THREAD

**Issue by vanomak** [Unact/yandex_mapkit#34]

**Comment by fryette** [comment]
Any news on it?

**Comment by DCrow** [comment]
This needs more clarification on which functionality is needed. 
Mapkit Directions has a vast amount of classes, implementing all of them would take too much time.

At least some real-world use-case scenarios would be great.

**Comment by imanmagomedov** [comment]
Building a driver’s route for several points on the map with createDriverRouter (https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-directions/ref/com/yandex/mapkit/directions/Directions-docpage/)

**Comment by JRakhimov** [comment]
So, is it possible to build routes berween points now? @DCrow

**Comment by DCrow** [comment]
@JRakhimov At the current moment no one has implemented this functionality yet. If anyone is willing to implement it, I am always happy to review it and include it in the library.
