### ISSUE TITLE
Placemark text overlaps

### ISSUE THREAD

**Issue by yaro-melnychuk** [Unact/yandex_mapkit#340]
Text overlaps when there are many placemarks with `Placemark.text` set.
Looks like the `outlineColor` is not working for the text of another placemark.
Can we fix this?

![Screenshot 2023-12-15 at 14 41 41](https://github.com/Unact/yandex_mapkit/assets/85098704/e9f67423-3a48-4a75-bd82-2bf9793bc322) |  ![Screenshot_2023-12-15-14-23-27-549_kz daribar app-edit](https://github.com/Unact/yandex_mapkit/assets/85098704/52643425-4782-427e-90a4-d57c8628be2c)
:-------------------------:|:-------------------------:

**Comment by DCrow** [comment]
Hello!

I don't quite understand the problem. `PlacemarkTextStyle.outlineColor` is working as intended.
Overlapping of placemark text can be controller by `PlacemarkMapObject.zIndex`.
