### ISSUE TITLE
 I need a search engine like the one on the yandex map website, but it's only searching for the name of streets or city names. Can we make the map more flexible?

### ISSUE THREAD

**Issue by Ahrorxoja** [Unact/yandex_mapkit#345]
I need a search engine like the one on the yandex map website, but it's only searching for the name of streets or city names. Can we make the map more flexible?

**Comment by DCrow** [comment]
Hello!

What results search/suggest return solely depends on what the native [iOS](https://github.com/yandex/mapkit-ios-demo)/[Android](https://github.com/yandex/mapkit-android-demo) developers implement. 
Since this is only a flutter wrapper around those native libraries please ask there.
