### ISSUE TITLE
При отмене сессии YandexSearch.searchByPoint получаю MissingPluginException - No implementation found for method cancel...

### ISSUE THREAD

**Issue by egorozh** [Unact/yandex_mapkit#348]
Здравствуйте,

Подскажите, пожалуйста, 
Ловлю ошибку - `MissingPluginException(No implementation found for method cancel on channel yandex_mapkit/yandex_search_session_8)` при попытке отмены сессии через session.session.cancel();

Делаю ради синхронизации, чтобы отменять запрос на сервер при частом вызове(при перемещении карты). Возможно трактую неправильно использование api.

Пример кода:
```dart
    final session = YandexSearch.searchByPoint(
        point: target,
        zoom: zoom,
        searchOptions: const SearchOptions(
          searchType: SearchType.geo,
        ));

    final completer = CancellableCompleter<SearchSessionResult>(
      cancellationToken,
      onCancel: () {
        session.session.cancel();
      },
    );

    if (cancellationToken?.isCancelled != true) {
      session.result.then((result) => completer.complete(result),
          onError: (Object error, StackTrace stackTrace) => completer.completeError(
                error,
                stackTrace,
              ));
    }

    final addresses = await completer.future;

    final firstAddress = addresses.items?.firstOrNull;
```

Либа с CancellationToken - https://pub.dev/packages/cancellation_token

**Comment by DCrow** [comment]
Добрый день!

Такого не должно происходить, тут бага в текущей либе. В ближайшем будущем будет исправлена.

**Comment by DCrow** [comment]
Да, там везде одна проблема. В YandexDriving и YandexBicycle тоже присутствует.

**Comment by DCrow** [comment]
Исправлено в новой версии
