### ISSUE TITLE
android 10: the map is not being drawn

### ISSUE THREAD

**Issue by MiSticksman** [Unact/yandex_mapkit#349]
It was found that on android 10 devices the map is not rendered, but the space it occupies is clickable and the points can be selected. I checked on android 12-14, everything works correctly, without lags.
android 10:
![telegram-cloud-photo-size-2-5341788746481259594-y](https://github.com/Unact/yandex_mapkit/assets/76129265/91248b16-3531-4e8d-98f4-513f3896f3c1)
![telegram-cloud-photo-size-2-5341788746481259595-y](https://github.com/Unact/yandex_mapkit/assets/76129265/9b99ee4b-fc5b-4ad3-8996-dfeb81cd0625)
logcat:
![telegram-cloud-photo-size-2-5341788746481259603-y](https://github.com/Unact/yandex_mapkit/assets/76129265/5226b923-3904-406f-a66c-ff9699a4e12c)
![telegram-cloud-photo-size-2-5339207153308783086-y](https://github.com/Unact/yandex_mapkit/assets/76129265/78a89f19-3967-4b61-befa-6ee9f02d6c85)

android 14
![telegram-cloud-photo-size-2-5339207153308783039-y](https://github.com/Unact/yandex_mapkit/assets/76129265/e8357c3b-6d62-4373-914e-805a40238f6b)

**Comment by androidparanoidal** [comment]
I have the same problem on Android 9, but this empty area is not clickable

**Comment by MiSticksman** [comment]
The problem was that useAndroidViewSurface = true. Deleting this line solved the problem
