### ISSUE TITLE
Не загружается карта без разрешений на геолокацию

### ISSUE THREAD

**Issue by AlexeyKuznetsovGit** [Unact/yandex_mapkit#355]
Я хочу отобразить карту даже если я не дал разрешение на геолокацию, но в этом случае на android устройстве у меня карта не загружается, вместо этого показывается сетка из квадратов. Логика такая, что если юзер не дал координаты свои, то приложение показывает ему центр Москвы и дальше пусть делает что хочет. Что нужно для этого сделать? На ios устройстве все работает.
![2024-03-28 17 45 32](https://github.com/Unact/yandex_mapkit/assets/61086054/d80d10df-0602-4198-880c-4bd52fd0611d)

**Comment by DCrow** [comment]
Здравствуйте!

Так карта отображается только тогда, когда апи ключ не указан либо не активирован. 
Разрешения на получение данных геолокации не влияют на отображение карты.
