### ISSUE TITLE
onMapCreated - Invalid constant value

### ISSUE THREAD

**Issue by Syabr** [Unact/yandex_mapkit#363]
Добрый день, столкнулся с проблемой что в `onMapCreated: (controller) {}` не могу прописать так, делаю по гайду из [хабра](https://habr.com/ru/companies/friflex/articles/715940/), в dart новичек и немного непонятно почему ругается на данный кусок кода.  Буду благодарен ответу что делаю не так

**Comment by DCrow** [comment]
Добрый день!

Пожалуйста приложить кусок кода, который вызывает ошибку.

Скорее всего, у вас какой-то из родителей `YandexMap` имеет объявлен через `const`, при таком объявлении, все ниже стоящие классы автоматически имеют const в объявлении, но `const` нельзя использовать с лямбда функциями.

**Comment by Syabr** [comment]
Спасибо большое за ответ! Действительно, указал `child: const YandexMap(...)`. Странно что именно это небыло подсвечено. Спасибо
