### ISSUE TITLE
focusRect не работает на андроиде

### ISSUE THREAD

**Issue by yaro-melnychuk** [Unact/yandex_mapkit#367]
`focusRect` не работает на **андроиде**
на **iOs** работает
Воспроизводится на примере из **example**

[ссылка на кнопку в примере](https://github.com/Unact/yandex_mapkit/blob/67106aca1a1e3c3544a47f31d7b58a7a202b2721/example/lib/examples/map_controls_page.dart#L295)

версия 4.0.2

**Comment by melnychuk-yaro** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by DCrow** [comment]
Добрый день!

Да, действительно не работает, исправлю в ближайшее время.
