### ISSUE TITLE
Yandex Search

### ISSUE THREAD

**Issue by khorunaliyevtursunali** [Unact/yandex_mapkit#370]
MissingPluginException(No implementation found for method initSession on channel yandex_mapkit/yandex_search)
I'm using Dart 3.3.0 and Flutter 3.19.2
YandexMapKit 4.0.2
Yandex map opened and markers working perfectly
But when I using YandexSearch.searchByText is not working

**Comment by batya3000** [comment]
any updates? almost the same error 
MissingPluginException(No implementation found for method initSession on channel yandex_mapkit/yandex_driving)

in YandexDriving.requestRoutes

**Comment by DCrow** [comment]
Hello!

Have you set your desired variant correctly? In `android/gradle.properties` for Android and in `ios/Podfile` for iOS.

By default `lite` variant is used, which does not implement `YandexDriving`, `YandexBycicle`, `YandexPedestrian`, `YandexSearch`, `YandexSuggest`.

**Comment by batya3000** [comment]
my bad. thanks, now it works)

**Comment by khorunaliyevtursunali** [comment]
@DCrow 
My variant
yandexMapkit.variant=full

**Comment by khorunaliyevtursunali** [comment]
Can anyone help me on this issue

**Comment by khorunaliyevtursunali** [comment]
No answer from Yandex and has no good doc for developers.

**Comment by DCrow** [comment]
@khorunaliyevtursunali 
In your application you have to include `implementation 'com.yandex.android:maps.mobile:4.5.1-full`. 
yandex_mapkit v4.0.2 library only supports native v4.5.1.
