### ISSUE TITLE
Не отображается виджет карты в версии скачанной из Google Play 

### ISSUE THREAD

**Issue by imdul** [Unact/yandex_mapkit#371]
Здравствуйте.

При тестировании версии debug в эмуляторе и версии relese на планшете виджет работает. Карта отображается, приближение работает, отображает метки, линии и местоположение.

Только в логе получаю сразу после инициализации:
> I/PlatformViewsController( 9504): Using hybrid composition for platform view: 0
> D/EGL_emulation( 9504): eglMakeCurrent: 0xec0619c0: ver 2 0 (tinfo 0xec3b2330) (first time)
> W/Gralloc4( 9504): allocator 3.x is not supported
> I/u.appname( 9504): NativeAlloc concurrent copying GC freed 8636(709KB) AllocSpace objects, 8(288KB) LOS objects, 49% free, 3419KB/6838KB, paused 934us total 120.320ms
> E/EGL_emulation( 9504): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
> E/EGL_emulation( 9504): tid 9504: eglQueryContext(2019): error 0x3004 (EGL_BAD_ATTRIBUTE)
> ...
> W/yandex.maps( 9504): XMCuGl4Nfl5wkXbkDBlj: Could not choose OpenGl ES Version 3 config; Got EGL error 12288
> W/yandex.maps( 9504): XMCuGl4Nfl5wkXbkDBlj: Create OpenGl ES context version 2

После загрузки приложения из Google Play (закрытое тестирование) карты нет, на этом месте ничего нет, пусто. И метод `onMapCreated` не выполняется. Как будто виджет вырезан из приложения.

**android/gradle.properties** (наличие этой строки не влияет)
> ...
> yandexMapkit.variant=full

**android/app/build.gradle**
> dependencies {
>     implementation 'com.yandex.android:maps.mobile:4.5.1-full'
>     implementation platform('com.google.firebase:firebase-bom:33.0.0')
>     implementation 'com.google.firebase:firebase-messaging:24.0.0'
>     implementation 'com.google.firebase:firebase-iid:21.1.0'
>     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
>     implementation 'androidx.window:window:1.2.0'
>     implementation 'androidx.window:window-java:1.2.0'
>     implementation "androidx.core:core-splashscreen:1.0.1"
> }

**app/src/main/AndroidManifest.xml**
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
>     
>     <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
>     <uses-permission android:name="android.permission.CAMERA" />
>     <uses-feature android:name="android.hardware.camera" android:required="false" />
> ...
>         <activity
>             android:name=".MainActivity"

Получаю ошибку во время инициализации виджета карты:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map
    	at io.flutter.plugin.platform.z.M(SourceFile:1)
    	at io.flutter.plugin.platform.z$a.d(SourceFile:1)
    	at n7.q$a.c(SourceFile:1)
    	at n7.q$a.onMethodCall(SourceFile:1)
    	at o7.k$a.a(SourceFile:1)
    	at f7.c.l(SourceFile:1)
    	at f7.c.m(SourceFile:1)
    	at f7.c.i(SourceFile:1)
    	at f7.b.run(SourceFile:1)
    	at android.os.Handler.handleCallback(Handler.java:938)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loop(Looper.java:223)
    	at android.app.ActivityThread.main(ActivityThread.java:7814)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
    , null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
    <asynchronous suspension>
    #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099)
    <asynchronous suspension>
    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822)
    <asynchronous suspension>
```

**Comment by VladVKozlov** [comment]
У меня такая же проблема.

**Comment by VladVKozlov** [comment]
Учеловека в чате https://t.me/mapkit/6452 проблема решилась вот так:
```
Бился только что с этой же проблемой в аналогичном environment'е. Не помогло ничего из советов, в свежий проект - также не сработало.
Проблема оказалась в строке MapKitFactory.setLocale("RU"). Если убрать её или исправить на MapKitFactory.setLocale("ru_RU"), то работает.
```

Но у меня `MapKitFactory.setLocale()` закомментировано, так как я хочу использовать язык системы по умолчанию

**Comment by imdul** [comment]
> Решилось откатом на [3.4.0](https://pub.dev/packages/yandex_mapkit/versions/3.4.0) , там в релиз версии все работает.

Попробовал откатить и действительно заработало. Спасибо за подсказку, была такая мысль на крайний случай (ранее писали о появлении этой ошибке в версии 4), пока работает так, параллельно тестирую виджет от Яндекса.


> Но у меня `MapKitFactory.setLocale()` закомментировано, так как я хочу использовать язык системы по умолчанию

У меня тоже эта строка закомментирована.

> `MapKitFactory.setLocale("RU");` // Your preferred language. **Not required**, defaults to system language



> Если убрать её или исправить на MapKitFactory.setLocale("ru_RU"), то работает.

Интересно, как комментарии влияют на работу?! Проверю и этот вариант. Спасибо за информацию.

**Comment by DCrow** [comment]
Здравствуйте!

@imdul
К сожалению нет возможности проверить багу через Google Play.
По предполагаемой проблеме выложил фикс в ветке [gp_fix](https://github.com/Unact/yandex_mapkit/tree/gp_fix). Не могли бы сказать, исправил ли он вашу проблему?

> Интересно, как комментарии влияют на работу?!

Тут проблема в нативной либе, если некорректно указывать локаль, то либа нормально не инициализируется. Возможные варианты [тут](https://yandex.ru/dev/jsapi30/doc/ru/dg/concepts/localization) указаны.

**Comment by imdul** [comment]
> К сожалению нет возможности проверить багу через Google Play.

Ошибка появлялась в release версии. Она была впервые обнаружена при тесте из Google Play.

> Не могли бы сказать, исправил ли он вашу проблему?

В версии [gp_fix](https://github.com/Unact/yandex_mapkit/tree/gp_fix) работает, вроде всё ок.



> Тут проблема в нативной либе, если некорректно указывать локаль, то либа нормально не инициализируется.

Значение "RU" вызывает фатальную ошибку. В версии 4.0.2 с разными вариациями, либо с закомментированной или отсутствующей строкой локали, всегда вызывает эту ошибку (из первого сообщения).


**С такими настройками:**

`android/app/src/main/java/[ru.name.app]/MainApplication.java`
```
package [ru.name.app];
import android.app.Application;
import com.yandex.mapkit.MapKitFactory;

public class MainApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
         MapKitFactory.setLocale("ru_RU");
         MapKitFactory.setApiKey("WORKED_API_KEY");
    }
}
```

`android/app/src/main/kotlin/[ru.name.app]/MainActivity.kt`
```
package [ru.name.app]

import androidx.annotation.NonNull
import com.yandex.mapkit.MapKitFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setLocale("ru_RU")
        MapKitFactory.setApiKey("WORKED_API_KEY")
        super.configureFlutterEngine(flutterEngine)
    }
}
```

`android/app/build.gradle`
```
dependencies {
    ...
    implementation 'com.yandex.android:maps.mobile:4.5.1-full' // <- подсвечивает строку: A newer version of com.yandex.android:maps.mobile than 4.5.1-full is available: 4.5.1-lite
}
```

Здесь можно использовать более новую версию? С версией 4.0.2 тоже не работало.

> 4.6.1-lite |   | Central | 0 | Apr 25, 2024
> 4.6.1-full |   | Central | 0 | Apr 25, 2024

**Comment by DCrow** [comment]
> Значение "RU" вызывает фатальную ошибку.

Тут только методом проб определять, в документации яндекса про это ничего не написано. 

> В версии [gp_fix](https://github.com/Unact/yandex_mapkit/tree/gp_fix) работает, вроде всё ок.

Хорошо, спасибо. В ближайшее время выпущу новую версию с фиксом.

> Здесь можно использовать более новую версию? С версией 4.0.2 тоже не работало.

Нет, для 4.0.2 только нативная версия 4.5.1.

**Comment by DCrow** [comment]
Выпустил новую версию
