### ISSUE TITLE
Есть ли какая нибудь встроенная оптимизация для работы с большим количеством точек и кластеров?

### ISSUE THREAD

**Issue by StasVersh** [Unact/yandex_mapkit#374]
Мы работает с апи сдека, выводим пункты выдачи, которых больше 8000, и в момент отрисовки этих точек на не очень мощных устройствах прилажка может подвиснуть на сек 10) Есть ли какие нибудь встроенные оптимизации по типу отрисовки точек в определенных локациях и тд?
P.S
После того как маркеры отрисованы, всё работает плавно

**Comment by DCrow** [comment]
Добрый день!

Со слов https://github.com/yandex/mapkit-android-demo/issues/40 разработчиков нативной либы, либа не предназначена на такое большое кол-во точек. 
Каких-либо специальных оптимизаций, к сожалению, нет.
