### ISSUE TITLE
When closing the page, the map continues to be drawn, for several milliseconds

### ISSUE THREAD

**Issue by K01010010** [Unact/yandex_mapkit#389]
При закрытии страницы, карта продолжает отрисовываться, несколько милисекунд. Используется AutoRouter, мне в принципе показалось несколько странным что виджет не встраивается в виджет-tree как следует.

When closing the page, the map continues to be drawn, for several milliseconds. AutoRouter is used, in principle it seemed a little strange to me that the widget is not embedded in the widget-tree as it should be.

Здесь в скриншоте была закрыта страница заказа, и произошел переход на историю заказов - я подловил момент и сделал скриншот, с возникшим багом
![image](https://github.com/user-attachments/assets/8319f241-4fa2-4b0d-b971-10092be3f9eb)

**Comment by n0ndescr1pt** [comment]
есть вариант при закрытии менять карту на пустой SizedBox(), сделать это на выход по кнопке и на OnWillPopScope когда жестами выходишь, у меня так же было с плеером через inAppWebView при выходе плеер оставался на пару миллисекунд на другом экране, какую нибудь переменную setState и меняет на SizedBox() мне помогло

**Comment by K01010010** [comment]
> есть вариант, но он немного костыльный при закрытии менять карту на пустой SizedBox(), сделать это на выход по кнопке и на OnWillPopScope когда жестами выходишь, у меня так же было с плеером через inAppWebView при выходе плеер оставался на пару миллисекунд на другом экране, какую нибудь переменную setState и меняет на SizedBox() мне помогло

это действительно помогло, сделал через стейт менеджер показ/сокрытие виджета, через изменение флага в PopScope и повторное отображение в initState - проблема исчезла большое спасибо. Вопрос закрыт
