### ISSUE TITLE
Все запускается работает но изображения самих карт нет 

### ISSUE THREAD

**Issue by AlexEAA** [Unact/yandex_mapkit#39]
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.13.6 17G10021, locale ru-RU)
    • Flutter version 1.14.6 at /Users/seoinetru/Downloads/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/seoinetru/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Users/seoinetru/Downloads/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • SM G975F   • R58M351M10R • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome      • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server  • web-javascript • Flutter Tools

**Comment by AlexEAA** [comment]
кажется нашел yandex::maps::runtime::network::spdylay::Connector::connect: Could not connect to 149.5.244.18:443, reason: certificate verify failed

**Comment by DCrow** [comment]
Если нет изображения карты(пустые квадратики), то значит
1. Не указан ключ
2. Яндекс не активировал ключ

Как указывается ключ в проекте?

**Comment by AlexEAA** [comment]
Спасибо , заработал , видно активация ключа занимает какое то время.

**Comment by DCrow** [comment]
Да, такое часто происходит. В таких случаях, лучше сразу писать в поддержку Яндекса, чтоб они сами активировали, автоматом у них как-то долго активируется.
