### ISSUE TITLE
API_KEY Problem with Kotlin

### ISSUE THREAD

**Issue by KenanYusubov** [Unact/yandex_mapkit#41]
**Hi. I have added my API key to my app. But your example only contains Java version of adding API Key. How can I add Kotlin version?**

`package com.example.courier_map
`
```
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import com.yandex.mapkit.MapKitFactory
```

```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setApiKey("MY API KEY IS HERE")
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

I have done this version, but it does not work. It gives the following view:
[error image](https://drive.google.com/file/d/1jzFiOAysNXp_O0aXyvCoG1L6Ya0McPxs/view?usp=sharing)

?> I have granted permissions.

How can I solve it?

**Comment by DCrow** [comment]
Hello! Kotlin initialization is the same as Android. After Flutter v 1.12 Android embedding was changed, which changed code generation for new projects and because of that `onCreate` method is no longer created, instead `configureFlutterEngine` is created.

As I can see in your image, map widget is showing, except it doesn't display the map itself(map fragments are not rendered). 
Most likely your api key has not been activated by Yandex. You should contact them for activation.

As for black areas around buttons, it seems this is some kind of Flutter bug, since that area is a Flutter plugin not a native widget.

**Comment by KenanYusubov** [comment]
Thanks a lot for explanation.

**Comment by KenanYusubov** [comment]
But Yandex Developer Dashboard shows that api key is activated.

**Comment by KenanYusubov** [comment]
Solved.

**Comment by DCrow** [comment]
As far as I understand, Dashboard is displaying active(meaning created)/disabled(meaning deleted) keys, key activation isn't being reflected there. 

This problem occurs very frequently. 
Most times the key is activated automatically after a few days, or manually by asking Yandex support to activate it.

**Comment by DCrow** [comment]
>Solved.

Great to hear

**Comment by KenanYusubov** [comment]
> PS You can attach images to github comments just by pasting them in, instead of using google drive



> As far as I understand, Dashboard is displaying active(meaning created)/disabled(meaning deleted) keys, key activation isn't being reflected there.
> 
> This problem occurs very frequently.
> Most times the key is activated automatically after a few days, or manually by asking Yandex support to activate it.

I asked them for activation. And it is working. But there is new problem. When I use showUserLayer method, it doesn't show icon that I give it, it shows default icon. What is the problem?

**Comment by DCrow** [comment]
Maybe you haven't enabled `android.permission.ACCESS_FINE_LOCATION` permission?

If that doesn't help please provide a code sample + `flutter doctor` result
