### ISSUE TITLE
are some method deprecated?

### ISSUE THREAD

**Issue by KenanYusubov** [Unact/yandex_mapkit#42]
I want to use YandexSearch, Camera tracking but it does not give me any suggestions. So, I can't add it to my project. are they deprecated?

_But they are showing in the last changelog of yandex_mapkit._

**Comment by DCrow** [comment]
Both were added recently. They are working as intended. 

It should be noted that for YandexSearch, it does not show results for incomplete words(For example `mos` doesn't show anything while `moscow` returns some results)

Can you provide an example?
