### ISSUE TITLE
Address suggestion not working on IOS

### ISSUE THREAD

**Issue by Rehckover** [Unact/yandex_mapkit#52]
Address suggestion works fine on an android device but on IOS such error occur:
std::__1::enable_if <warn>: No available cache for request

**Comment by DCrow** [comment]
Hello!

As far as I know, currently there are no problems with Address suggestion feature on both iOS and Android.

Could you provide an example?
Also could you paste your `flutter doctor -v`

**Comment by DCrow** [comment]
Closing since no one answered
