### ISSUE TITLE
Crash on iOS when moving with zoom parameter

### ISSUE THREAD

**Issue by sorokinDev** [Unact/yandex_mapkit#54]
I have a button to move map on tap:
```
final double zoom = 14.7;
await _controller.move(
  point: Point(latitude: userLocation.latitude, longitude: userLocation.longitude),
  zoom: zoom
);
```
This results to crash only on iOS in Crashlytics without stacktrace:
YandexMapController.swift line 160
YandexMapController.move(_:)

Line 160 in YandexMapController.swift is:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/19349760/90151333-a9fdbc80-dd97-11ea-9eae-f7c036d97fda.png">

If I remove zoom parameter, everything works fine. Also, no problem on Android.
Version of the library: ^0.3.9
Flutter doctor: Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale ru)

**Comment by DCrow** [comment]
Hello!
Thanks for reporting!

It seems this is a problem with converting Dart `double` into Swift `Float`.
Fixed this in master branch.

**Comment by lexpolesov** [comment]
When will the new version of the library for flutter appear with these changes?

**Comment by DCrow** [comment]
@lexpolesov If you're referring to pub.dev, then I just published the new version.  

Also you can always specify a github repository in your pubspec.yaml like so
```yaml
yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit.dart
```
