### ISSUE TITLE
Event on map tap

### ISSUE THREAD

**Issue by dadrum** [Unact/yandex_mapkit#56]
Hi, is there any way to catch the event onMapTap (@NonNull Map map, @NonNull Point point) ?

**Comment by DCrow** [comment]
Hello!

Currently this feature is not implemented. 
If anyone is willing to implement it, I am always happy to review it and include it in the library.

**Comment by DCrow** [comment]
This is now implemented in master branch.

New callback methods `onMapTap` and `onMapLongTap` have been added to `YandexMap`
