### ISSUE TITLE
How to activate dark mode?

### ISSUE THREAD

**Issue by kostyanchikoff** [Unact/yandex_mapkit#57]
Android yandex map kit has isNigthMode function which activates dark theme, what is the alternative here? Thank you in advance!

**Comment by DCrow** [comment]
Hello!

Currently this feature is not implemented.
If anyone is willing to implement it, I am always happy to review it and include it in the library.

**Comment by DCrow** [comment]
This is now implemented in master branch.

You can enable night mode the following way
```dart
YandexMap(
  onMapCreated: (YandexMapController yandexMapController) async {
    await yandexMapController.toggleNightMode(enabled: true);
  }
)
```

**Comment by rexolion** [comment]
@DCrow Hello! Sorry, I cannot access the toggleNightMode method. Has it been removed?

**Comment by DCrow** [comment]
@rexolion 
In newer versions it's available like so

```dart
YandexMap(
  nightModeEnabled: true
)
```

**Comment by rexolion** [comment]
@DCrow Thank you for the quick answer!

**Comment by ValeriusGC** [comment]
> [@rexolion](https://github.com/rexolion) In newer versions it's available like so
> 
> YandexMap(
>   nightModeEnabled: true
> )

But how to toggle this in runtime?

I can not see appropriate method in controller.
