### ISSUE TITLE
YandexMap is always rebuilt, and that causes lags in scrolling

### ISSUE THREAD

**Issue by adminant** [Unact/yandex_mapkit#58]
Yandex Map is used as an element of SliverList.
During scrolling wnen approaching map's AndroidView element the scroll lags and element is always rebuilt.
Other elements like Text or other native flutter components don't get rebuild when just scrolling list.

**Comment by adminant** [comment]
More specifically - when map is moved out of screen and returned back - it is fully rebuilt, so the scrolling of list with a map as of element is very laggy!

**Comment by DCrow** [comment]
`YandexMap` uses `UiKitView` and `AndroidView` flutter widgets to render itself(for iOS and Android respectively). 
Scrolling, sizing is handled by those widgets.
This is a problem with those flutter widgets

This might be related to https://github.com/flutter/flutter/issues/34330
