### ISSUE TITLE
Empty grid in example app on iOS

### ISSUE THREAD

**Issue by feronetick** [Unact/yandex_mapkit#6]
I launched the application from the example with my appKey. On iOS Simulator and real device the widget is working, but the map is not displayed. However works on android.

![Снимок экрана 2019-03-28 в 14 09 52](https://user-images.githubusercontent.com/3761183/55144760-55867c80-5163-11e9-817d-0e2025c9e4de.png)

**Comment by DCrow** [comment]
For some reason yandex api key takes **a lot longer** to start working in iOS. 
If this problem persists you should write a tiket to yandex support, that your map is not showing in iOS.

This is a problem specific to yandex key activation.

**Comment by evilandfox** [comment]
Same problem but on Android... Both physical smartphone and emulator show empty map. I tested yandex maps api key that used in app on web application and it works good. What's to do?)

**Comment by evilandfox** [comment]
Problem resolves by itself. The problem was from api key because I created it recently and it requires a bit of time to be activated
