### ISSUE TITLE
Possible hybrid version for lower api devices

### ISSUE THREAD

**Issue by kemphack** [Unact/yandex_mapkit#65]
Stucked with "Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20" because of WebView.
Try using hybrid composition for API 19 lvl (https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-kotlin-tab#hybrid-composition)

**Comment by DCrow** [comment]
Hello!

Please elaborate what are you trying to achieve by using hybrid composition? 
Currently this repository hasn't implemented such functionality.

**Comment by DCrow** [comment]
Closing since previous question has not been answered.
