### ISSUE TITLE
Как найти свое местоположение и показать ближайшие места на карте?

### ISSUE THREAD

**Issue by YaCubeK** [Unact/yandex_mapkit#66]
Здравствуйте! Хотел спросить как можно сделать так, чтобы при открытии страницы с картой автоматом показывалось настоящее местоположение. А также ближайшие заведения(кафе,парки,салоны)? Спасибо заранее!

**Comment by ryufitreet** [comment]
Кафе, парки и другие "точки интереса" отображаются по дефолту, если их не убирать через стили. Текущее положение включается через showUserLayer. У этого проекта очень хорошие примеры, пример с локацией пользователя лежит в layers_page.dart.

**Comment by DCrow** [comment]
Добрый день!

Все как @ryufitreet говорит, по умолчанию различные заведения должны отображаться. 
Местоположение включается/отключается через методы [showUserLayer](https://github.com/Unact/yandex_mapkit/blob/master/lib/src/yandex_map_controller.dart#L47)/[hideUserLayer](https://github.com/Unact/yandex_mapkit/blob/master/lib/src/yandex_map_controller.dart#L72)

Для их использования необходимо указать `NSLocationWhenInUseUsageDescription` в Info.plist для iOS и `android.permission.ACCESS_FINE_LOCATION ` в `main/AndroidManifest.xml`

**Comment by YaCubeK** [comment]
Спасибо, просто когда я использовал showUserLayer у меня показывало локацию компании Google в США. Получается всего надо добавить permission в Manifest-e? И можно еще вопрос yandex mapkit весит около 20 мб, можно ли как то уменьшит его вес в приложении?

**Comment by DCrow** [comment]
Вероятно вы использовали карту в симуляторе. 
У них всегда статичная точка используется для считывания текущей локации(саму координату можно сменить в настройках).

Насчет размеров, действительно либа много весит, особо с этим ничего не сделать. 
Недавно читал, что Яндекс выпустил две вариации либ full/lite для разработки, возможно это уменьшит размер библиотеки. 
В данный момент не представляю, как такого рода функционал имплементировать, разве что делать два репозитория вместо одного.

**Comment by YaCubeK** [comment]
Спасибо за пояснение!
