### ISSUE TITLE
MissingPluginException(No implementation found for method getSuggestions on channel yandex_mapkit/yandex_search)

### ISSUE THREAD

**Issue by MonsWriter** [Unact/yandex_mapkit#70]
Не работает метод `getSuggestions` в Android. Другие методы работают.
В iOS всё в порядке.
```
E/flutter ( 1050): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getSuggestions on channel yandex_mapkit/yandex_search)
E/flutter ( 1050): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter ( 1050): <asynchronous suspension>
E/flutter ( 1050): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter ( 1050): #2      YandexSearch.getSuggestions
package:yandex_mapkit/src/yandex_search.dart:22
E/flutter ( 1050): #3      _HomeScreenState.querySuggestions
package:portal_energy/screens/homescreen.dart:215
E/flutter ( 1050): #4      _HomeScreenState.defaultViewsStack.<anonymous closure>
package:portal_energy/screens/homescreen.dart:265
E/flutter ( 1050): #5      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter ( 1050): #6      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter ( 1050): #7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter ( 1050): #8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter ( 1050): #9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter ( 1050): #10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter ( 1050): #11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter ( 1050): #12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter ( 1050): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter ( 1050): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 1050): #15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter ( 1050): #16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter ( 1050): #17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358
E/flutter ( 1050): #18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter ( 1050): #19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter ( 1050): #20     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter ( 1050): #21     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter ( 1050): #22     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter ( 1050): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 1050): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1050): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 1050): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 1050): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```
Спасибо большое за плагин! Буду рад, если дадите какую-то наводку, в чём может быть проблема.

**Comment by DCrow** [comment]
Добрый день!

Подскажите как подключали к проекту, интересует есть ли в `android/app/AndroidManifest.xml` следующие строки
```xml
<meta-data
                android:name="flutterEmbedding"
                android:value="2" />
```

Также просьба приложить результат `flutter doctor --verbose` и `pubspec.yaml`

По виду похоже, что возможно бага, и не корректно инициализировался MethodChannel для android

**Comment by MonsWriter** [comment]
Подключал к проекту по инструкции в `Readme`. Правда, были два момента, которые пришлось сделать не по инструкции: в `MainActivity.kt` добавить метод `onCreate`, в котором я потом вызывал `MapKitFactory.setApiKey`.
И второе: в `build.gradle` пришлось добавить `implementation 'com.google.android.gms:play-services-location:17.1.0'`, без этого не мог получить геолокацию пользователя в Android.

Мой `AndroidManifest.xml`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.portal_energy">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Portal Energy"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

`flutter doctor --verbose`:
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B28, locale `en-KZ)`
    • Flutter version 1.22.3 at /Users/aleksandr/Downloads/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/aleksandr/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
    ! Error: iPhone (Елена) is not connected. Xcode will continue when iPhone (Елена) is connected. (code -13)

! Doctor found issues in 1 category.

Мой `pubspec.yaml`:

```
name: portal_energy
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  firebase_auth: ^0.18.1+1
  firebase_crashlytics: "^0.2.1+1"
  numeric_keyboard: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6 
  flutter_spinkit: "^4.1.2"
  device_id: ^0.2.0
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.0
  intl_phone_number_input: ^0.5.2
  package_info: ^0.4.0+16
  adaptive_dialog: ^0.9.0
  provider: ^4.3.2+2
  flutter_svg: ^0.19.1
  yandex_mapkit: ^0.4.0
  webview_flutter: ^1.0.5
  permission_handler: ^5.0.1+1
  location: ^3.0.2
  vector_math: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
```

**Comment by DCrow** [comment]
Не совсем понял, зачем надо "MainActivity.kt добавить метод onCreate"? В Readme же указано в configureFlutterEngine надо, внезависимости java или kotlin. 

Для местоположения, насколько я знаю, `implementation 'com.google.android.gms:play-services-location:17.1.0' ` не нужна, главное иметь `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` в AndroidManifest.xml

По зависимостям, вроде ничего не должно мешать проекту.
Вы пробовали, тестовое приложение в проекте? Оно работает? 
Также пробывали(перед `flutter run`) сначала выполнить `flutter clean`?

**Comment by MonsWriter** [comment]
> Не совсем понял, зачем надо "MainActivity.kt добавить метод onCreate"? В Readme же указано в configureFlutterEngine надо, внезависимости java или kotlin.
> 
> Для местоположения, насколько я знаю, `implementation 'com.google.android.gms:play-services-location:17.1.0' ` не нужна, главное иметь `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` в AndroidManifest.xml
> 
> По зависимостям, вроде ничего не должно мешать проекту.
> Вы пробовали, тестовое приложение в проекте? Оно работает?
> Также пробывали(перед `flutter run`) сначала выполнить `flutter clean`?

C configureFlutterEngine не компилируется. 

Без `implementation 'com.google.android.gms:play-services-location:17.1.0'` не работает отображение геолокации в Android, даже в тестовом проекте. 
Наткнулся на решение здесь: 
https://github.com/yandex/mapkit-android-demo/issues/170#issuecomment-668550229

`getSuggestions` в тестовом проекте тоже не работает.

`flutter clean` - пробовал, как и `flutter pub cache repair`.

**Comment by DCrow** [comment]
Еще раз пробывал создав новый проект, весь функционал работает без проблем.
Наткнулся на такой баг в репозитории флаттера, очень напоминает по описанию вашу проблему https://github.com/flutter/flutter/issues/70314

Попробуйте решение из этого issue, если не поможет, то просьба приложить репозиторий, где бага воспроизводится.

**Comment by DCrow** [comment]
Закрываю, так как нет активности
