### ISSUE TITLE
подскажите как редактировать rawImageData

### ISSUE THREAD

**Issue by Kizat** [Unact/yandex_mapkit#71]
я бы хотел цвет `rawImageData` поменять на другой, подскажите может есть где то редактор для этого

**Comment by DCrow** [comment]
Добрый день!

Если вы имеете ввиду переменную [rawImageData](https://github.com/Unact/yandex_mapkit/blob/master/example/lib/examples/data/dummy_image.dart#L2) из примера, то единственный способ поменять цвет это 
* Преобразовать байты в файл
* Обработать файл как хочется(paint, photoshop и тп)
* Обратно преобразовать файл в байты, как локально каким-либо языком программирования, либо онлайн(всякие hex /ascii редакторы обычно позволяют сохранить байты в отдельный файл)

Других способов лично не знаю, возможно есть какой-нить онлайн сервис.
