### ISSUE TITLE
Как отключить логи BufferQueueProducer ?

### ISSUE THREAD

**Issue by Frezyx** [Unact/yandex_mapkit#72]
Привет ✋ 
Спасибо большое за этот пакет !
Очень нужно было заиспользовать Яндекс Карты. 

Есть только один вопрос - можно ли как-то отключить логи ?
Очень сильно надоедают )

![image](https://user-images.githubusercontent.com/40857927/98963620-e072e100-2518-11eb-9e68-71b6085458ca.png)

**Comment by DCrow** [comment]
Добрый вечер!

Насчет лог лучше в оригинальных репозиториях для [Android](https://github.com/yandex/mapkit-android-demo)/[iOS](https://github.com/yandex/mapkit-ios-demo) спросить, они нативно включают.
Для iOS видел такое решение https://github.com/yandex/mapkit-ios-demo/issues/45
Для Android не встречал

**Comment by Frezyx** [comment]
Спасибо за подсказку, пойду искать)
