### ISSUE TITLE
How to set API KEY on MainActivity Kotlin version?

### ISSUE THREAD

**Issue by devmansurov** [Unact/yandex_mapkit#73]
I tried use this plugin can't set API KEY because in plugin README example with MainActivity.java (JAVA) file but in new version of flutter this file doesn't exists. In new version we have MainActivity.kt (KOTLIN) version of file. How we can set API KEY in this file correctly?

Flutter version: 1.22.4

**Comment by DCrow** [comment]
Hello!

It's the same for Kotlin/Android, same files, same functions. So for Kotlin 
```kotlin

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.embedding.engine.FlutterEngine
import com.yandex.mapkit.MapKitFactory

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setApiKey("YOUR_API_KEY");
        super.configureFlutterEngine(flutterEngine);
    }
}

```
