### ISSUE TITLE
The app crashes when running on iOS 14

### ISSUE THREAD

**Issue by topor00** [Unact/yandex_mapkit#75]
After updating to XCode 12 and build application, application crashes with yandex_mapkit on iOS14 on real devices . On iOS <14 it working successful .

**Comment by DCrow** [comment]
Hello!

This projects works with iOS 14 devices.
Maybe you're having this [problem](https://flutter.dev/docs/development/ios-14)?
If not please try running `flutter clean` `flutter pub cache repair`.
If that doesn't help then please add your `flutter doctor --verbose`

**Comment by DCrow** [comment]
Closing my previous question hasn't been answered.
