### ISSUE TITLE
How to move to user location on one click

### ISSUE THREAD

**Issue by devmansurov** [Unact/yandex_mapkit#77]
Current version of Yandex Mapkit package can't move to use on one click. Only when I doubleclick to move to user button then can show user location. How to move to user on 1 click with function `moveToUser()` ?

**Comment by DCrow** [comment]
Hello!

Please elaborate what problem you're experiencing. 

`YandexMapController.moveToUser` works as expected.
When it is called it positions the camera over user coordinates(if location permissions are granted)
