### ISSUE TITLE
It's possible to listen map zoom changes?

### ISSUE THREAD

**Issue by devmansurov** [Unact/yandex_mapkit#78]
Can I listen map zoom changes in this package?

I tried create navigation app and lister user location changes. Now I need to listen zoom changes to move user to new location using current map zoom.

**Comment by DCrow** [comment]
Hello!

You can use `YandexMapController.enableCameraTracking` to track zoom changes. 
When zoom changes(due to user gestures) the passed callback will be called with new zoom value.
