### ISSUE TITLE
Execution failed for task ':yandex_mapkit:verifyReleaseResources'.

### ISSUE THREAD

**Issue by Ishokov-Dzhafar** [Unact/yandex_mapkit#8]
При попытке собрать релизную сборку для android, вылезает такая ошибка:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':yandex_mapkit:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/****/Documents/projects/*****/build/yandex_mapkit/intermediates/res/merged/release/values/values.xml:275: error: resource android:attr/fontVariationSettings not found.
  /Users/****/Documents/projects/*****/build/yandex_mapkit/intermediates/res/merged/release/values/values.xml:276: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

Проект у меня уже мигрировал на androidx. Не могли бы вы сделать переход на androidx?

**Comment by Ishokov-Dzhafar** [comment]
Когда вручную прописываешь в build.gradle следующее, то ошибка пропадает:
compileSdkVersion 28

testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

**Comment by Ishokov-Dzhafar** [comment]
Я сделал миграцию, можешь посмотреть по этой ссылке https://github.com/Ishokov-Dzhafar/yandex_mapkit/commit/1eb69c4e3e30cc8af33303914bd4f07d76198396

**Comment by DCrow** [comment]
Спасибо за помощь в миграции. Теперь проект поддерживает AndroidX
