### ISSUE TITLE
[QUESTION] Does this package supports com.yandex.android:maps.mobile:4.0.0-full?

### ISSUE THREAD

**Issue by soloroman** [Unact/yandex_mapkit#80]
Is it possible to use latest Yandex Map sdk? or only 3.5.0?

**Comment by DCrow** [comment]
Hello!

No both iOS and Android are locked for 3.5.0. 
To work with 4.0.0-full this project has to be updated

**Comment by DCrow** [comment]
Updated this project to use newer iOS and Android libraries(4.0.0-full)
