### ISSUE TITLE
Ошибка при архивировании IOS приложения

### ISSUE THREAD

**Issue by kostyanchikoff** [Unact/yandex_mapkit#84]
При попытке архивировать приложение вылетает YendexMapsModile missing required architecture armv7 in file. При работе с симулятором все нормально отрабатывает.

**Comment by DCrow** [comment]
Доброе утрое!

Для текущей версии Mapkit 4.0.0, Яндекс убрал архитектуры armv7 и x86_64 для iOS. [См](https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/versions.html)
