### ISSUE TITLE
Изменение локали карты

### ISSUE THREAD

**Issue by mitskovets** [Unact/yandex_mapkit#86]
Подскажите, пожалуйста, как передать карте, что бы показывала на английском. Если передавать в YandexMapController и вызывать  в нем MapKitFactory.setLocale(lang), то при повторном открытии карты крашит приложение. Ругается, что язык нужно устанавливать до инициализации. А нужно делать смену языка в приложении. Спасибо.

**Comment by DCrow** [comment]
Добрый день.

Ругается уже низ лежащие либы для iOS/Android. 

**iOS** 
```
Locale is already set!             Locale can be only set once and before the first mapKit() or sharedInstnce() call.
```

**Android**
```
Locale is already set. Ignored.
```

Судя по сообщению ошибки, язык можно только один раз сменить, до запуска приложения содержащего YandexMapkit.
Поэтому сделать смену языка в приложении, чтобы при этом менялся язык на карте нельзя.

О таком функционале стоит спросить разработчиков нативных [Android](https://github.com/yandex/mapkit-android-demo)/[iOS](https://github.com/yandex/mapkit-ios-demo) либ.

**Comment by mitskovets** [comment]
Добрый день. Немного переделал смену языка, приложение уже не крашит.
Сделал смену языка в YandexMapFactory через SharedPreferences
`public class YandexMapFactory extends PlatformViewFactory {
  private final Registrar pluginRegistrar;

  public YandexMapFactory(Registrar registrar) {
    super(StandardMessageCodec.INSTANCE);
    pluginRegistrar = registrar;
    SharedPreferences sharedValue = registrar.context().getSharedPreferences("FlutterSharedPreferences", 0);
    String language = sharedValue.getString("flutter." + "languageCode", "");
    Log.d("SharedPreferences", "language:"+language);
    if(language != null && !language.equals("")) {
      String mpLocale = language + "_" + language.toUpperCase();
      MapKitFactory.setLocale(mpLocale);
    } else {
      String mpLocale = Locale.getDefault().getLanguage();
      MapKitFactory.setLocale(mpLocale);
    }
  }

  @Override
  public PlatformView create(Context context, int id, Object o) {
    return new YandexMapController(id, context, pluginRegistrar);
  }
}`
Приложение уже не крашится, но к сожалению язык не меняется, при смене языка и рестарте приложения.
Меняется только если выйти из приложения и зайти снова, тогда все в порядке.
т.е. flutter не рестартится совсем, нужно еще что-то придумать )))
Спасибо.

**Comment by DCrow** [comment]
Для передачи параметров при инициализации карты, стоит либо(если действие одноразовое), сразу в
```java
public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    MapKitFactory.setApiKey("YOUR_API_KEY");
    MapKitFactory.setLocale("YOUR_VALUE");
    super.configureFlutterEngine(flutterEngine);
  }
}
```
Либо же можно передавать таким образом
**yandex_map.dart**
```dart
class _YandexMapState extends State<YandexMap> {
  YandexMapController _controller;

  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
        viewType: YandexMap.viewType,
        onPlatformViewCreated: _onPlatformViewCreated,
        creationParamsCodec: const StandardMessageCodec(),
        creationParams: {
          'YOUR_PARAM_NAME': 'YOUR_VALUE'
        },
        gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer())
        ].toSet(),
      );
    } else {
      return UiKitView(
        viewType: YandexMap.viewType,
        onPlatformViewCreated: _onPlatformViewCreated,
        creationParamsCodec: const StandardMessageCodec(),
        creationParams: {
          'YOUR_PARAM_NAME': 'YOUR_VALUE'
        },
        gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer())
        ].toSet(),
      );
    }
  }
}
```

**YandexMapFactory.java**
```java
public class YandexMapFactory extends PlatformViewFactory {
  private final BinaryMessenger messenger;

  public YandexMapFactory(BinaryMessenger messenger) {
    super(StandardMessageCodec.INSTANCE);
    this.messenger = messenger;
  }

  @Override
  public PlatformView create(Context context, int id, Object o) {
    return new YandexMapController(id, context, messenger, o);
  }
}
```
**YandexMapController.java**
```java
public YandexMapController(int id, Context context, BinaryMessenger messenger, Object o) {
    Map<String, Object> params = ((Map<String, Object>) o);
    MapKitFactory.setLocale((String) params.get("lang"));
    MapKitFactory.initialize(context);
    mapView = new MapView(context);
    MapKitFactory.getInstance().onStart();
    mapView.onStart();

    yandexMapObjectTapListener = new YandexMapObjectTapListener();
    yandexMapInputListener = new YandexMapInputListener();
    yandexMapSizeChangedListener = new YandexMapSizeChangedListener();
    userLocationLayer = MapKitFactory.getInstance().createUserLocationLayer(mapView.getMapWindow());
    yandexUserLocationObjectListener = new YandexUserLocationObjectListener();

    methodChannel = new MethodChannel(messenger, "yandex_mapkit/yandex_map_" + id);
    methodChannel.setMethodCallHandler(this);

    mapView.getMap().addInputListener(yandexMapInputListener);
    mapView.getMapWindow().addSizeChangedListener(yandexMapSizeChangedListener);
  }
```

В обоих случаях можно проставить язык до полной инициализации либы. 

В любом случае YandexMapkit не дает изменять язык, в случаях когда библиотека уже инициализирована.

**Comment by mitskovets** [comment]
Да, я как раз пошел именно этим методом как у Вас в YandexMapController, через creationParams, но смены языка не получается при изменении языка в приложении, и приложение крашится.

**Comment by Hasanboy1998** [comment]
> Для передачи параметров при инициализации карты, стоит либо(если действие одноразовое), указывать сразу в **MainActivity.java**
> 
> ```java
> public class MainActivity extends FlutterActivity {
>   @Override
>   public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>     MapKitFactory.setApiKey("YOUR_API_KEY");
>     MapKitFactory.setLocale("YOUR_VALUE");
>     super.configureFlutterEngine(flutterEngine);
>   }
> }
> ```
> 
> Либо же можно передавать таким образом **yandex_map.dart**
> 
> ```dart
> class _YandexMapState extends State<YandexMap> {
>   YandexMapController _controller;
> 
>   @override
>   Widget build(BuildContext context) {
>     if (defaultTargetPlatform == TargetPlatform.android) {
>       return AndroidView(
>         viewType: YandexMap.viewType,
>         onPlatformViewCreated: _onPlatformViewCreated,
>         creationParamsCodec: const StandardMessageCodec(),
>         creationParams: {
>           'YOUR_PARAM_NAME': 'YOUR_VALUE'
>         },
>         gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
>           Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer())
>         ].toSet(),
>       );
>     } else {
>       return UiKitView(
>         viewType: YandexMap.viewType,
>         onPlatformViewCreated: _onPlatformViewCreated,
>         creationParamsCodec: const StandardMessageCodec(),
>         creationParams: {
>           'YOUR_PARAM_NAME': 'YOUR_VALUE'
>         },
>         gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
>           Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer())
>         ].toSet(),
>       );
>     }
>   }
> }
> ```
> 
> **YandexMapFactory.java**
> 
> ```java
> public class YandexMapFactory extends PlatformViewFactory {
>   private final BinaryMessenger messenger;
> 
>   public YandexMapFactory(BinaryMessenger messenger) {
>     super(StandardMessageCodec.INSTANCE);
>     this.messenger = messenger;
>   }
> 
>   @Override
>   public PlatformView create(Context context, int id, Object o) {
>     return new YandexMapController(id, context, messenger, o);
>   }
> }
> ```
> 
> **YandexMapController.java**
> 
> ```java
> public YandexMapController(int id, Context context, BinaryMessenger messenger, Object o) {
>     Map<String, Object> params = ((Map<String, Object>) o);
>     MapKitFactory.setLocale((String) params.get("YOUR_PARAM_NAME"));
>     MapKitFactory.initialize(context);
>     mapView = new MapView(context);
>     MapKitFactory.getInstance().onStart();
>     mapView.onStart();
> 
>     yandexMapObjectTapListener = new YandexMapObjectTapListener();
>     yandexMapInputListener = new YandexMapInputListener();
>     yandexMapSizeChangedListener = new YandexMapSizeChangedListener();
>     userLocationLayer = MapKitFactory.getInstance().createUserLocationLayer(mapView.getMapWindow());
>     yandexUserLocationObjectListener = new YandexUserLocationObjectListener();
> 
>     methodChannel = new MethodChannel(messenger, "yandex_mapkit/yandex_map_" + id);
>     methodChannel.setMethodCallHandler(this);
> 
>     mapView.getMap().addInputListener(yandexMapInputListener);
>     mapView.getMapWindow().addSizeChangedListener(yandexMapSizeChangedListener);
>   }
> ```
> 
> **YandexMapFactory.swift**
> 
> ```swift
> public class YandexMapFactory: NSObject, FlutterPlatformViewFactory {
>   private let pluginRegistrar: FlutterPluginRegistrar!
> 
>   public init(registrar: FlutterPluginRegistrar) {
>     self.pluginRegistrar = registrar
>     super.init()
>   }
>     
>   public func createArgsCodec() -> FlutterMessageCodec & NSObjectProtocol {
>     return FlutterStandardMessageCodec.sharedInstance()
>   }
> 
>   public func create(withFrame frame: CGRect,
>                      viewIdentifier viewId: Int64,
>                      arguments args: Any?) -> FlutterPlatformView {
>     return YandexMapController(id: viewId, frame: frame, registrar: self.pluginRegistrar, args: args)
>   }
> }
> ```
> 
> **YandexMapController.swift**
> 
> ```swift
> public required init(id: Int64, frame: CGRect, registrar: FlutterPluginRegistrar, args: Any?) {
>     let params = args as! [String: Any]
> 
>     YMKMapKit.setLocale(params["YOUR_PARAM_NAME"] as! String)
> 
>     self.pluginRegistrar = registrar
>     self.mapView = YMKMapView(frame: frame)
>     self.methodChannel = FlutterMethodChannel(
>       name: "yandex_mapkit/yandex_map_\(id)",
>       binaryMessenger: registrar.messenger()
>     )
>     self.mapTapListener = MapTapListener(channel: methodChannel)
>     self.mapObjectTapListener = MapObjectTapListener(channel: methodChannel)
>     self.mapSizeChangedListener = MapSizeChangedListener(channel: methodChannel)
>     self.userLocationLayer = YMKMapKit.sharedInstance().createUserLocationLayer(with: mapView.mapWindow)
> 
>     super.init()
> 
>     weak var weakSelf = self
>     self.methodChannel.setMethodCallHandler({ weakSelf?.handle($0, result: $1) })
> 
>     self.mapView.mapWindow.map.addInputListener(with: mapTapListener)
>     self.mapView.mapWindow.addSizeChangedListener(with: mapSizeChangedListener)
>   }
> ```
> 
> В обоих случаях можно проставить язык до полной инициализации либы.
> 
> В любом случае YandexMapkit не дает изменять язык, в случаях когда библиотека уже инициализирована.

Можете ли вы обновить это до текущей версии?

(Google translate uzbek -> rus)

**Comment by gidrokolbaska** [comment]
Можете плиз актуализировать свой пример до актуальной версии плагина?

**Comment by mitskovets** [comment]
Не работаю сейчас с картами, к сожалению), другие проекты
