### ISSUE TITLE
Placemark onTap() event passes tap coordinates but not Point

### ISSUE THREAD

**Issue by Tumist76** [Unact/yandex_mapkit#88]
Placemark onTap function passes `Point` with coordinates where user tapped the marker. It should pass `Point` with coordinates that were set in `Placemark` constructor.

```
Placemark(
      point: Point(
          latitude: wash.coordinates.latitude,
          longitude: wash.coordinates.longitude),
      style: PlacemarkStyle(iconName: marker, opacity: 0.9),
      onTap: (point) => selectWashByMarkerTap(point),
    );
```

`Point` properties that I set in `Placemark` constructor:
```
Point(
  latitude: 62.242478, 
  longitude: 74.532285
);
```

`Point` properties from event callback:
`Point(62.22261552459269, 74.11623848382754)`

**Comment by DCrow** [comment]
Hello!

This callback works the same as corresponding listener in [iOS](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Protocols/YMKMapObjectTapListener.html)/[Android](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObjectTapListener.html). 
It always returns the tapped point coordinates, not the tapped placemark coordinates.

**Comment by Tumist76** [comment]
Huh, that seems counterintuitive to me, but okay. A bit off-topic, but can you maybe suggest a solution then? I need to identify somehow, what marker was pressed, but can't find any unique properties except coordinates, which, as we see, are not tied to marker, but to tapped point.

**Comment by DCrow** [comment]
I wouldn't call this a good solution, but you can do something like this
```dart
Placemark placemark; 
placemark = Placemark(
  point: const Point(latitude: 0, longitude: 0),
  onTap: (Point point) => print(placemark.point),
);
```

In a more broad perspective `onTap` callback should be changed to include the calling placemark along with the tapped point.
Something like 
```dart
Placemark(
  point: const Point(latitude: 0, longitude: 0),
  onTap: (Placemark placemark, Point tappedPoint) => print(placemark.point),
);
```

**Comment by DCrow** [comment]
Changed `onTap` signature to also include the underlying `Placemark`
