### ISSUE TITLE
Is it possible to create a polygon with a hole inside ? (Flutter)

### ISSUE THREAD

**Issue by topor00** [Unact/yandex_mapkit#92]
I need to make a polygon with a fill color, but that it has a hole in the form of another polygon without a fill color. How can i do this?

**Comment by DCrow** [comment]
Hello!

This functionality isn't implemented in this library. 

You are always welcome to contribute to this library.
Mostly functionality concerning [`innerRings`](https://github.com/Unact/yandex_mapkit/blob/master/ios/Classes/YandexMapController.swift#L421) has to be implemented for it to work.

**Comment by DCrow** [comment]
Added the ability to add innerRings coordinates for `Polygon`
