### ISSUE TITLE
Не работает YandexSearch.getSuggestions

### ISSUE THREAD

**Issue by NazKok** [Unact/yandex_mapkit#96]
У меня не работает метод YandexSearch.getSuggestions, если в древе виджетов до этого не появлялся YandexMap. Взял для проверки приложение пример, которое прилагается к пакету, и заменил там YandexMap на простой текст. В итоге поиск тоже перестал работать (хотя для этого нужно полностью перезапустить приложение, если поменять виджет во время работы приложения и сделать хот релоад или рестарт, то поиск продолжит работать). В чем причина? Может я что-то не так делаю? Или этому методу нужен YandexMapController, который инициализируется при создании YandexMap?  Мне нужно использовать подсказки поиска адресов в местах приложения, в которые пользователь может попасть раньше, чем на страницу с картой

**Comment by DCrow** [comment]
Добрый день!

Сейчас действительно без использования `YandexMapController` не отдает результаты. 
Судя по всему бага, так как в примерах нативных либ карта не требуется.

**Comment by DCrow** [comment]
Решено в #125
